target: all
server:
  http_listen_port: 3200
storage:
  trace:
    backend: local
    local:
      path: /var/tempo/traces
    wal:
      path: /var/tempo/wal
overrides:
  defaults:
    ingestion:
      rate_limit_bytes: 5000000
  per_tenant_override_config: /etc/tempo/overrides.yaml
