apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: block-builder
  namespace: tracing
spec:
  podManagementPolicy: Parallel
  replicas: 0
  selector:
    matchLabels:
      app: block-builder
      name: block-builder
  serviceName: block-builder
  template:
    metadata:
      annotations:
        config_hash: 32561a7c801a4cc83b6f52f0f344dd19
        grafana.com/rollout-mirror-replicas-from-resource-api-version: apps/v1
        grafana.com/rollout-mirror-replicas-from-resource-kind: StatefulSet
        grafana.com/rollout-mirror-replicas-from-resource-name: live-store-zone-a
      labels:
        app: block-builder
        name: block-builder
        tempo-gossip-member: "true"
    spec:
      containers:
      - args:
        - -config.file=/conf/tempo.yaml
        - -target=block-builder
        image: grafana/tempo:latest
        imagePullPolicy: IfNotPresent
        name: block-builder
        ports:
        - containerPort: 3200
          name: prom-metrics
        readinessProbe:
          httpGet:
            path: /ready
            port: 3200
          initialDelaySeconds: 15
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 1Gi
        volumeMounts:
        - mountPath: /conf
          name: tempo-conf
        - mountPath: /var/tempo
          name: block-builder-data
        - mountPath: /overrides
          name: overrides
      securityContext:
        fsGroup: 10001
      terminationGracePeriodSeconds: 60
      volumes:
      - configMap:
          name: tempo-block-builder
        name: tempo-conf
      - configMap:
          name: tempo-overrides
        name: overrides
      - emptyDir:
          sizeLimit: 5Gi
        name: block-builder-data
  updateStrategy:
    type: RollingUpdate
