{
 "title": "Frigg",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" },
   { "name": "interval", "query": "1m,5m" },
   { "name": "component", "query": "-all-in-one,-compactor" }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "gcs",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(go_gc_duration_seconds_count{cluster=\"ops-tools1\", namespace=\"jaeger\", job=~\"jaeger/frigg$component\"}[$interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "go heap",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_inuse_bytes{cluster=\"ops-tools1\", namespace=\"jaeger\", job=~\"jaeger/frigg$component\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "goroutines",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{cluster=\"ops-tools1\", namespace=\"jaeger\", job=~\"jaeger/frigg$component\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "cpu",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{cluster=\"ops-tools1\", namespace=\"jaeger\", pod_name=~\"frigg$component.*\"}[$interval])",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "working set",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{cluster=\"ops-tools1\", namespace=\"jaeger\", pod_name=~\"frigg$component.*\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "rx",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{cluster=\"ops-tools1\", namespace=\"jaeger\", pod_name=~\"frigg$component.*\"}[$interval])"
    }
   ]
  },
  {
   "title": "data volume free",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "kubelet_volume_stats_available_bytes{cluster=\"ops-tools1\", namespace=\"jaeger\", persistentvolumeclaim=~\"frigg.*\"}",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "bad words",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(promtail_custom_bad_words_total{cluster=\"ops-tools1\", exported_namespace=\"jaeger\", app=~\"frigg$component.*\"}[$interval])",
     "legendFormat": "{{app}}"
    }
   ]
  },
  { "title": "Maintenance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Work Queue",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "friggdb_work_queue_length{job=~\"jaeger/frigg$component\"}",
     "legendFormat": "length"
    },
    {
     "expr": "friggdb_work_queue_max{job=~\"jaeger/frigg$component\"}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "maintenance cycles",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(friggdb_maintenance_total{job=~\"jaeger/frigg$component\"}[$interval])",
     "legendFormat": "maint-{{job}}"
    },
    {
     "expr": "increase(friggdb_compaction_errors_total{job=~\"jaeger/frigg$component\"}[$interval])",
     "legendFormat": "compaction_err"
    },
    {
     "expr": "increase(friggdb_retention_errors_total{job=~\"jaeger/frigg$component\"}[$interval])",
     "legendFormat": "retention_err"
    },
    {
     "expr": "increase(friggdb_blocklist_poll_errors_total{job=~\"jaeger/frigg$component\"}[$interval])",
     "legendFormat": "blocklist_err"
    }
   ]
  },
  {
   "title": "Blocklist Poll Duration",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum(rate(friggdb_blocklist_poll_duration_seconds_bucket{job=~\"jaeger/frigg$component\"}[$interval])) by (le))",
     "legendFormat": ".99"
    },
    {
     "expr": "histogram_quantile(.9, sum(rate(friggdb_blocklist_poll_duration_seconds_bucket{job=~\"jaeger/frigg$component\"}[$interval])) by (le))",
     "legendFormat": ".9"
    },
    {
     "expr": "histogram_quantile(.5, sum(rate(friggdb_blocklist_poll_duration_seconds_bucket{job=~\"jaeger/frigg$component\"}[$interval])) by (le))",
     "legendFormat": ".5"
    }
   ]
  },
  {
   "title": "Blocklist Length",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "friggdb_blocklist_length{job=~\"jaeger/frigg$component\"}",
     "legendFormat": "{{tenant}}-blocklist"
    },
    {
     "expr": "friggdb_compaction_blocklist_length{job=~\"jaeger/frigg$component\"}",
     "legendFormat": "{{tenant}}-compacted"
    }
   ]
  },
  {
   "title": "retention duration",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum(rate(friggdb_retention_duration_seconds_bucket{job=~\"jaeger/frigg$component\"}[$interval])) by (le))",
     "legendFormat": ".99"
    },
    {
     "expr": "histogram_quantile(.9, sum(rate(friggdb_retention_duration_seconds_bucket{job=~\"jaeger/frigg$component\"}[$interval])) by (le))",
     "legendFormat": ".9"
    },
    {
     "expr": "histogram_quantile(.5, sum(rate(friggdb_retention_duration_seconds_bucket{job=~\"jaeger/frigg$component\"}[$interval])) by (le))",
     "legendFormat": ".5"
    }
   ]
  },
  {
   "title": "compaction duration",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum(rate(friggdb_compaction_duration_seconds_bucket{job=~\"jaeger/frigg$component\"}[$interval])) by (le))",
     "legendFormat": ".99"
    },
    {
     "expr": "histogram_quantile(.9, sum(rate(friggdb_compaction_duration_seconds_bucket{job=~\"jaeger/frigg$component\"}[$interval])) by (le))",
     "legendFormat": ".9"
    },
    {
     "expr": "histogram_quantile(.5, sum(rate(friggdb_compaction_duration_seconds_bucket{job=~\"jaeger/frigg$component\"}[$interval])) by (le))",
     "legendFormat": ".5"
    }
   ]
  },
  {
   "title": "compaction stop duration",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum(rate(friggdb_compaction_duration_stop_seconds_bucket{job=~\"jaeger/frigg$component\"}[$interval])) by (le))",
     "legendFormat": ".99"
    },
    {
     "expr": "histogram_quantile(.9, sum(rate(friggdb_compaction_duration_stop_seconds_bucket{job=~\"jaeger/frigg$component\"}[$interval])) by (le))",
     "legendFormat": ".9"
    },
    {
     "expr": "histogram_quantile(.5, sum(rate(friggdb_compaction_duration_stop_seconds_bucket{job=~\"jaeger/frigg$component\"}[$interval])) by (le))",
     "legendFormat": ".5"
    }
   ]
  },
  {
   "title": "retention",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(friggdb_retention_deleted_total{job=~\"jaeger/frigg$component\"}[$interval])",
     "legendFormat": "deleted"
    },
    {
     "expr": "increase(friggdb_retention_marked_for_deletion_total{job=~\"jaeger/frigg$component\"}[$interval])",
     "legendFormat": "marked_for_deletion"
    }
   ]
  },
  {
   "title": "Compaction ID range",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "friggdb_compaction_id_range{job=~\"jaeger/frigg$component\"}",
     "legendFormat": "compacted_range"
    }
   ]
  },
  { "title": "Read", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Cache Lookups",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(friggdb_disk_cache_total[$interval])",
     "legendFormat": "{{type}}-{{status}}"
    }
   ]
  },
  {
   "title": "Cache Misses",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(friggdb_disk_cache_miss_total[$interval])",
     "legendFormat": "length"
    }
   ]
  },
  {
   "title": "Cache Purges",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(friggdb_disk_cache_clean_total[$interval])",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Query  Bytes Read",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum(rate(frigg_query_bytes_read_bucket[$interval])) by (le))",
     "legendFormat": ".99"
    },
    {
     "expr": "histogram_quantile(.9, sum(rate(frigg_query_bytes_read_bucket[$interval])) by (le))",
     "legendFormat": ".9"
    },
    {
     "expr": "histogram_quantile(.5, sum(rate(frigg_query_bytes_read_bucket[$interval])) by (le))",
     "legendFormat": ".5"
    }
   ]
  },
  {
   "title": "p99 Reads",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum(rate(frigg_query_reads_bucket[$interval])) by (layer, le))",
     "legendFormat": "{{layer}}"
    }
   ]
  },
  {
   "title": "p50 Reads",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(.5, sum(rate(frigg_query_reads_bucket[$interval])) by (layer, le))",
     "legendFormat": "{{layer}}"
    }
   ]
  },
  {
   "title": "Reads/Sec",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(frigg_request_duration_seconds_sum{route=\"/friggpb.Querier/FindTraceByID\"}[$interval])",
     "legendFormat": "{{layer}}"
    }
   ]
  },
  {
   "title": "Query Success Rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 8, "y": 23 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "frigg_request_duration_seconds_sum{route=\"/friggpb.Querier/FindTraceByID\", status_code=\"success\"} / frigg_request_duration_seconds_sum{route=\"/friggpb.Querier/FindTraceByID\"}"
    }
   ]
  },
  {
   "title": "Query Latency (Querier)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 15, "y": 23 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum(rate(frigg_request_duration_seconds_bucket{method=\"GET\", route=\"api_traces_traceid\"}[$interval])) by (le))",
     "legendFormat": ".99"
    },
    {
     "expr": "histogram_quantile(.9, sum(rate(frigg_request_duration_seconds_bucket{method=\"GET\", route=\"api_traces_traceid\"}[$interval])) by (le))",
     "legendFormat": ".9"
    },
    {
     "expr": "histogram_quantile(.5, sum(rate(frigg_request_duration_seconds_bucket{method=\"GET\", route=\"api_traces_traceid\"}[$interval])) by (le))",
     "legendFormat": ".5"
    }
   ]
  },
  {
   "title": "Query Latency (Ingester)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 15, "y": 28 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum(rate(frigg_request_duration_seconds_bucket{route=\"/friggpb.Querier/FindTraceByID\"}[$interval])) by (le))",
     "legendFormat": ".99"
    },
    {
     "expr": "histogram_quantile(.9, sum(rate(frigg_request_duration_seconds_bucket{route=\"/friggpb.Querier/FindTraceByID\"}[$interval])) by (le))",
     "legendFormat": ".9"
    },
    {
     "expr": "histogram_quantile(.5, sum(rate(frigg_request_duration_seconds_bucket{route=\"/friggpb.Querier/FindTraceByID\"}[$interval])) by (le))",
     "legendFormat": ".5"
    }
   ]
  },
  { "title": "Write", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Spans Received",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(frigg_distributor_spans_received_total[$interval])"
    }
   ]
  },
  {
   "title": "Traces Created",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(frigg_ingester_traces_created_total[$interval])"
    }
   ]
  },
  {
   "title": "Blocks Flushed",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(frigg_ingester_blocks_flushed_total[$interval])"
    }
   ]
  },
  {
   "title": "Failed Flushes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "frigg_ingester_failed_flushes_total"
    }
   ]
  },
  {
   "title": "Blocks Cleared",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(frigg_ingester_blocks_cleared_total[$interval])"
    }
   ]
  },
  {
   "title": "Flush Duration",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 34 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum(rate(frigg_ingester_flush_duration_seconds_bucket[$interval])) by (le))",
     "legendFormat": ".99"
    },
    {
     "expr": "histogram_quantile(.9, sum(rate(frigg_ingester_flush_duration_seconds_bucket[$interval])) by (le))",
     "legendFormat": ".9"
    },
    {
     "expr": "histogram_quantile(.5, sum(rate(ffrigg_ingester_flush_duration_seconds_bucket[$interval])) by (le))",
     "legendFormat": ".5"
    }
   ]
  },
  {
   "title": "Push Success Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "frigg_request_duration_seconds_sum{route=\"/friggpb.Pusher/Push\", status_code=\"success\"} / frigg_request_duration_seconds_sum{route=\"/friggpb.Pusher/Push\"}"
    }
   ]
  },
  {
   "title": "Push Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 39 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum(rate(frigg_request_duration_seconds_bucket{route=\"/friggpb.Pusher/Push\"}[$interval])) by (le))",
     "legendFormat": ".99"
    },
    {
     "expr": "histogram_quantile(.9, sum(rate(frigg_request_duration_seconds_bucket{route=\"/friggpb.Pusher/Push\"}[$interval])) by (le))",
     "legendFormat": ".9"
    },
    {
     "expr": "histogram_quantile(.5, sum(rate(frigg_request_duration_seconds_bucket{route=\"/friggpb.Pusher/Push\"}[$interval])) by (le))",
     "legendFormat": ".5"
    }
   ]
  },
  { "title": "GCS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Latency By Operation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum(rate(friggdb_gcs_request_duration_seconds_bucket{job=~\"jaeger/frigg$component\"}[$interval])) by (operation, le))",
     "legendFormat": ".99-{{operation}}"
    },
    {
     "expr": "histogram_quantile(.9, sum(rate(friggdb_gcs_request_duration_seconds_bucket{job=~\"jaeger/frigg$component\"}[$interval])) by (operation, le))",
     "legendFormat": ".9-{{operation}}"
    },
    {
     "expr": "histogram_quantile(.5, sum(rate(friggdb_gcs_request_duration_seconds_bucket{job=~\"jaeger/frigg$component\"}[$interval])) by (operation, le))",
     "legendFormat": ".5-{{operation}}"
    }
   ]
  },
  {
   "title": "Requests/Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(friggdb_gcs_request_duration_seconds_count{job=~\"jaeger/frigg$component\"}[$interval])) by (status_code, operation)",
     "legendFormat": "{{status_code}}-{{operation}}"
    }
   ]
  }
 ]
}