{
 "title": "tempo",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" },
   { "name": "interval", "query": "1m,5m" },
   {
    "name": "component",
    "query": "compactor,distributor,ingester,querier"
   },
   { "name": "cluster", "query": "ops-tools1" },
   {
    "name": "namespace",
    "query": "label_values(kube_pod_container_info{image=~\".*frigg.*\", cluster=\"$cluster\"}, namespace)"
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "gcs",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(go_gc_duration_seconds_count{cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$namespace/$component\"}[$interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "go heap",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_inuse_bytes{cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$namespace/$component\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "goroutines",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$namespace/$component\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "cpu",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{cluster=\"$cluster\", namespace=\"$namespace\", pod_name=~\"$component.*\", container_name!=\"POD\"}[$interval])",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "working set",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{cluster=\"$cluster\", namespace=\"$namespace\", pod_name=~\"$component.*\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "rx",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{cluster=\"$cluster\", namespace=\"$namespace\", pod_name=~\"$component.*\"}[$interval])",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "data volume free",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "kubelet_volume_stats_available_bytes{cluster=\"$cluster\", namespace=\"$namespace\", persistentvolumeclaim=~\"$component.*\"}",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "bad words",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(promtail_custom_bad_words_total{cluster=\"$cluster\", exported_namespace=\"$namespace\", app=~\"$component.*\"}[$interval])",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  { "title": "Maintenance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "%age total work queue",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "tempodb_work_queue_length{job=~\"$namespace/$component\"} / tempodb_work_queue_max{job=~\"$namespace/$component\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "maintenance cycles",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(tempodb_maintenance_total{job=~\"$namespace/$component\"}[$interval])) by (job)",
     "legendFormat": "maint-{{job}}"
    },
    {
     "expr": "sum(increase(tempodb_compaction_errors_total{job=~\"$namespace/$component\"}[$interval])) by (job)",
     "legendFormat": "compaction_err"
    },
    {
     "expr": "sum(increase(tempodb_retention_errors_total{job=~\"$namespace/$component\"}[$interval])) by (job)",
     "legendFormat": "retention_err"
    },
    {
     "expr": "sum(increase(tempodb_blocklist_poll_errors_total{job=~\"$namespace/$component\"}[$interval])) by (job)",
     "legendFormat": "blocklist_err"
    }
   ]
  },
  {
   "title": "Blocklist Poll Duration",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum(rate(tempodb_blocklist_poll_duration_seconds_bucket{job=~\"$namespace/$component\"}[$interval])) by (le))",
     "legendFormat": ".99"
    },
    {
     "expr": "histogram_quantile(.9, sum(rate(tempodb_blocklist_poll_duration_seconds_bucket{job=~\"$namespace/$component\"}[$interval])) by (le))",
     "legendFormat": ".9"
    },
    {
     "expr": "histogram_quantile(.5, sum(rate(tempodb_blocklist_poll_duration_seconds_bucket{job=~\"$namespace/$component\"}[$interval])) by (le))",
     "legendFormat": ".5"
    }
   ]
  },
  {
   "title": "Blocklist Length",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(tempodb_blocklist_length{job=~\"$namespace/$component\"}) by (tenant)",
     "legendFormat": "{{tenant}}-blocklist"
    },
    {
     "expr": "avg(tempodb_compaction_blocklist_length{job=~\"$namespace/$component\"}) by (tenant)",
     "legendFormat": "{{tenant}}-compacted"
    }
   ]
  },
  {
   "title": "retention duration",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum(rate(tempodb_retention_duration_seconds_bucket{job=~\"$namespace/$component\"}[$interval])) by (le))",
     "legendFormat": ".99"
    },
    {
     "expr": "histogram_quantile(.9, sum(rate(tempodb_retention_duration_seconds_bucket{job=~\"$namespace/$component\"}[$interval])) by (le))",
     "legendFormat": ".9"
    },
    {
     "expr": "histogram_quantile(.5, sum(rate(tempodb_retention_duration_seconds_bucket{job=~\"$namespace/$component\"}[$interval])) by (le))",
     "legendFormat": ".5"
    }
   ]
  },
  {
   "title": "compaction duration",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum(rate(tempodb_compaction_duration_seconds_bucket{job=~\"$namespace/$component\"}[$interval])) by (le, level))",
     "legendFormat": ".99-{{level}}"
    },
    {
     "expr": "histogram_quantile(.9, sum(rate(tempodb_compaction_duration_seconds_bucket{job=~\"$namespace/$component\"}[$interval])) by (le, level))",
     "legendFormat": ".9-{{level}}"
    },
    {
     "expr": "histogram_quantile(.5, sum(rate(tempodb_compaction_duration_seconds_bucket{job=~\"$namespace/$component\"}[$interval])) by (le, level))",
     "legendFormat": ".5-{{level}}"
    }
   ]
  },
  {
   "title": "compaction stop duration",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum(rate(tempodb_compaction_duration_stop_seconds_bucket{job=~\"$namespace/$component\"}[$interval])) by (le))",
     "legendFormat": ".99"
    },
    {
     "expr": "histogram_quantile(.9, sum(rate(tempodb_compaction_duration_stop_seconds_bucket{job=~\"$namespace/$component\"}[$interval])) by (le))",
     "legendFormat": ".9"
    },
    {
     "expr": "histogram_quantile(.5, sum(rate(tempodb_compaction_duration_stop_seconds_bucket{job=~\"$namespace/$component\"}[$interval])) by (le))",
     "legendFormat": ".5"
    }
   ]
  },
  {
   "title": "retention",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(tempodb_retention_deleted_total{job=~\"$namespace/$component\"}[$interval])",
     "legendFormat": "deleted"
    },
    {
     "expr": "increase(tempodb_retention_marked_for_deletion_total{job=~\"$namespace/$component\"}[$interval])",
     "legendFormat": "marked_for_deletion"
    }
   ]
  },
  { "title": "Read", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Cache Lookups",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(tempodb_disk_cache_total[$interval])",
     "legendFormat": "{{type}}-{{status}}"
    }
   ]
  },
  {
   "title": "Cache Misses",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(tempodb_disk_cache_miss_total[$interval])",
     "legendFormat": "length"
    }
   ]
  },
  {
   "title": "Cache Purges",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(tempodb_disk_cache_clean_total[$interval])",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Query  Bytes Read",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum(rate(tempo_query_bytes_read_bucket[$interval])) by (le))",
     "legendFormat": ".99"
    },
    {
     "expr": "histogram_quantile(.9, sum(rate(tempo_query_bytes_read_bucket[$interval])) by (le))",
     "legendFormat": ".9"
    },
    {
     "expr": "histogram_quantile(.5, sum(rate(tempo_query_bytes_read_bucket[$interval])) by (le))",
     "legendFormat": ".5"
    }
   ]
  },
  {
   "title": "p99 Reads",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum(rate(tempo_query_reads_bucket[$interval])) by (layer, le))",
     "legendFormat": "{{layer}}"
    }
   ]
  },
  {
   "title": "p50 Reads",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(.5, sum(rate(tempo_query_reads_bucket[$interval])) by (layer, le))",
     "legendFormat": "{{layer}}"
    }
   ]
  },
  {
   "title": "Reads/Sec",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(tempo_request_duration_seconds_sum{route=\"/tempopb.Querier/FindTraceByID\"}[$interval])",
     "legendFormat": "{{layer}}"
    }
   ]
  },
  {
   "title": "Query Success Rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "tempo_request_duration_seconds_sum{route=\"/tempopb.Querier/FindTraceByID\", status_code=\"success\"} / tempo_request_duration_seconds_sum{route=\"/tempopb.Querier/FindTraceByID\"}"
    }
   ]
  },
  {
   "title": "Query Latency (Querier)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 15, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum(rate(tempo_request_duration_seconds_bucket{method=\"GET\", route=\"api_traces_traceid\"}[$interval])) by (le))",
     "legendFormat": ".99"
    },
    {
     "expr": "histogram_quantile(.9, sum(rate(tempo_request_duration_seconds_bucket{method=\"GET\", route=\"api_traces_traceid\"}[$interval])) by (le))",
     "legendFormat": ".9"
    },
    {
     "expr": "histogram_quantile(.5, sum(rate(tempo_request_duration_seconds_bucket{method=\"GET\", route=\"api_traces_traceid\"}[$interval])) by (le))",
     "legendFormat": ".5"
    }
   ]
  },
  {
   "title": "Query Latency (Ingester)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 15, "y": 23 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum(rate(tempo_request_duration_seconds_bucket{route=\"/tempopb.Querier/FindTraceByID\"}[$interval])) by (le))",
     "legendFormat": ".99"
    },
    {
     "expr": "histogram_quantile(.9, sum(rate(tempo_request_duration_seconds_bucket{route=\"/tempopb.Querier/FindTraceByID\"}[$interval])) by (le))",
     "legendFormat": ".9"
    },
    {
     "expr": "histogram_quantile(.5, sum(rate(tempo_request_duration_seconds_bucket{route=\"/tempopb.Querier/FindTraceByID\"}[$interval])) by (le))",
     "legendFormat": ".5"
    }
   ]
  },
  { "title": "Write", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Spans Received",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(tempo_distributor_spans_received_total[$interval])"
    }
   ]
  },
  {
   "title": "Traces Created",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(tempo_ingester_traces_created_total[$interval])"
    }
   ]
  },
  {
   "title": "Blocks Flushed",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(tempo_ingester_blocks_flushed_total[$interval])"
    }
   ]
  },
  {
   "title": "Failed Flushes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tempo_ingester_failed_flushes_total"
    }
   ]
  },
  {
   "title": "Blocks Cleared",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(tempo_ingester_blocks_cleared_total[$interval])"
    }
   ]
  },
  {
   "title": "Flush Duration",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 29 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum(rate(tempo_ingester_flush_duration_seconds_bucket[$interval])) by (le))",
     "legendFormat": ".99"
    },
    {
     "expr": "histogram_quantile(.9, sum(rate(tempo_ingester_flush_duration_seconds_bucket[$interval])) by (le))",
     "legendFormat": ".9"
    },
    {
     "expr": "histogram_quantile(.5, sum(rate(ftempo_ingester_flush_duration_seconds_bucket[$interval])) by (le))",
     "legendFormat": ".5"
    }
   ]
  },
  {
   "title": "Traces / Batch",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(.9, sum(rate(tempo_distributor_traces_per_batch_bucket[$interval])) by (le))",
     "legendFormat": ".9"
    },
    {
     "expr": "histogram_quantile(.5, sum(rate(tempo_distributor_traces_per_batch_bucket[$interval])) by (le))",
     "legendFormat": ".5"
    },
    {
     "expr": "histogram_quantile(.1, sum(rate(tempo_distributor_traces_per_batch_bucket[$interval])) by (le))",
     "legendFormat": ".1"
    }
   ]
  },
  {
   "title": "Push Success Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "tempo_request_duration_seconds_sum{route=\"/tempopb.Pusher/Push\", status_code=\"success\"} / tempo_request_duration_seconds_sum{route=\"/tempopb.Pusher/Push\"}"
    }
   ]
  },
  {
   "title": "Push Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 34 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum(rate(tempo_request_duration_seconds_bucket{route=\"/tempopb.Pusher/Push\"}[$interval])) by (le))",
     "legendFormat": ".99"
    },
    {
     "expr": "histogram_quantile(.9, sum(rate(tempo_request_duration_seconds_bucket{route=\"/tempopb.Pusher/Push\"}[$interval])) by (le))",
     "legendFormat": ".9"
    },
    {
     "expr": "histogram_quantile(.5, sum(rate(tempo_request_duration_seconds_bucket{route=\"/tempopb.Pusher/Push\"}[$interval])) by (le))",
     "legendFormat": ".5"
    }
   ]
  },
  {
   "title": "GCS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latency By Operation",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(.99, sum(rate(tempodb_gcs_request_duration_seconds_bucket{job=~\"$namespace/$component\"}[$interval])) by (operation, le))",
       "legendFormat": ".99-{{operation}}"
      },
      {
       "expr": "histogram_quantile(.9, sum(rate(tempodb_gcs_request_duration_seconds_bucket{job=~\"$namespace/$component\"}[$interval])) by (operation, le))",
       "legendFormat": ".9-{{operation}}"
      },
      {
       "expr": "histogram_quantile(.5, sum(rate(tempodb_gcs_request_duration_seconds_bucket{job=~\"$namespace/$component\"}[$interval])) by (operation, le))",
       "legendFormat": ".5-{{operation}}"
      }
     ]
    },
    {
     "title": "Requests/Second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tempodb_gcs_request_duration_seconds_count{job=~\"$namespace/$component\"}[$interval])) by (status_code, operation)",
       "legendFormat": "{{status_code}}-{{operation}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Ring/Memberlist",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "Gossip Health",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "gauge_memberlist_health_score{cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$namespace/$component\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Node Health",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "memberlist_client_cluster_node_health_score{cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$namespace/$component\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Member Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "min(memberlist_client_cluster_members_count{cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$namespace/$component\"})",
       "legendFormat": "min"
      },
      {
       "expr": "max(memberlist_client_cluster_members_count{cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$namespace/$component\"})",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "KV Store Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "min(memberlist_client_kv_store_count{cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$namespace/$component\"})",
       "legendFormat": "min"
      },
      {
       "expr": "max(memberlist_client_kv_store_count{cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$namespace/$component\"})",
       "legendFormat": "max"
      }
     ]
    }
   ]
  }
 ]
}