storage:
  trace:
    blocklist_poll_stale_tenant_index: 1s # force components to always fall back to polling

backend_scheduler:
  provider:
    compaction:
      min_input_blocks: 100 # prevent compaction from triggering on small integration test blocks