FROM golang:alpine@sha256:e6898559d553d81b245eb8eadafcb3ca38ef320a9e26674df59d4f07a4fd0b07 AS build-dlv

RUN go install github.com/go-delve/delve/cmd/dlv@latest

FROM alpine:3.23@sha256:865b95f46d98cf867a156fe4a135ad3fe50d2056aa3f25ed31662dff6da4eb62 as certs
RUN apk --update add ca-certificates bash
ARG TARGETARCH
COPY bin/linux/tempo-${TARGETARCH} /tempo

COPY --from=build-dlv /go/bin/dlv /dlv
COPY /cmd/tempo/entrypoint-debug.sh /entrypoint-debug.sh
EXPOSE 2345
ENTRYPOINT [ "/entrypoint-debug.sh" ]
CMD []
