FROM golang:1.27.2-alpine@sha256:85dc1069ac644ea3c527b177303a406eb3358192816cd7f9e5848eb658851673 AS build-dlv

RUN go install github.com/go-delve/delve/cmd/dlv@v1.26.3

FROM alpine:3.24@sha256:28bd5fe8b56d1bd048e5babf5b10710ebe0bae67db86916198a6eec434943f8b as certs
RUN apk --update add ca-certificates bash
ARG TARGETARCH
COPY bin/linux/tempo-${TARGETARCH} /tempo

COPY --from=build-dlv /go/bin/dlv /dlv
COPY /cmd/tempo/entrypoint-debug.sh /entrypoint-debug.sh
EXPOSE 2345
ENTRYPOINT [ "/entrypoint-debug.sh" ]
CMD []
