{
 "title": "Frigg",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "interval", "query": "1m,5m" }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "gcs",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(go_gc_duration_seconds_count{job=\"frigg\"}[$interval])"
    }
   ]
  },
  {
   "title": "go heap",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{job=\"frigg\"}"
    }
   ]
  },
  {
   "title": "goroutines",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=\"frigg\"}"
    }
   ]
  },
  { "title": "Read", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "blocklist polling",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(friggdb_blocklist_poll_total[$interval])",
     "legendFormat": "poll"
    },
    {
     "expr": "rate(friggdb_blocklist_poll_errors_total[$interval])"
    }
   ]
  },
  {
   "title": "Blocklist Poll Duration",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum(rate(friggdb_blocklist_poll_duration_seconds_bucket[$interval])) by (le))",
     "legendFormat": ".99"
    },
    {
     "expr": "histogram_quantile(.9, sum(rate(friggdb_blocklist_poll_duration_seconds_bucket[$interval])) by (le))",
     "legendFormat": ".9"
    },
    {
     "expr": "histogram_quantile(.5, sum(rate(friggdb_blocklist_poll_duration_seconds_bucket[$interval])) by (le))",
     "legendFormat": ".5"
    }
   ]
  },
  {
   "title": "Query Queue",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "friggdb_query_queue_length", "legendFormat": "length" },
    { "expr": "friggdb_query_queue_max", "legendFormat": "max" }
   ]
  },
  {
   "title": "Cache Lookups",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(friggdb_disk_cache_total[$interval])",
     "legendFormat": "{{type}}-{{status}}"
    }
   ]
  },
  {
   "title": "Cache Misses",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(friggdb_disk_cache_miss_total[$interval])",
     "legendFormat": "length"
    }
   ]
  },
  {
   "title": "Cache Purges",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(friggdb_disk_cache_clean_total[$interval])",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Query  Bytes Read",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 7 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum(rate(frigg_query_bytes_read_bucket[$interval])) by (le))",
     "legendFormat": ".99"
    },
    {
     "expr": "histogram_quantile(.9, sum(rate(frigg_query_bytes_read_bucket[$interval])) by (le))",
     "legendFormat": ".9"
    },
    {
     "expr": "histogram_quantile(.5, sum(rate(frigg_query_bytes_read_bucket[$interval])) by (le))",
     "legendFormat": ".5"
    }
   ]
  },
  {
   "title": "Reads/Sec",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(frigg_request_duration_seconds_sum{route=\"/friggpb.Querier/FindTraceByID\"}[$interval])",
     "legendFormat": "{{layer}}"
    }
   ]
  },
  {
   "title": "Query Success Rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "frigg_request_duration_seconds_sum{route=\"/friggpb.Querier/FindTraceByID\", status_code=\"success\"} / frigg_request_duration_seconds_sum{route=\"/friggpb.Querier/FindTraceByID\"}"
    }
   ]
  },
  {
   "title": "Query Latency (Querier)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 15, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum(rate(frigg_request_duration_seconds_bucket{method=\"GET\", route=\"api_traces_traceid\"}[$interval])) by (le))",
     "legendFormat": ".99"
    },
    {
     "expr": "histogram_quantile(.9, sum(rate(frigg_request_duration_seconds_bucket{method=\"GET\", route=\"api_traces_traceid\"}[$interval])) by (le))",
     "legendFormat": ".9"
    },
    {
     "expr": "histogram_quantile(.5, sum(rate(frigg_request_duration_seconds_bucket{method=\"GET\", route=\"api_traces_traceid\"}[$interval])) by (le))",
     "legendFormat": ".5"
    }
   ]
  },
  {
   "title": "p99 Reads",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum(rate(frigg_query_reads_bucket[$interval])) by (layer, le))",
     "legendFormat": "{{layer}}"
    }
   ]
  },
  {
   "title": "Query Latency (Ingester)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 15, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum(rate(frigg_request_duration_seconds_bucket{route=\"/friggpb.Querier/FindTraceByID\"}[$interval])) by (le))",
     "legendFormat": ".99"
    },
    {
     "expr": "histogram_quantile(.9, sum(rate(frigg_request_duration_seconds_bucket{route=\"/friggpb.Querier/FindTraceByID\"}[$interval])) by (le))",
     "legendFormat": ".9"
    },
    {
     "expr": "histogram_quantile(.5, sum(rate(frigg_request_duration_seconds_bucket{route=\"/friggpb.Querier/FindTraceByID\"}[$interval])) by (le))",
     "legendFormat": ".5"
    }
   ]
  },
  {
   "title": "p50 Reads",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(.5, sum(rate(frigg_query_reads_bucket[$interval])) by (layer, le))",
     "legendFormat": "{{layer}}"
    }
   ]
  },
  { "title": "Write", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Spans Received",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(frigg_distributor_spans_received_total[$interval])"
    }
   ]
  },
  {
   "title": "Traces Created",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(frigg_ingester_traces_created_total[$interval])"
    }
   ]
  },
  {
   "title": "Blocks Flushed",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(frigg_ingester_blocks_flushed_total[$interval])"
    }
   ]
  },
  {
   "title": "Failed Flushes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "frigg_ingester_failed_flushes_total"
    }
   ]
  },
  {
   "title": "Blocks Cleared",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "frigg_ingester_blocks_cleared_total"
    }
   ]
  },
  {
   "title": "Complete Block Flush",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 23 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum(rate(frigg_ingester_flush_duration_seconds_bucket[$interval])) by (le))",
     "legendFormat": ".99"
    },
    {
     "expr": "histogram_quantile(.9, sum(rate(frigg_ingester_flush_duration_seconds_bucket[$interval])) by (le))",
     "legendFormat": ".9"
    },
    {
     "expr": "histogram_quantile(.5, sum(rate(ffrigg_ingester_flush_duration_seconds_bucket[$interval])) by (le))",
     "legendFormat": ".5"
    }
   ]
  },
  {
   "title": "Push Success Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "frigg_request_duration_seconds_sum{route=\"/friggpb.Pusher/Push\", status_code=\"success\"} / frigg_request_duration_seconds_sum{route=\"/friggpb.Pusher/Push\"}"
    }
   ]
  },
  {
   "title": "Push Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum(rate(frigg_request_duration_seconds_bucket{route=\"/friggpb.Pusher/Push\"}[$interval])) by (le))",
     "legendFormat": ".99"
    },
    {
     "expr": "histogram_quantile(.9, sum(rate(frigg_request_duration_seconds_bucket{route=\"/friggpb.Pusher/Push\"}[$interval])) by (le))",
     "legendFormat": ".9"
    },
    {
     "expr": "histogram_quantile(.5, sum(rate(frigg_request_duration_seconds_bucket{route=\"/friggpb.Pusher/Push\"}[$interval])) by (le))",
     "legendFormat": ".5"
    }
   ]
  },
  { "title": "GCS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Latency By Operation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum(rate(friggdb_gcs_request_duration_seconds_bucket[$interval])) by (operation, le))",
     "legendFormat": ".99-{{operation}}"
    },
    {
     "expr": "histogram_quantile(.9, sum(rate(friggdb_gcs_request_duration_seconds_bucket[$interval])) by (operation, le))",
     "legendFormat": ".9-{{operation}}"
    },
    {
     "expr": "histogram_quantile(.5, sum(rate(friggdb_gcs_request_duration_seconds_bucket[$interval])) by (operation, le))",
     "legendFormat": ".5-{{operation}}"
    }
   ]
  },
  {
   "title": "Latency By Operation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(friggdb_gcs_request_duration_seconds_count[$interval])) by (status_code, operation)",
     "legendFormat": "{{status_code}}-{{operation}}"
    }
   ]
  }
 ]
}