// Code generated by wiresmith. DO NOT EDIT.
// source: resource/v1/resource.proto

package v1

import (
	"fmt"
	commonv1 "github.com/grafana/tempo/pkg/tempopb/common/v1"
	"github.com/grafana/wiresmith/protohelpers"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/runtime/protoimpl"
	"reflect"
	"slices"
	"strings"
	"unsafe"
)

// Cold companion utilities for resource/v1/resource.proto.
//
// This file holds two cold concerns merged into one compilation unit:
//
//   - Reflection / registration glue: the per-message ProtoReflect()
//     methods, the per-enum Descriptor()/Type()/Number() methods, the
//     embedded FileDescriptorProto blob, the file_*_msgTypes /
//     file_*_enumTypes arrays, and the init() that registers everything
//     with protoregistry.GlobalFiles and protoregistry.GlobalTypes.
//   - The per-message String() debug dumps (hand-rolled, deterministic,
//     non-reflection — see compiler/generator/emit_string.go).
//
// None of these are called on the marshal / unmarshal / size hot path.
//
// Why a separate file? Putting this code (plus its descriptorpb /
// protoreflect / protoimpl imports — ~64KB of descriptorpb alone, ~377KB
// added to __TEXT overall) next to the hot Marshal/Unmarshal functions
// caused a measured +7–14% regression on otlp benchmarks (UnmarshalProfiles
// regressed by +12.6%) due to icache / iTLB / BTB pressure: the hot
// loops themselves were unchanged, but cold reflection code interleaved
// in the same compilation unit shifted hot functions onto different
// cache sets and pushed them ~131KB further into the binary. Emitting
// the cold half here, in its own .o, lets the linker place it away
// from the hot half and recovers that throughput. reflect and String()
// are both cold and were already split out, so merging them (cold→cold)
// preserves the rationale while halving the companion-file count.
//
// See compiler/generator/emit_registration.go for the full rationale
// and the benchmark methodology. DO NOT inline this file's contents
// back into the main .pb.go without re-measuring.

func (m *Resource) String() string {
	if m == nil {
		return "<nil>"
	}
	var b strings.Builder
	for _, e := range m.Attributes {
		b.WriteString("attributes: ")
		b.WriteString("{")
		b.WriteString(e.String())
		b.WriteString("}")
		b.WriteString(" ")
	}
	if m.DroppedAttributesCount != 0 {
		b.WriteString("dropped_attributes_count: ")
		fmt.Fprintf(&b, "%v", m.DroppedAttributesCount)
		b.WriteString(" ")
	}
	for _, e := range m.EntityRefs {
		b.WriteString("entity_refs: ")
		b.WriteString("{")
		b.WriteString(e.String())
		b.WriteString("}")
		b.WriteString(" ")
	}
	return strings.TrimSpace(b.String())
}

func (m *Resource) Clone() *Resource {
	if m == nil {
		return nil
	}
	out := &Resource{}
	out.Attributes = slices.Clone(m.Attributes)
	for i := range out.Attributes {
		out.Attributes[i] = *m.Attributes[i].Clone()
	}
	out.DroppedAttributesCount = m.DroppedAttributesCount
	out.EntityRefs = slices.Clone(m.EntityRefs)
	for i := range out.EntityRefs {
		out.EntityRefs[i] = out.EntityRefs[i].Clone()
	}
	return out
}

func (x *Resource) ProtoReflect() protoreflect.Message {
	file_resource_v1_resource_proto_init()
	return protohelpers.NewMessageReflect(&file_resource_v1_resource_proto_msgTypes[0], x)
}

const file_resource_v1_resource_proto_rawDesc = "" +
	"\x0a\x1a\x72\x65\x73\x6f\x75\x72\x63\x65\x2f\x76\x31\x2f\x72\x65\x73\x6f\x75\x72\x63\x65\x2e\x70\x72\x6f\x74\x6f\x12\x13\x74\x65\x6d\x70\x6f\x70\x62\x2e\x72\x65" +
	"\x73\x6f\x75\x72\x63\x65\x2e\x76\x31\x1a\x16\x63\x6f\x6d\x6d\x6f\x6e\x2f\x76\x31\x2f\x63\x6f\x6d\x6d\x6f\x6e\x2e\x70\x72\x6f\x74\x6f\x22\xc6\x01\x0a\x08\x52\x65" +
	"\x73\x6f\x75\x72\x63\x65\x12\x3b\x0a\x0a\x61\x74\x74\x72\x69\x62\x75\x74\x65\x73\x18\x01\x20\x03\x28\x0b\x32\x1b\x2e\x74\x65\x6d\x70\x6f\x70\x62\x2e\x63\x6f\x6d" +
	"\x6d\x6f\x6e\x2e\x76\x31\x2e\x4b\x65\x79\x56\x61\x6c\x75\x65\x52\x0a\x61\x74\x74\x72\x69\x62\x75\x74\x65\x73\x12\x38\x0a\x18\x64\x72\x6f\x70\x70\x65\x64\x5f\x61" +
	"\x74\x74\x72\x69\x62\x75\x74\x65\x73\x5f\x63\x6f\x75\x6e\x74\x18\x02\x20\x01\x28\x0d\x52\x16\x64\x72\x6f\x70\x70\x65\x64\x41\x74\x74\x72\x69\x62\x75\x74\x65\x73" +
	"\x43\x6f\x75\x6e\x74\x12\x43\x0a\x0b\x65\x6e\x74\x69\x74\x79\x5f\x72\x65\x66\x73\x18\x03\x20\x03\x28\x0b\x32\x1c\x2e\x74\x65\x6d\x70\x6f\x70\x62\x2e\x63\x6f\x6d" +
	"\x6d\x6f\x6e\x2e\x76\x31\x2e\x45\x6e\x74\x69\x74\x79\x52\x65\x66\x42\x04\xf0\xb6\x18\x01\x52\x0a\x65\x6e\x74\x69\x74\x79\x52\x65\x66\x73\x42\x84\x01\xc8\xb7\x18" +
	"\x01\x0a\x16\x69\x6f\x2e\x74\x65\x6d\x70\x6f\x70\x62\x2e\x72\x65\x73\x6f\x75\x72\x63\x65\x2e\x76\x31\x42\x0d\x52\x65\x73\x6f\x75\x72\x63\x65\x50\x72\x6f\x74\x6f" +
	"\x50\x01\x5a\x33\x67\x69\x74\x68\x75\x62\x2e\x63\x6f\x6d\x2f\x67\x72\x61\x66\x61\x6e\x61\x2f\x74\x65\x6d\x70\x6f\x2f\x70\x6b\x67\x2f\x74\x65\x6d\x70\x6f\x70\x62" +
	"\x2f\x72\x65\x73\x6f\x75\x72\x63\x65\x2f\x76\x31\x3b\x76\x31\xaa\x02\x1f\x4f\x70\x65\x6e\x54\x65\x6c\x65\x6d\x65\x74\x72\x79\x2e\x50\x72\x6f\x74\x6f\x2e\x52\x65" +
	"\x73\x6f\x75\x72\x63\x65\x2e\x56\x31\x62\x06\x70\x72\x6f\x74\x6f\x33"

var file_resource_v1_resource_proto_fd protoreflect.FileDescriptor

var file_resource_v1_resource_proto_msgTypes = make([]protoimpl.MessageInfo, 1)

var file_resource_v1_resource_proto_goTypes = []any{
	(*Resource)(nil),           // 0: tempopb.resource.v1.Resource
	(*commonv1.KeyValue)(nil),  // 1: tempopb.common.v1.KeyValue
	(*commonv1.EntityRef)(nil), // 2: tempopb.common.v1.EntityRef
}

var file_resource_v1_resource_proto_depIdxs = []int32{
	1, // 0: tempopb.resource.v1.Resource.attributes:type_name -> tempopb.common.v1.KeyValue
	2, // 1: tempopb.resource.v1.Resource.entity_refs:type_name -> tempopb.common.v1.EntityRef
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_resource_v1_resource_proto_init() }

func file_resource_v1_resource_proto_init() {
	if file_resource_v1_resource_proto_fd != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_resource_v1_resource_proto_rawDesc), len(file_resource_v1_resource_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_resource_v1_resource_proto_goTypes,
		DependencyIndexes: file_resource_v1_resource_proto_depIdxs,
		MessageInfos:      file_resource_v1_resource_proto_msgTypes,
	}.Build()
	file_resource_v1_resource_proto_fd = out.File
	file_resource_v1_resource_proto_goTypes = nil
	file_resource_v1_resource_proto_depIdxs = nil
}
