// Code generated by wiresmith. DO NOT EDIT.
// source: resource/v1/resource.proto

package v1

import (
	"fmt"
	commonv1 "github.com/grafana/tempo/pkg/tempopb/common/v1"
	"github.com/grafana/wiresmith/protohelpers"
	"google.golang.org/protobuf/encoding/protowire"
	"io"
	"math"
)

// Resource information.
type Resource struct {
	// Set of attributes that describe the resource.
	// Attribute keys MUST be unique (it is not allowed to have more than one
	// attribute with the same key).
	Attributes []*commonv1.KeyValue `protobuf:"bytes,1,rep,name=attributes,proto3" json:"attributes,omitempty"`
	// dropped_attributes_count is the number of dropped attributes. If the value is 0, then
	// no attributes were dropped.
	DroppedAttributesCount uint32 `protobuf:"varint,2,opt,name=dropped_attributes_count,json=droppedAttributesCount,proto3" json:"dropped_attributes_count,omitempty"`
}

func (m *Resource) Reset() {
	if m == nil {
		return
	}
	*m = Resource{}
}
func (*Resource) ProtoMessage() {}
func (m *Resource) String() string {
	if m == nil {
		return "<nil>"
	}
	return fmt.Sprintf("%v", *m)
}

func (m *Resource) GetAttributes() []*commonv1.KeyValue {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *Resource) GetDroppedAttributesCount() uint32 {
	if m != nil {
		return m.DroppedAttributesCount
	}
	return 0
}

func (m *Resource) Size() int {
	if m == nil {
		return 0
	}
	var n int
	for i := range m.Attributes {
		if m.Attributes[i] == nil {
			continue
		}
		s := (*m.Attributes[i]).Size()
		n += 1 + protowire.SizeVarint(uint64(s)) + s
	}
	if m.DroppedAttributesCount != 0 {
		n += 1 + protowire.SizeVarint(uint64(m.DroppedAttributesCount))
	}
	return n
}

func (m *Resource) Marshal() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.Size()
	dAtA = make([]byte, size)
	if size == 0 {
		return dAtA, nil
	}
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Resource) MarshalTo(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Resource) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	if m.DroppedAttributesCount != 0 {
		i = protohelpers.EncodeVarint(dAtA, i, uint64(m.DroppedAttributesCount))
		i--
		dAtA[i] = 0x10
	}
	for iNdEx := len(m.Attributes) - 1; iNdEx >= 0; iNdEx-- {
		if m.Attributes[iNdEx] == nil {
			continue
		}
		size, err := (*m.Attributes[iNdEx]).MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		if size <= 0x7F {
			dAtA[i-1] = uint8(size)
			i--
		} else {
			i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x0a
	}
	return len(dAtA) - i, nil
}

func (m *Resource) Unmarshal(b []byte) error {
	return m.unmarshal(b, 0)
}

func (m *Resource) UnmarshalWithDepth(b []byte, depth int) error {
	if depth < 0 {
		depth = 0
	}
	return m.unmarshal(b, depth)
}

func (m *Resource) unmarshal(dAtA []byte, depth int) error {
	if depth > protohelpers.MaxUnmarshalDepth {
		return fmt.Errorf("exceeded max recursion depth")
	}
	l := len(dAtA)
	iNdEx := 0
	if l >= 256 && depth >= 0 {
		var preIdx int
		var field1count int
		for preIdx < l {
			var preWire uint64
			for shift := uint(0); ; shift += 7 {
				if preIdx >= l {
					break
				}
				b := dAtA[preIdx]
				preIdx++
				preWire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			preNum := int32(preWire >> 3)
			preTyp := int(preWire & 0x7)
			switch preNum {
			case 1:
				field1count++
			}
			switch preTyp {
			case 0:
				for preIdx < l {
					preIdx++
					if dAtA[preIdx-1] < 0x80 {
						break
					}
				}
			case 1:
				preIdx += 8
			case 2:
				var preLen uint64
				for shift := uint(0); ; shift += 7 {
					if preIdx >= l {
						break
					}
					b := dAtA[preIdx]
					preIdx++
					preLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				preIdx += int(preLen)
			case 5:
				preIdx += 4
			default:
				preIdx = -1
			}
			if preIdx < 0 || preIdx > l {
				break
			}
		}
		preCapMax := l / 2
		if c := field1count; c > 0 {
			if c > preCapMax {
				c = preCapMax
			}
			if len(m.Attributes) == 0 && cap(m.Attributes) < c {
				m.Attributes = make([]*commonv1.KeyValue, 0, c)
			}
		}
	}
	for iNdEx < l {
		var wire uint64
		if iNdEx < l && dAtA[iNdEx] < 0x80 {
			wire = uint64(dAtA[iNdEx])
			iNdEx++
		} else {
			for shift := uint(0); ; shift += 7 {
				if shift >= 35 {
					return fmt.Errorf("proto: integer overflow")
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		}
		if wire>>3 < 1 || wire>>3 > 0x1FFFFFFF {
			return fmt.Errorf("invalid field number")
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		switch fieldNum {
		case 1: // attributes
			if wireType != 2 {
				n, err := protohelpers.SkipValue(dAtA[iNdEx:], wireType, fieldNum)
				if err != nil {
					return err
				}
				iNdEx += n
				continue
			}
			var byteLen uint64
			if iNdEx < l && dAtA[iNdEx] < 0x80 {
				byteLen = uint64(dAtA[iNdEx])
				iNdEx++
			} else {
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return fmt.Errorf("proto: integer overflow")
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					byteLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						if shift == 63 && b > 1 {
							return fmt.Errorf("proto: varint overflow")
						}
						break
					}
				}
			}
			if byteLen > uint64(math.MaxInt) {
				return io.ErrUnexpectedEOF
			}
			intByteLen := int(byteLen)
			postIndex := iNdEx + intByteLen
			if postIndex < 0 {
				return fmt.Errorf("proto: negative length")
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Attributes = append(m.Attributes, &commonv1.KeyValue{})
			if err := m.Attributes[len(m.Attributes)-1].UnmarshalWithDepth(dAtA[iNdEx:postIndex], depth+1); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2: // dropped_attributes_count
			if wireType != 0 {
				n, err := protohelpers.SkipValue(dAtA[iNdEx:], wireType, fieldNum)
				if err != nil {
					return err
				}
				iNdEx += n
				continue
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return fmt.Errorf("proto: integer overflow")
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint64(b&0x7F) << shift
				if b < 0x80 {
					if shift == 63 && b > 1 {
						return fmt.Errorf("proto: varint overflow")
					}
					break
				}
			}
			m.DroppedAttributesCount = uint32(v)
		default:
			n, err := protohelpers.SkipValue(dAtA[iNdEx:], wireType, fieldNum)
			if err != nil {
				return err
			}
			iNdEx += n
		}
	}
	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *Resource) UnmarshalNoPrescan(dAtA []byte) error {
	return m.unmarshal(dAtA, -1)
}
