// Code generated by wiresmith. DO NOT EDIT.
// source: tempopb/backendwork.proto

package tempopb

import (
	"fmt"
	"io"
	"math"
	"strconv"

	"github.com/grafana/wiresmith/protohelpers"
	"google.golang.org/protobuf/encoding/protowire"
)

type JobType int32

const (
	JobType_JOB_TYPE_UNSPECIFIED JobType = 0
	JobType_JOB_TYPE_COMPACTION  JobType = 1
	JobType_JOB_TYPE_RETENTION   JobType = 2
	JobType_JOB_TYPE_REDACTION   JobType = 3
)

var JobType_name = map[int32]string{
	0: "JOB_TYPE_UNSPECIFIED",
	1: "JOB_TYPE_COMPACTION",
	2: "JOB_TYPE_RETENTION",
	3: "JOB_TYPE_REDACTION",
}

var JobType_value = map[string]int32{
	"JOB_TYPE_UNSPECIFIED": 0,
	"JOB_TYPE_COMPACTION":  1,
	"JOB_TYPE_RETENTION":   2,
	"JOB_TYPE_REDACTION":   3,
}

func (x JobType) String() string {
	if name, ok := JobType_name[int32(x)]; ok {
		return name
	}
	return strconv.FormatInt(int64(x), 10)
}

type JobStatus int32

const (
	JobStatus_JOB_STATUS_UNSPECIFIED JobStatus = 0
	JobStatus_JOB_STATUS_SUCCEEDED   JobStatus = 1
	JobStatus_JOB_STATUS_FAILED      JobStatus = 2
	JobStatus_JOB_STATUS_RUNNING     JobStatus = 3
)

var JobStatus_name = map[int32]string{
	0: "JOB_STATUS_UNSPECIFIED",
	1: "JOB_STATUS_SUCCEEDED",
	2: "JOB_STATUS_FAILED",
	3: "JOB_STATUS_RUNNING",
}

var JobStatus_value = map[string]int32{
	"JOB_STATUS_UNSPECIFIED": 0,
	"JOB_STATUS_SUCCEEDED":   1,
	"JOB_STATUS_FAILED":      2,
	"JOB_STATUS_RUNNING":     3,
}

func (x JobStatus) String() string {
	if name, ok := JobStatus_name[int32(x)]; ok {
		return name
	}
	return strconv.FormatInt(int64(x), 10)
}

// CompactionDetail contains fields specific to compaction jobs
type CompactionDetail struct {
	Input  []string `protobuf:"bytes,1,rep,name=input,proto3" json:"input,omitempty"`
	Output []string `protobuf:"bytes,2,rep,name=output,proto3" json:"output,omitempty"`
}

type RetentionDetail struct {
}

// RedactionDetail contains fields for redaction jobs (one job per block).
// TraceIds are the trace IDs to redact from the block. Future extension may add
// traceql/attribute-based redaction.
type RedactionDetail struct {
	BlockId  string   `protobuf:"bytes,1,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`
	TraceIds [][]byte `protobuf:"bytes,2,rep,name=trace_ids,json=traceIds,proto3" json:"trace_ids,omitempty"`

	fieldsPresent [1]uint64
}

// JobDetail contains the specific details for each job type
type JobDetail struct {
	Tenant string `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	// oneof detail {
	Compaction *CompactionDetail `protobuf:"bytes,2,opt,name=compaction,proto3" json:"compaction,omitempty"`
	Retention  *RetentionDetail  `protobuf:"bytes,3,opt,name=retention,proto3" json:"retention,omitempty"`
	Redaction  *RedactionDetail  `protobuf:"bytes,4,opt,name=redaction,proto3" json:"redaction,omitempty"`
	// batch_id groups the pending jobs that were created from a single SubmitRedaction
	// call. Enables future Status/Cancel RPCs keyed on the original submission.
	BatchId string `protobuf:"bytes,5,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`

	fieldsPresent [1]uint64
}

type NextJobRequest struct {
	WorkerId string `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`

	fieldsPresent [1]uint64
}

type NextJobResponse struct {
	JobId  string    `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Type   JobType   `protobuf:"varint,2,opt,name=type,proto3,enum=tempopb.JobType" json:"type,omitempty"`
	Detail JobDetail `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`

	fieldsPresent [1]uint64
}

type UpdateJobStatusRequest struct {
	JobId      string            `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status     JobStatus         `protobuf:"varint,2,opt,name=status,proto3,enum=tempopb.JobStatus" json:"status,omitempty"`
	Error      string            `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	Compaction *CompactionDetail `protobuf:"bytes,4,opt,name=compaction,proto3" json:"compaction,omitempty"`
	Redaction  *RedactionResult  `protobuf:"bytes,5,opt,name=redaction,proto3" json:"redaction,omitempty"`

	fieldsPresent [1]uint64
}

type UpdateJobStatusResponse struct {
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`

	fieldsPresent [1]uint64
}

// SubmitRedactionRequest is the user-facing API for redacting traces from a tenant.
// The scheduler fans out one internal pending job per block for the authenticated tenant.
// The tenant is sourced exclusively from the X-Scope-OrgID request header; the server
// ignores tenant_id in the body to prevent cross-tenant escalation.
type SubmitRedactionRequest struct {
	TenantId string   `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	TraceIds [][]byte `protobuf:"bytes,2,rep,name=trace_ids,json=traceIds,proto3" json:"trace_ids,omitempty"`

	fieldsPresent [1]uint64
}

type SubmitRedactionResponse struct {
	// batch_id identifies this submission; all resulting pending block jobs share this ID.
	BatchId string `protobuf:"bytes,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	// jobs_created is the number of pending block-level redaction jobs that were enqueued.
	JobsCreated int32 `protobuf:"varint,2,opt,name=jobs_created,json=jobsCreated,proto3" json:"jobs_created,omitempty"`

	fieldsPresent [1]uint64
}

// RedactionResult is reported by the worker when a redaction job completes.
type RedactionResult struct {
	// traces_found is the number of target trace IDs that were present and removed
	// from the block. Zero means the block was scanned and found clean.
	TracesFound int32 `protobuf:"varint,1,opt,name=traces_found,json=tracesFound,proto3" json:"traces_found,omitempty"`

	fieldsPresent [1]uint64
}

// RedactionBatch holds the trace IDs for an in-flight redaction submission.
// All pending block jobs for a tenant share one batch to avoid copying the trace ID
// list into every job (which could be millions of jobs for large tenants).
// Persisted locally as batches.pb alongside the shard files.
type RedactionBatch struct {
	BatchId           string   `protobuf:"bytes,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	TenantId          string   `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	TraceIds          [][]byte `protobuf:"bytes,3,rep,name=trace_ids,json=traceIds,proto3" json:"trace_ids,omitempty"`
	CreatedAtUnixNano int64    `protobuf:"varint,4,opt,name=created_at_unix_nano,json=createdAtUnixNano,proto3" json:"created_at_unix_nano,omitempty"`
	// skipped_compaction_job_ids holds the IDs of compaction jobs whose input
	// blocks were skipped at submission time because they were actively compacting.
	// At rescan time the scheduler looks up these jobs and creates redaction jobs
	// for their output blocks.
	SkippedCompactionJobIds []string `protobuf:"bytes,5,rep,name=skipped_compaction_job_ids,json=skippedCompactionJobIds,proto3" json:"skipped_compaction_job_ids,omitempty"`
	// rescan_after_unix_nano is the earliest time at which the scheduler should
	// perform the rescan described above. Zero means no rescan is pending.
	RescanAfterUnixNano int64 `protobuf:"varint,6,opt,name=rescan_after_unix_nano,json=rescanAfterUnixNano,proto3" json:"rescan_after_unix_nano,omitempty"`

	fieldsPresent [1]uint64
}

// RedactionBatches is the top-level container written to batches.pb.
type RedactionBatches struct {
	Batches []*RedactionBatch `protobuf:"bytes,1,rep,name=batches,proto3" json:"batches,omitempty"`
}

func (m *CompactionDetail) Reset() {
	if m == nil {
		return
	}
	*m = CompactionDetail{}
}
func (*CompactionDetail) ProtoMessage() {}
func (m *CompactionDetail) String() string {
	if m == nil {
		return "<nil>"
	}
	return fmt.Sprintf("%v", *m)
}

func (m *RetentionDetail) Reset() {
	if m == nil {
		return
	}
	*m = RetentionDetail{}
}
func (*RetentionDetail) ProtoMessage() {}
func (m *RetentionDetail) String() string {
	if m == nil {
		return "<nil>"
	}
	return fmt.Sprintf("%v", *m)
}

func (m *RedactionDetail) Reset() {
	if m == nil {
		return
	}
	*m = RedactionDetail{}
}
func (*RedactionDetail) ProtoMessage() {}
func (m *RedactionDetail) String() string {
	if m == nil {
		return "<nil>"
	}
	return fmt.Sprintf("%v", *m)
}

func (m *JobDetail) Reset() {
	if m == nil {
		return
	}
	*m = JobDetail{}
}
func (*JobDetail) ProtoMessage() {}
func (m *JobDetail) String() string {
	if m == nil {
		return "<nil>"
	}
	return fmt.Sprintf("%v", *m)
}

func (m *NextJobRequest) Reset() {
	if m == nil {
		return
	}
	*m = NextJobRequest{}
}
func (*NextJobRequest) ProtoMessage() {}
func (m *NextJobRequest) String() string {
	if m == nil {
		return "<nil>"
	}
	return fmt.Sprintf("%v", *m)
}

func (m *NextJobResponse) Reset() {
	if m == nil {
		return
	}
	*m = NextJobResponse{}
}
func (*NextJobResponse) ProtoMessage() {}
func (m *NextJobResponse) String() string {
	if m == nil {
		return "<nil>"
	}
	return fmt.Sprintf("%v", *m)
}

func (m *UpdateJobStatusRequest) Reset() {
	if m == nil {
		return
	}
	*m = UpdateJobStatusRequest{}
}
func (*UpdateJobStatusRequest) ProtoMessage() {}
func (m *UpdateJobStatusRequest) String() string {
	if m == nil {
		return "<nil>"
	}
	return fmt.Sprintf("%v", *m)
}

func (m *UpdateJobStatusResponse) Reset() {
	if m == nil {
		return
	}
	*m = UpdateJobStatusResponse{}
}
func (*UpdateJobStatusResponse) ProtoMessage() {}
func (m *UpdateJobStatusResponse) String() string {
	if m == nil {
		return "<nil>"
	}
	return fmt.Sprintf("%v", *m)
}

func (m *SubmitRedactionRequest) Reset() {
	if m == nil {
		return
	}
	*m = SubmitRedactionRequest{}
}
func (*SubmitRedactionRequest) ProtoMessage() {}
func (m *SubmitRedactionRequest) String() string {
	if m == nil {
		return "<nil>"
	}
	return fmt.Sprintf("%v", *m)
}

func (m *SubmitRedactionResponse) Reset() {
	if m == nil {
		return
	}
	*m = SubmitRedactionResponse{}
}
func (*SubmitRedactionResponse) ProtoMessage() {}
func (m *SubmitRedactionResponse) String() string {
	if m == nil {
		return "<nil>"
	}
	return fmt.Sprintf("%v", *m)
}

func (m *RedactionResult) Reset() {
	if m == nil {
		return
	}
	*m = RedactionResult{}
}
func (*RedactionResult) ProtoMessage() {}
func (m *RedactionResult) String() string {
	if m == nil {
		return "<nil>"
	}
	return fmt.Sprintf("%v", *m)
}

func (m *RedactionBatch) Reset() {
	if m == nil {
		return
	}
	*m = RedactionBatch{}
}
func (*RedactionBatch) ProtoMessage() {}
func (m *RedactionBatch) String() string {
	if m == nil {
		return "<nil>"
	}
	return fmt.Sprintf("%v", *m)
}

func (m *RedactionBatches) Reset() {
	if m == nil {
		return
	}
	*m = RedactionBatches{}
}
func (*RedactionBatches) ProtoMessage() {}
func (m *RedactionBatches) String() string {
	if m == nil {
		return "<nil>"
	}
	return fmt.Sprintf("%v", *m)
}

func (m *RedactionDetail) HasBlockId() bool {
	if m == nil {
		return false
	}
	return m.fieldsPresent[0]&(1<<0) != 0
}

func (m *JobDetail) HasTenant() bool {
	if m == nil {
		return false
	}
	return m.fieldsPresent[0]&(1<<0) != 0
}

func (m *JobDetail) HasBatchId() bool {
	if m == nil {
		return false
	}
	return m.fieldsPresent[0]&(1<<1) != 0
}

func (m *NextJobRequest) HasWorkerId() bool {
	if m == nil {
		return false
	}
	return m.fieldsPresent[0]&(1<<0) != 0
}

func (m *NextJobResponse) HasJobId() bool {
	if m == nil {
		return false
	}
	return m.fieldsPresent[0]&(1<<0) != 0
}

func (m *NextJobResponse) HasType() bool {
	if m == nil {
		return false
	}
	return m.fieldsPresent[0]&(1<<1) != 0
}

func (m *NextJobResponse) HasDetail() bool {
	if m == nil {
		return false
	}
	return m.fieldsPresent[0]&(1<<2) != 0
}

func (m *UpdateJobStatusRequest) HasJobId() bool {
	if m == nil {
		return false
	}
	return m.fieldsPresent[0]&(1<<0) != 0
}

func (m *UpdateJobStatusRequest) HasStatus() bool {
	if m == nil {
		return false
	}
	return m.fieldsPresent[0]&(1<<1) != 0
}

func (m *UpdateJobStatusRequest) HasError() bool {
	if m == nil {
		return false
	}
	return m.fieldsPresent[0]&(1<<2) != 0
}

func (m *UpdateJobStatusResponse) HasSuccess() bool {
	if m == nil {
		return false
	}
	return m.fieldsPresent[0]&(1<<0) != 0
}

func (m *SubmitRedactionRequest) HasTenantId() bool {
	if m == nil {
		return false
	}
	return m.fieldsPresent[0]&(1<<0) != 0
}

func (m *SubmitRedactionResponse) HasBatchId() bool {
	if m == nil {
		return false
	}
	return m.fieldsPresent[0]&(1<<0) != 0
}

func (m *SubmitRedactionResponse) HasJobsCreated() bool {
	if m == nil {
		return false
	}
	return m.fieldsPresent[0]&(1<<1) != 0
}

func (m *RedactionResult) HasTracesFound() bool {
	if m == nil {
		return false
	}
	return m.fieldsPresent[0]&(1<<0) != 0
}

func (m *RedactionBatch) HasBatchId() bool {
	if m == nil {
		return false
	}
	return m.fieldsPresent[0]&(1<<0) != 0
}

func (m *RedactionBatch) HasTenantId() bool {
	if m == nil {
		return false
	}
	return m.fieldsPresent[0]&(1<<1) != 0
}

func (m *RedactionBatch) HasCreatedAtUnixNano() bool {
	if m == nil {
		return false
	}
	return m.fieldsPresent[0]&(1<<2) != 0
}

func (m *RedactionBatch) HasRescanAfterUnixNano() bool {
	if m == nil {
		return false
	}
	return m.fieldsPresent[0]&(1<<3) != 0
}

func (m *CompactionDetail) GetInput() []string {
	if m != nil {
		return m.Input
	}
	return nil
}

func (m *CompactionDetail) GetOutput() []string {
	if m != nil {
		return m.Output
	}
	return nil
}

func (m *RedactionDetail) GetBlockId() string {
	if m != nil {
		return m.BlockId
	}
	return ""
}

func (m *RedactionDetail) GetTraceIds() [][]byte {
	if m != nil {
		return m.TraceIds
	}
	return nil
}

func (m *JobDetail) GetTenant() string {
	if m != nil {
		return m.Tenant
	}
	return ""
}

func (m *JobDetail) GetCompaction() *CompactionDetail {
	if m != nil {
		return m.Compaction
	}
	return nil
}

func (m *JobDetail) GetRetention() *RetentionDetail {
	if m != nil {
		return m.Retention
	}
	return nil
}

func (m *JobDetail) GetRedaction() *RedactionDetail {
	if m != nil {
		return m.Redaction
	}
	return nil
}

func (m *JobDetail) GetBatchId() string {
	if m != nil {
		return m.BatchId
	}
	return ""
}

func (m *NextJobRequest) GetWorkerId() string {
	if m != nil {
		return m.WorkerId
	}
	return ""
}

func (m *NextJobResponse) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

func (m *NextJobResponse) GetType() JobType {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *NextJobResponse) GetDetail() *JobDetail {
	if m != nil && m.fieldsPresent[0]&(1<<2) != 0 {
		return &m.Detail
	}
	return nil
}

func (m *UpdateJobStatusRequest) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

func (m *UpdateJobStatusRequest) GetStatus() JobStatus {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *UpdateJobStatusRequest) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *UpdateJobStatusRequest) GetCompaction() *CompactionDetail {
	if m != nil {
		return m.Compaction
	}
	return nil
}

func (m *UpdateJobStatusRequest) GetRedaction() *RedactionResult {
	if m != nil {
		return m.Redaction
	}
	return nil
}

func (m *UpdateJobStatusResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *SubmitRedactionRequest) GetTenantId() string {
	if m != nil {
		return m.TenantId
	}
	return ""
}

func (m *SubmitRedactionRequest) GetTraceIds() [][]byte {
	if m != nil {
		return m.TraceIds
	}
	return nil
}

func (m *SubmitRedactionResponse) GetBatchId() string {
	if m != nil {
		return m.BatchId
	}
	return ""
}

func (m *SubmitRedactionResponse) GetJobsCreated() int32 {
	if m != nil {
		return m.JobsCreated
	}
	return 0
}

func (m *RedactionResult) GetTracesFound() int32 {
	if m != nil {
		return m.TracesFound
	}
	return 0
}

func (m *RedactionBatch) GetBatchId() string {
	if m != nil {
		return m.BatchId
	}
	return ""
}

func (m *RedactionBatch) GetTenantId() string {
	if m != nil {
		return m.TenantId
	}
	return ""
}

func (m *RedactionBatch) GetTraceIds() [][]byte {
	if m != nil {
		return m.TraceIds
	}
	return nil
}

func (m *RedactionBatch) GetCreatedAtUnixNano() int64 {
	if m != nil {
		return m.CreatedAtUnixNano
	}
	return 0
}

func (m *RedactionBatch) GetSkippedCompactionJobIds() []string {
	if m != nil {
		return m.SkippedCompactionJobIds
	}
	return nil
}

func (m *RedactionBatch) GetRescanAfterUnixNano() int64 {
	if m != nil {
		return m.RescanAfterUnixNano
	}
	return 0
}

func (m *RedactionBatches) GetBatches() []*RedactionBatch {
	if m != nil {
		return m.Batches
	}
	return nil
}

func (m *CompactionDetail) Size() int {
	if m == nil {
		return 0
	}
	var n int
	for _, v := range m.Input {
		n += 1 + protowire.SizeVarint(uint64(len(v))) + len(v)
	}
	for _, v := range m.Output {
		n += 1 + protowire.SizeVarint(uint64(len(v))) + len(v)
	}
	return n
}

func (m *RetentionDetail) Size() int {
	if m == nil {
		return 0
	}
	var n int
	return n
}

func (m *RedactionDetail) Size() int {
	if m == nil {
		return 0
	}
	var n int
	if len(m.BlockId) > 0 {
		n += 1 + protowire.SizeVarint(uint64(len(m.BlockId))) + len(m.BlockId)
	}
	for _, v := range m.TraceIds {
		n += 1 + protowire.SizeVarint(uint64(len(v))) + len(v)
	}
	return n
}

func (m *JobDetail) Size() int {
	if m == nil {
		return 0
	}
	var n int
	if len(m.Tenant) > 0 {
		n += 1 + protowire.SizeVarint(uint64(len(m.Tenant))) + len(m.Tenant)
	}
	if m.Compaction != nil {
		s := (*m.Compaction).Size()
		n += 1 + protowire.SizeVarint(uint64(s)) + s
	}
	if m.Retention != nil {
		s := (*m.Retention).Size()
		n += 1 + protowire.SizeVarint(uint64(s)) + s
	}
	if m.Redaction != nil {
		s := (*m.Redaction).Size()
		n += 1 + protowire.SizeVarint(uint64(s)) + s
	}
	if len(m.BatchId) > 0 {
		n += 1 + protowire.SizeVarint(uint64(len(m.BatchId))) + len(m.BatchId)
	}
	return n
}

func (m *NextJobRequest) Size() int {
	if m == nil {
		return 0
	}
	var n int
	if len(m.WorkerId) > 0 {
		n += 1 + protowire.SizeVarint(uint64(len(m.WorkerId))) + len(m.WorkerId)
	}
	return n
}

func (m *NextJobResponse) Size() int {
	if m == nil {
		return 0
	}
	var n int
	if len(m.JobId) > 0 {
		n += 1 + protowire.SizeVarint(uint64(len(m.JobId))) + len(m.JobId)
	}
	if m.Type != 0 {
		n += 1 + protowire.SizeVarint(uint64(m.Type))
	}
	{
		s := m.Detail.Size()
		if s > 0 {
			n += 1 + protowire.SizeVarint(uint64(s)) + s
		} else if m.fieldsPresent[0]&(1<<2) != 0 {
			n += 2
		}
	}
	return n
}

func (m *UpdateJobStatusRequest) Size() int {
	if m == nil {
		return 0
	}
	var n int
	if len(m.JobId) > 0 {
		n += 1 + protowire.SizeVarint(uint64(len(m.JobId))) + len(m.JobId)
	}
	if m.Status != 0 {
		n += 1 + protowire.SizeVarint(uint64(m.Status))
	}
	if len(m.Error) > 0 {
		n += 1 + protowire.SizeVarint(uint64(len(m.Error))) + len(m.Error)
	}
	if m.Compaction != nil {
		s := (*m.Compaction).Size()
		n += 1 + protowire.SizeVarint(uint64(s)) + s
	}
	if m.Redaction != nil {
		s := (*m.Redaction).Size()
		n += 1 + protowire.SizeVarint(uint64(s)) + s
	}
	return n
}

func (m *UpdateJobStatusResponse) Size() int {
	if m == nil {
		return 0
	}
	var n int
	if m.Success {
		n += 2
	}
	return n
}

func (m *SubmitRedactionRequest) Size() int {
	if m == nil {
		return 0
	}
	var n int
	if len(m.TenantId) > 0 {
		n += 1 + protowire.SizeVarint(uint64(len(m.TenantId))) + len(m.TenantId)
	}
	for _, v := range m.TraceIds {
		n += 1 + protowire.SizeVarint(uint64(len(v))) + len(v)
	}
	return n
}

func (m *SubmitRedactionResponse) Size() int {
	if m == nil {
		return 0
	}
	var n int
	if len(m.BatchId) > 0 {
		n += 1 + protowire.SizeVarint(uint64(len(m.BatchId))) + len(m.BatchId)
	}
	if m.JobsCreated != 0 {
		n += 1 + protowire.SizeVarint(uint64(m.JobsCreated))
	}
	return n
}

func (m *RedactionResult) Size() int {
	if m == nil {
		return 0
	}
	var n int
	if m.TracesFound != 0 {
		n += 1 + protowire.SizeVarint(uint64(m.TracesFound))
	}
	return n
}

func (m *RedactionBatch) Size() int {
	if m == nil {
		return 0
	}
	var n int
	if len(m.BatchId) > 0 {
		n += 1 + protowire.SizeVarint(uint64(len(m.BatchId))) + len(m.BatchId)
	}
	if len(m.TenantId) > 0 {
		n += 1 + protowire.SizeVarint(uint64(len(m.TenantId))) + len(m.TenantId)
	}
	for _, v := range m.TraceIds {
		n += 1 + protowire.SizeVarint(uint64(len(v))) + len(v)
	}
	if m.CreatedAtUnixNano != 0 {
		n += 1 + protowire.SizeVarint(uint64(m.CreatedAtUnixNano))
	}
	for _, v := range m.SkippedCompactionJobIds {
		n += 1 + protowire.SizeVarint(uint64(len(v))) + len(v)
	}
	if m.RescanAfterUnixNano != 0 {
		n += 1 + protowire.SizeVarint(uint64(m.RescanAfterUnixNano))
	}
	return n
}

func (m *RedactionBatches) Size() int {
	if m == nil {
		return 0
	}
	var n int
	for i := range m.Batches {
		if m.Batches[i] == nil {
			continue
		}
		s := (*m.Batches[i]).Size()
		n += 1 + protowire.SizeVarint(uint64(s)) + s
	}
	return n
}

func (m *CompactionDetail) Marshal() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.Size()
	dAtA = make([]byte, size)
	if size == 0 {
		return dAtA, nil
	}
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CompactionDetail) MarshalTo(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CompactionDetail) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	for iNdEx := len(m.Output) - 1; iNdEx >= 0; iNdEx-- {
		i -= len(m.Output[iNdEx])
		copy(dAtA[i:], m.Output[iNdEx])
		i = protohelpers.EncodeVarint(dAtA, i, uint64(len(m.Output[iNdEx])))
		i--
		dAtA[i] = 0x12
	}
	for iNdEx := len(m.Input) - 1; iNdEx >= 0; iNdEx-- {
		i -= len(m.Input[iNdEx])
		copy(dAtA[i:], m.Input[iNdEx])
		i = protohelpers.EncodeVarint(dAtA, i, uint64(len(m.Input[iNdEx])))
		i--
		dAtA[i] = 0x0a
	}
	return len(dAtA) - i, nil
}

func (m *RetentionDetail) Marshal() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.Size()
	dAtA = make([]byte, size)
	if size == 0 {
		return dAtA, nil
	}
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RetentionDetail) MarshalTo(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RetentionDetail) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	return len(dAtA) - i, nil
}

func (m *RedactionDetail) Marshal() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.Size()
	dAtA = make([]byte, size)
	if size == 0 {
		return dAtA, nil
	}
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RedactionDetail) MarshalTo(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RedactionDetail) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	for iNdEx := len(m.TraceIds) - 1; iNdEx >= 0; iNdEx-- {
		i -= len(m.TraceIds[iNdEx])
		copy(dAtA[i:], m.TraceIds[iNdEx])
		i = protohelpers.EncodeVarint(dAtA, i, uint64(len(m.TraceIds[iNdEx])))
		i--
		dAtA[i] = 0x12
	}
	if len(m.BlockId) > 0 {
		i -= len(m.BlockId)
		copy(dAtA[i:], m.BlockId)
		i = protohelpers.EncodeVarint(dAtA, i, uint64(len(m.BlockId)))
		i--
		dAtA[i] = 0x0a
	}
	return len(dAtA) - i, nil
}

func (m *JobDetail) Marshal() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.Size()
	dAtA = make([]byte, size)
	if size == 0 {
		return dAtA, nil
	}
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *JobDetail) MarshalTo(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *JobDetail) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	if len(m.BatchId) > 0 {
		i -= len(m.BatchId)
		copy(dAtA[i:], m.BatchId)
		i = protohelpers.EncodeVarint(dAtA, i, uint64(len(m.BatchId)))
		i--
		dAtA[i] = 0x2a
	}
	if m.Redaction != nil {
		size, err := (*m.Redaction).MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x22
	}
	if m.Retention != nil {
		size, err := (*m.Retention).MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x1a
	}
	if m.Compaction != nil {
		size, err := (*m.Compaction).MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Tenant) > 0 {
		i -= len(m.Tenant)
		copy(dAtA[i:], m.Tenant)
		i = protohelpers.EncodeVarint(dAtA, i, uint64(len(m.Tenant)))
		i--
		dAtA[i] = 0x0a
	}
	return len(dAtA) - i, nil
}

func (m *NextJobRequest) Marshal() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.Size()
	dAtA = make([]byte, size)
	if size == 0 {
		return dAtA, nil
	}
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NextJobRequest) MarshalTo(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *NextJobRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	if len(m.WorkerId) > 0 {
		i -= len(m.WorkerId)
		copy(dAtA[i:], m.WorkerId)
		i = protohelpers.EncodeVarint(dAtA, i, uint64(len(m.WorkerId)))
		i--
		dAtA[i] = 0x0a
	}
	return len(dAtA) - i, nil
}

func (m *NextJobResponse) Marshal() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.Size()
	dAtA = make([]byte, size)
	if size == 0 {
		return dAtA, nil
	}
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NextJobResponse) MarshalTo(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *NextJobResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	{
		size, err := m.Detail.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		if size > 0 {
			i -= size
			i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
			i--
			dAtA[i] = 0x1a
		} else if m.fieldsPresent[0]&(1<<2) != 0 {
			i--
			dAtA[i] = 0
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.Type != 0 {
		i = protohelpers.EncodeVarint(dAtA, i, uint64(m.Type))
		i--
		dAtA[i] = 0x10
	}
	if len(m.JobId) > 0 {
		i -= len(m.JobId)
		copy(dAtA[i:], m.JobId)
		i = protohelpers.EncodeVarint(dAtA, i, uint64(len(m.JobId)))
		i--
		dAtA[i] = 0x0a
	}
	return len(dAtA) - i, nil
}

func (m *UpdateJobStatusRequest) Marshal() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.Size()
	dAtA = make([]byte, size)
	if size == 0 {
		return dAtA, nil
	}
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UpdateJobStatusRequest) MarshalTo(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *UpdateJobStatusRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	if m.Redaction != nil {
		size, err := (*m.Redaction).MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x2a
	}
	if m.Compaction != nil {
		size, err := (*m.Compaction).MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Error) > 0 {
		i -= len(m.Error)
		copy(dAtA[i:], m.Error)
		i = protohelpers.EncodeVarint(dAtA, i, uint64(len(m.Error)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Status != 0 {
		i = protohelpers.EncodeVarint(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x10
	}
	if len(m.JobId) > 0 {
		i -= len(m.JobId)
		copy(dAtA[i:], m.JobId)
		i = protohelpers.EncodeVarint(dAtA, i, uint64(len(m.JobId)))
		i--
		dAtA[i] = 0x0a
	}
	return len(dAtA) - i, nil
}

func (m *UpdateJobStatusResponse) Marshal() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.Size()
	dAtA = make([]byte, size)
	if size == 0 {
		return dAtA, nil
	}
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UpdateJobStatusResponse) MarshalTo(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *UpdateJobStatusResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	if m.Success {
		i--
		if m.Success {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x08
	}
	return len(dAtA) - i, nil
}

func (m *SubmitRedactionRequest) Marshal() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.Size()
	dAtA = make([]byte, size)
	if size == 0 {
		return dAtA, nil
	}
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SubmitRedactionRequest) MarshalTo(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SubmitRedactionRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	for iNdEx := len(m.TraceIds) - 1; iNdEx >= 0; iNdEx-- {
		i -= len(m.TraceIds[iNdEx])
		copy(dAtA[i:], m.TraceIds[iNdEx])
		i = protohelpers.EncodeVarint(dAtA, i, uint64(len(m.TraceIds[iNdEx])))
		i--
		dAtA[i] = 0x12
	}
	if len(m.TenantId) > 0 {
		i -= len(m.TenantId)
		copy(dAtA[i:], m.TenantId)
		i = protohelpers.EncodeVarint(dAtA, i, uint64(len(m.TenantId)))
		i--
		dAtA[i] = 0x0a
	}
	return len(dAtA) - i, nil
}

func (m *SubmitRedactionResponse) Marshal() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.Size()
	dAtA = make([]byte, size)
	if size == 0 {
		return dAtA, nil
	}
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SubmitRedactionResponse) MarshalTo(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SubmitRedactionResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	if m.JobsCreated != 0 {
		i = protohelpers.EncodeVarint(dAtA, i, uint64(m.JobsCreated))
		i--
		dAtA[i] = 0x10
	}
	if len(m.BatchId) > 0 {
		i -= len(m.BatchId)
		copy(dAtA[i:], m.BatchId)
		i = protohelpers.EncodeVarint(dAtA, i, uint64(len(m.BatchId)))
		i--
		dAtA[i] = 0x0a
	}
	return len(dAtA) - i, nil
}

func (m *RedactionResult) Marshal() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.Size()
	dAtA = make([]byte, size)
	if size == 0 {
		return dAtA, nil
	}
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RedactionResult) MarshalTo(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RedactionResult) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	if m.TracesFound != 0 {
		i = protohelpers.EncodeVarint(dAtA, i, uint64(m.TracesFound))
		i--
		dAtA[i] = 0x08
	}
	return len(dAtA) - i, nil
}

func (m *RedactionBatch) Marshal() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.Size()
	dAtA = make([]byte, size)
	if size == 0 {
		return dAtA, nil
	}
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RedactionBatch) MarshalTo(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RedactionBatch) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	if m.RescanAfterUnixNano != 0 {
		i = protohelpers.EncodeVarint(dAtA, i, uint64(m.RescanAfterUnixNano))
		i--
		dAtA[i] = 0x30
	}
	for iNdEx := len(m.SkippedCompactionJobIds) - 1; iNdEx >= 0; iNdEx-- {
		i -= len(m.SkippedCompactionJobIds[iNdEx])
		copy(dAtA[i:], m.SkippedCompactionJobIds[iNdEx])
		i = protohelpers.EncodeVarint(dAtA, i, uint64(len(m.SkippedCompactionJobIds[iNdEx])))
		i--
		dAtA[i] = 0x2a
	}
	if m.CreatedAtUnixNano != 0 {
		i = protohelpers.EncodeVarint(dAtA, i, uint64(m.CreatedAtUnixNano))
		i--
		dAtA[i] = 0x20
	}
	for iNdEx := len(m.TraceIds) - 1; iNdEx >= 0; iNdEx-- {
		i -= len(m.TraceIds[iNdEx])
		copy(dAtA[i:], m.TraceIds[iNdEx])
		i = protohelpers.EncodeVarint(dAtA, i, uint64(len(m.TraceIds[iNdEx])))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.TenantId) > 0 {
		i -= len(m.TenantId)
		copy(dAtA[i:], m.TenantId)
		i = protohelpers.EncodeVarint(dAtA, i, uint64(len(m.TenantId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.BatchId) > 0 {
		i -= len(m.BatchId)
		copy(dAtA[i:], m.BatchId)
		i = protohelpers.EncodeVarint(dAtA, i, uint64(len(m.BatchId)))
		i--
		dAtA[i] = 0x0a
	}
	return len(dAtA) - i, nil
}

func (m *RedactionBatches) Marshal() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.Size()
	dAtA = make([]byte, size)
	if size == 0 {
		return dAtA, nil
	}
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RedactionBatches) MarshalTo(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RedactionBatches) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	for iNdEx := len(m.Batches) - 1; iNdEx >= 0; iNdEx-- {
		if m.Batches[iNdEx] == nil {
			continue
		}
		size, err := (*m.Batches[iNdEx]).MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x0a
	}
	return len(dAtA) - i, nil
}

// NOTE: maxUnmarshalDepth and skipValue are shared with the primary
// .pb.go of this Go package; the duplicate copies emitted for this
// file are stripped by `make gen-proto` (tools/strip-wiresmith-dup-helpers.py).

func (m *CompactionDetail) Unmarshal(b []byte) error {
	return m.unmarshal(b, 0)
}

func (m *CompactionDetail) UnmarshalWithDepth(b []byte, depth int) error {
	if depth < 0 {
		depth = 0
	}
	return m.unmarshal(b, depth)
}

func (m *CompactionDetail) unmarshal(dAtA []byte, depth int) error {
	if depth > maxUnmarshalDepth {
		return fmt.Errorf("exceeded max recursion depth")
	}
	l := len(dAtA)
	iNdEx := 0
	if l >= 256 {
		var preIdx int
		var field1count int
		var field2count int
		for preIdx < l {
			var preWire uint64
			for shift := uint(0); ; shift += 7 {
				if preIdx >= l {
					break
				}
				b := dAtA[preIdx]
				preIdx++
				preWire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			preNum := int32(preWire >> 3)
			preTyp := int(preWire & 0x7)
			switch preNum {
			case 1:
				field1count++
			case 2:
				field2count++
			}
			switch preTyp {
			case 0:
				for preIdx < l {
					preIdx++
					if dAtA[preIdx-1] < 0x80 {
						break
					}
				}
			case 1:
				preIdx += 8
			case 2:
				var preLen uint64
				for shift := uint(0); ; shift += 7 {
					if preIdx >= l {
						break
					}
					b := dAtA[preIdx]
					preIdx++
					preLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				preIdx += int(preLen)
			case 5:
				preIdx += 4
			default:
				preIdx = -1
			}
			if preIdx < 0 || preIdx > l {
				break
			}
		}
		preCapMax := l / 2
		if c := field1count; c > 0 {
			if c > preCapMax {
				c = preCapMax
			}
			m.Input = make([]string, 0, c)
		}
		if c := field2count; c > 0 {
			if c > preCapMax {
				c = preCapMax
			}
			m.Output = make([]string, 0, c)
		}
	}
	for iNdEx < l {
		var wire uint64
		if iNdEx < l && dAtA[iNdEx] < 0x80 {
			wire = uint64(dAtA[iNdEx])
			iNdEx++
		} else {
			for shift := uint(0); ; shift += 7 {
				if shift >= 35 {
					return fmt.Errorf("proto: integer overflow")
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		}
		if wire>>3 < 1 || wire>>3 > 0x1FFFFFFF {
			return fmt.Errorf("invalid field number")
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		switch fieldNum {
		case 1: // input
			if wireType != 2 {
				n, err := skipValue(dAtA[iNdEx:], wireType, fieldNum)
				if err != nil {
					return err
				}
				iNdEx += n
				continue
			}
			var byteLen uint64
			if iNdEx < l && dAtA[iNdEx] < 0x80 {
				byteLen = uint64(dAtA[iNdEx])
				iNdEx++
			} else {
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return fmt.Errorf("proto: integer overflow")
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					byteLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						if shift == 63 && b > 1 {
							return fmt.Errorf("proto: varint overflow")
						}
						break
					}
				}
			}
			if byteLen > uint64(math.MaxInt) {
				return io.ErrUnexpectedEOF
			}
			intByteLen := int(byteLen)
			postIndex := iNdEx + intByteLen
			if postIndex < 0 {
				return fmt.Errorf("proto: negative length")
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Input = append(m.Input, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 2: // output
			if wireType != 2 {
				n, err := skipValue(dAtA[iNdEx:], wireType, fieldNum)
				if err != nil {
					return err
				}
				iNdEx += n
				continue
			}
			var byteLen uint64
			if iNdEx < l && dAtA[iNdEx] < 0x80 {
				byteLen = uint64(dAtA[iNdEx])
				iNdEx++
			} else {
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return fmt.Errorf("proto: integer overflow")
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					byteLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						if shift == 63 && b > 1 {
							return fmt.Errorf("proto: varint overflow")
						}
						break
					}
				}
			}
			if byteLen > uint64(math.MaxInt) {
				return io.ErrUnexpectedEOF
			}
			intByteLen := int(byteLen)
			postIndex := iNdEx + intByteLen
			if postIndex < 0 {
				return fmt.Errorf("proto: negative length")
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Output = append(m.Output, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			n, err := skipValue(dAtA[iNdEx:], wireType, fieldNum)
			if err != nil {
				return err
			}
			iNdEx += n
		}
	}
	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *RetentionDetail) Unmarshal(b []byte) error {
	return m.unmarshal(b, 0)
}

func (m *RetentionDetail) UnmarshalWithDepth(b []byte, depth int) error {
	if depth < 0 {
		depth = 0
	}
	return m.unmarshal(b, depth)
}

func (m *RetentionDetail) unmarshal(dAtA []byte, depth int) error {
	if depth > maxUnmarshalDepth {
		return fmt.Errorf("exceeded max recursion depth")
	}
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		if iNdEx < l && dAtA[iNdEx] < 0x80 {
			wire = uint64(dAtA[iNdEx])
			iNdEx++
		} else {
			for shift := uint(0); ; shift += 7 {
				if shift >= 35 {
					return fmt.Errorf("proto: integer overflow")
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		}
		if wire>>3 < 1 || wire>>3 > 0x1FFFFFFF {
			return fmt.Errorf("invalid field number")
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		switch fieldNum {
		default:
			n, err := skipValue(dAtA[iNdEx:], wireType, fieldNum)
			if err != nil {
				return err
			}
			iNdEx += n
		}
	}
	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *RedactionDetail) Unmarshal(b []byte) error {
	return m.unmarshal(b, 0)
}

func (m *RedactionDetail) UnmarshalWithDepth(b []byte, depth int) error {
	if depth < 0 {
		depth = 0
	}
	return m.unmarshal(b, depth)
}

func (m *RedactionDetail) unmarshal(dAtA []byte, depth int) error {
	if depth > maxUnmarshalDepth {
		return fmt.Errorf("exceeded max recursion depth")
	}
	l := len(dAtA)
	iNdEx := 0
	if l >= 256 {
		var preIdx int
		var field2count int
		for preIdx < l {
			var preWire uint64
			for shift := uint(0); ; shift += 7 {
				if preIdx >= l {
					break
				}
				b := dAtA[preIdx]
				preIdx++
				preWire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			preNum := int32(preWire >> 3)
			preTyp := int(preWire & 0x7)
			switch preNum {
			case 2:
				field2count++
			}
			switch preTyp {
			case 0:
				for preIdx < l {
					preIdx++
					if dAtA[preIdx-1] < 0x80 {
						break
					}
				}
			case 1:
				preIdx += 8
			case 2:
				var preLen uint64
				for shift := uint(0); ; shift += 7 {
					if preIdx >= l {
						break
					}
					b := dAtA[preIdx]
					preIdx++
					preLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				preIdx += int(preLen)
			case 5:
				preIdx += 4
			default:
				preIdx = -1
			}
			if preIdx < 0 || preIdx > l {
				break
			}
		}
		preCapMax := l / 2
		if c := field2count; c > 0 {
			if c > preCapMax {
				c = preCapMax
			}
			m.TraceIds = make([][]byte, 0, c)
		}
	}
	for iNdEx < l {
		var wire uint64
		if iNdEx < l && dAtA[iNdEx] < 0x80 {
			wire = uint64(dAtA[iNdEx])
			iNdEx++
		} else {
			for shift := uint(0); ; shift += 7 {
				if shift >= 35 {
					return fmt.Errorf("proto: integer overflow")
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		}
		if wire>>3 < 1 || wire>>3 > 0x1FFFFFFF {
			return fmt.Errorf("invalid field number")
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		switch fieldNum {
		case 1: // block_id
			if wireType != 2 {
				n, err := skipValue(dAtA[iNdEx:], wireType, fieldNum)
				if err != nil {
					return err
				}
				iNdEx += n
				continue
			}
			var byteLen uint64
			if iNdEx < l && dAtA[iNdEx] < 0x80 {
				byteLen = uint64(dAtA[iNdEx])
				iNdEx++
			} else {
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return fmt.Errorf("proto: integer overflow")
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					byteLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						if shift == 63 && b > 1 {
							return fmt.Errorf("proto: varint overflow")
						}
						break
					}
				}
			}
			if byteLen > uint64(math.MaxInt) {
				return io.ErrUnexpectedEOF
			}
			intByteLen := int(byteLen)
			postIndex := iNdEx + intByteLen
			if postIndex < 0 {
				return fmt.Errorf("proto: negative length")
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BlockId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
			m.fieldsPresent[0] |= 1 << 0
		case 2: // trace_ids
			if wireType != 2 {
				n, err := skipValue(dAtA[iNdEx:], wireType, fieldNum)
				if err != nil {
					return err
				}
				iNdEx += n
				continue
			}
			var byteLen uint64
			if iNdEx < l && dAtA[iNdEx] < 0x80 {
				byteLen = uint64(dAtA[iNdEx])
				iNdEx++
			} else {
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return fmt.Errorf("proto: integer overflow")
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					byteLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						if shift == 63 && b > 1 {
							return fmt.Errorf("proto: varint overflow")
						}
						break
					}
				}
			}
			if byteLen > uint64(math.MaxInt) {
				return io.ErrUnexpectedEOF
			}
			intByteLen := int(byteLen)
			postIndex := iNdEx + intByteLen
			if postIndex < 0 {
				return fmt.Errorf("proto: negative length")
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TraceIds = append(m.TraceIds, append([]byte(nil), dAtA[iNdEx:postIndex]...))
			iNdEx = postIndex
		default:
			n, err := skipValue(dAtA[iNdEx:], wireType, fieldNum)
			if err != nil {
				return err
			}
			iNdEx += n
		}
	}
	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *JobDetail) Unmarshal(b []byte) error {
	return m.unmarshal(b, 0)
}

func (m *JobDetail) UnmarshalWithDepth(b []byte, depth int) error {
	if depth < 0 {
		depth = 0
	}
	return m.unmarshal(b, depth)
}

func (m *JobDetail) unmarshal(dAtA []byte, depth int) error {
	if depth > maxUnmarshalDepth {
		return fmt.Errorf("exceeded max recursion depth")
	}
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		if iNdEx < l && dAtA[iNdEx] < 0x80 {
			wire = uint64(dAtA[iNdEx])
			iNdEx++
		} else {
			for shift := uint(0); ; shift += 7 {
				if shift >= 35 {
					return fmt.Errorf("proto: integer overflow")
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		}
		if wire>>3 < 1 || wire>>3 > 0x1FFFFFFF {
			return fmt.Errorf("invalid field number")
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		switch fieldNum {
		case 1: // tenant
			if wireType != 2 {
				n, err := skipValue(dAtA[iNdEx:], wireType, fieldNum)
				if err != nil {
					return err
				}
				iNdEx += n
				continue
			}
			var byteLen uint64
			if iNdEx < l && dAtA[iNdEx] < 0x80 {
				byteLen = uint64(dAtA[iNdEx])
				iNdEx++
			} else {
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return fmt.Errorf("proto: integer overflow")
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					byteLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						if shift == 63 && b > 1 {
							return fmt.Errorf("proto: varint overflow")
						}
						break
					}
				}
			}
			if byteLen > uint64(math.MaxInt) {
				return io.ErrUnexpectedEOF
			}
			intByteLen := int(byteLen)
			postIndex := iNdEx + intByteLen
			if postIndex < 0 {
				return fmt.Errorf("proto: negative length")
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Tenant = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
			m.fieldsPresent[0] |= 1 << 0
		case 2: // compaction
			if wireType != 2 {
				n, err := skipValue(dAtA[iNdEx:], wireType, fieldNum)
				if err != nil {
					return err
				}
				iNdEx += n
				continue
			}
			var byteLen uint64
			if iNdEx < l && dAtA[iNdEx] < 0x80 {
				byteLen = uint64(dAtA[iNdEx])
				iNdEx++
			} else {
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return fmt.Errorf("proto: integer overflow")
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					byteLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						if shift == 63 && b > 1 {
							return fmt.Errorf("proto: varint overflow")
						}
						break
					}
				}
			}
			if byteLen > uint64(math.MaxInt) {
				return io.ErrUnexpectedEOF
			}
			intByteLen := int(byteLen)
			postIndex := iNdEx + intByteLen
			if postIndex < 0 {
				return fmt.Errorf("proto: negative length")
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Compaction == nil {
				m.Compaction = new(CompactionDetail)
			}
			if err := m.Compaction.unmarshal(dAtA[iNdEx:postIndex], depth+1); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3: // retention
			if wireType != 2 {
				n, err := skipValue(dAtA[iNdEx:], wireType, fieldNum)
				if err != nil {
					return err
				}
				iNdEx += n
				continue
			}
			var byteLen uint64
			if iNdEx < l && dAtA[iNdEx] < 0x80 {
				byteLen = uint64(dAtA[iNdEx])
				iNdEx++
			} else {
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return fmt.Errorf("proto: integer overflow")
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					byteLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						if shift == 63 && b > 1 {
							return fmt.Errorf("proto: varint overflow")
						}
						break
					}
				}
			}
			if byteLen > uint64(math.MaxInt) {
				return io.ErrUnexpectedEOF
			}
			intByteLen := int(byteLen)
			postIndex := iNdEx + intByteLen
			if postIndex < 0 {
				return fmt.Errorf("proto: negative length")
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Retention == nil {
				m.Retention = new(RetentionDetail)
			}
			if err := m.Retention.unmarshal(dAtA[iNdEx:postIndex], depth+1); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4: // redaction
			if wireType != 2 {
				n, err := skipValue(dAtA[iNdEx:], wireType, fieldNum)
				if err != nil {
					return err
				}
				iNdEx += n
				continue
			}
			var byteLen uint64
			if iNdEx < l && dAtA[iNdEx] < 0x80 {
				byteLen = uint64(dAtA[iNdEx])
				iNdEx++
			} else {
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return fmt.Errorf("proto: integer overflow")
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					byteLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						if shift == 63 && b > 1 {
							return fmt.Errorf("proto: varint overflow")
						}
						break
					}
				}
			}
			if byteLen > uint64(math.MaxInt) {
				return io.ErrUnexpectedEOF
			}
			intByteLen := int(byteLen)
			postIndex := iNdEx + intByteLen
			if postIndex < 0 {
				return fmt.Errorf("proto: negative length")
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Redaction == nil {
				m.Redaction = new(RedactionDetail)
			}
			if err := m.Redaction.unmarshal(dAtA[iNdEx:postIndex], depth+1); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5: // batch_id
			if wireType != 2 {
				n, err := skipValue(dAtA[iNdEx:], wireType, fieldNum)
				if err != nil {
					return err
				}
				iNdEx += n
				continue
			}
			var byteLen uint64
			if iNdEx < l && dAtA[iNdEx] < 0x80 {
				byteLen = uint64(dAtA[iNdEx])
				iNdEx++
			} else {
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return fmt.Errorf("proto: integer overflow")
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					byteLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						if shift == 63 && b > 1 {
							return fmt.Errorf("proto: varint overflow")
						}
						break
					}
				}
			}
			if byteLen > uint64(math.MaxInt) {
				return io.ErrUnexpectedEOF
			}
			intByteLen := int(byteLen)
			postIndex := iNdEx + intByteLen
			if postIndex < 0 {
				return fmt.Errorf("proto: negative length")
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BatchId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
			m.fieldsPresent[0] |= 1 << 1
		default:
			n, err := skipValue(dAtA[iNdEx:], wireType, fieldNum)
			if err != nil {
				return err
			}
			iNdEx += n
		}
	}
	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *NextJobRequest) Unmarshal(b []byte) error {
	return m.unmarshal(b, 0)
}

func (m *NextJobRequest) UnmarshalWithDepth(b []byte, depth int) error {
	if depth < 0 {
		depth = 0
	}
	return m.unmarshal(b, depth)
}

func (m *NextJobRequest) unmarshal(dAtA []byte, depth int) error {
	if depth > maxUnmarshalDepth {
		return fmt.Errorf("exceeded max recursion depth")
	}
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		if iNdEx < l && dAtA[iNdEx] < 0x80 {
			wire = uint64(dAtA[iNdEx])
			iNdEx++
		} else {
			for shift := uint(0); ; shift += 7 {
				if shift >= 35 {
					return fmt.Errorf("proto: integer overflow")
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		}
		if wire>>3 < 1 || wire>>3 > 0x1FFFFFFF {
			return fmt.Errorf("invalid field number")
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		switch fieldNum {
		case 1: // worker_id
			if wireType != 2 {
				n, err := skipValue(dAtA[iNdEx:], wireType, fieldNum)
				if err != nil {
					return err
				}
				iNdEx += n
				continue
			}
			var byteLen uint64
			if iNdEx < l && dAtA[iNdEx] < 0x80 {
				byteLen = uint64(dAtA[iNdEx])
				iNdEx++
			} else {
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return fmt.Errorf("proto: integer overflow")
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					byteLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						if shift == 63 && b > 1 {
							return fmt.Errorf("proto: varint overflow")
						}
						break
					}
				}
			}
			if byteLen > uint64(math.MaxInt) {
				return io.ErrUnexpectedEOF
			}
			intByteLen := int(byteLen)
			postIndex := iNdEx + intByteLen
			if postIndex < 0 {
				return fmt.Errorf("proto: negative length")
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WorkerId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
			m.fieldsPresent[0] |= 1 << 0
		default:
			n, err := skipValue(dAtA[iNdEx:], wireType, fieldNum)
			if err != nil {
				return err
			}
			iNdEx += n
		}
	}
	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *NextJobResponse) Unmarshal(b []byte) error {
	return m.unmarshal(b, 0)
}

func (m *NextJobResponse) UnmarshalWithDepth(b []byte, depth int) error {
	if depth < 0 {
		depth = 0
	}
	return m.unmarshal(b, depth)
}

func (m *NextJobResponse) unmarshal(dAtA []byte, depth int) error {
	if depth > maxUnmarshalDepth {
		return fmt.Errorf("exceeded max recursion depth")
	}
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		if iNdEx < l && dAtA[iNdEx] < 0x80 {
			wire = uint64(dAtA[iNdEx])
			iNdEx++
		} else {
			for shift := uint(0); ; shift += 7 {
				if shift >= 35 {
					return fmt.Errorf("proto: integer overflow")
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		}
		if wire>>3 < 1 || wire>>3 > 0x1FFFFFFF {
			return fmt.Errorf("invalid field number")
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		switch fieldNum {
		case 1: // job_id
			if wireType != 2 {
				n, err := skipValue(dAtA[iNdEx:], wireType, fieldNum)
				if err != nil {
					return err
				}
				iNdEx += n
				continue
			}
			var byteLen uint64
			if iNdEx < l && dAtA[iNdEx] < 0x80 {
				byteLen = uint64(dAtA[iNdEx])
				iNdEx++
			} else {
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return fmt.Errorf("proto: integer overflow")
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					byteLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						if shift == 63 && b > 1 {
							return fmt.Errorf("proto: varint overflow")
						}
						break
					}
				}
			}
			if byteLen > uint64(math.MaxInt) {
				return io.ErrUnexpectedEOF
			}
			intByteLen := int(byteLen)
			postIndex := iNdEx + intByteLen
			if postIndex < 0 {
				return fmt.Errorf("proto: negative length")
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.JobId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
			m.fieldsPresent[0] |= 1 << 0
		case 2: // type
			if wireType != 0 {
				n, err := skipValue(dAtA[iNdEx:], wireType, fieldNum)
				if err != nil {
					return err
				}
				iNdEx += n
				continue
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return fmt.Errorf("proto: integer overflow")
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint64(b&0x7F) << shift
				if b < 0x80 {
					if shift == 63 && b > 1 {
						return fmt.Errorf("proto: varint overflow")
					}
					break
				}
			}
			m.Type = JobType(v)
			m.fieldsPresent[0] |= 1 << 1
		case 3: // detail
			if wireType != 2 {
				n, err := skipValue(dAtA[iNdEx:], wireType, fieldNum)
				if err != nil {
					return err
				}
				iNdEx += n
				continue
			}
			var byteLen uint64
			if iNdEx < l && dAtA[iNdEx] < 0x80 {
				byteLen = uint64(dAtA[iNdEx])
				iNdEx++
			} else {
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return fmt.Errorf("proto: integer overflow")
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					byteLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						if shift == 63 && b > 1 {
							return fmt.Errorf("proto: varint overflow")
						}
						break
					}
				}
			}
			if byteLen > uint64(math.MaxInt) {
				return io.ErrUnexpectedEOF
			}
			intByteLen := int(byteLen)
			postIndex := iNdEx + intByteLen
			if postIndex < 0 {
				return fmt.Errorf("proto: negative length")
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Detail.unmarshal(dAtA[iNdEx:postIndex], depth+1); err != nil {
				return err
			}
			iNdEx = postIndex
			m.fieldsPresent[0] |= 1 << 2
		default:
			n, err := skipValue(dAtA[iNdEx:], wireType, fieldNum)
			if err != nil {
				return err
			}
			iNdEx += n
		}
	}
	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *UpdateJobStatusRequest) Unmarshal(b []byte) error {
	return m.unmarshal(b, 0)
}

func (m *UpdateJobStatusRequest) UnmarshalWithDepth(b []byte, depth int) error {
	if depth < 0 {
		depth = 0
	}
	return m.unmarshal(b, depth)
}

func (m *UpdateJobStatusRequest) unmarshal(dAtA []byte, depth int) error {
	if depth > maxUnmarshalDepth {
		return fmt.Errorf("exceeded max recursion depth")
	}
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		if iNdEx < l && dAtA[iNdEx] < 0x80 {
			wire = uint64(dAtA[iNdEx])
			iNdEx++
		} else {
			for shift := uint(0); ; shift += 7 {
				if shift >= 35 {
					return fmt.Errorf("proto: integer overflow")
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		}
		if wire>>3 < 1 || wire>>3 > 0x1FFFFFFF {
			return fmt.Errorf("invalid field number")
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		switch fieldNum {
		case 1: // job_id
			if wireType != 2 {
				n, err := skipValue(dAtA[iNdEx:], wireType, fieldNum)
				if err != nil {
					return err
				}
				iNdEx += n
				continue
			}
			var byteLen uint64
			if iNdEx < l && dAtA[iNdEx] < 0x80 {
				byteLen = uint64(dAtA[iNdEx])
				iNdEx++
			} else {
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return fmt.Errorf("proto: integer overflow")
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					byteLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						if shift == 63 && b > 1 {
							return fmt.Errorf("proto: varint overflow")
						}
						break
					}
				}
			}
			if byteLen > uint64(math.MaxInt) {
				return io.ErrUnexpectedEOF
			}
			intByteLen := int(byteLen)
			postIndex := iNdEx + intByteLen
			if postIndex < 0 {
				return fmt.Errorf("proto: negative length")
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.JobId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
			m.fieldsPresent[0] |= 1 << 0
		case 2: // status
			if wireType != 0 {
				n, err := skipValue(dAtA[iNdEx:], wireType, fieldNum)
				if err != nil {
					return err
				}
				iNdEx += n
				continue
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return fmt.Errorf("proto: integer overflow")
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint64(b&0x7F) << shift
				if b < 0x80 {
					if shift == 63 && b > 1 {
						return fmt.Errorf("proto: varint overflow")
					}
					break
				}
			}
			m.Status = JobStatus(v)
			m.fieldsPresent[0] |= 1 << 1
		case 3: // error
			if wireType != 2 {
				n, err := skipValue(dAtA[iNdEx:], wireType, fieldNum)
				if err != nil {
					return err
				}
				iNdEx += n
				continue
			}
			var byteLen uint64
			if iNdEx < l && dAtA[iNdEx] < 0x80 {
				byteLen = uint64(dAtA[iNdEx])
				iNdEx++
			} else {
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return fmt.Errorf("proto: integer overflow")
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					byteLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						if shift == 63 && b > 1 {
							return fmt.Errorf("proto: varint overflow")
						}
						break
					}
				}
			}
			if byteLen > uint64(math.MaxInt) {
				return io.ErrUnexpectedEOF
			}
			intByteLen := int(byteLen)
			postIndex := iNdEx + intByteLen
			if postIndex < 0 {
				return fmt.Errorf("proto: negative length")
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Error = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
			m.fieldsPresent[0] |= 1 << 2
		case 4: // compaction
			if wireType != 2 {
				n, err := skipValue(dAtA[iNdEx:], wireType, fieldNum)
				if err != nil {
					return err
				}
				iNdEx += n
				continue
			}
			var byteLen uint64
			if iNdEx < l && dAtA[iNdEx] < 0x80 {
				byteLen = uint64(dAtA[iNdEx])
				iNdEx++
			} else {
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return fmt.Errorf("proto: integer overflow")
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					byteLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						if shift == 63 && b > 1 {
							return fmt.Errorf("proto: varint overflow")
						}
						break
					}
				}
			}
			if byteLen > uint64(math.MaxInt) {
				return io.ErrUnexpectedEOF
			}
			intByteLen := int(byteLen)
			postIndex := iNdEx + intByteLen
			if postIndex < 0 {
				return fmt.Errorf("proto: negative length")
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Compaction == nil {
				m.Compaction = new(CompactionDetail)
			}
			if err := m.Compaction.unmarshal(dAtA[iNdEx:postIndex], depth+1); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5: // redaction
			if wireType != 2 {
				n, err := skipValue(dAtA[iNdEx:], wireType, fieldNum)
				if err != nil {
					return err
				}
				iNdEx += n
				continue
			}
			var byteLen uint64
			if iNdEx < l && dAtA[iNdEx] < 0x80 {
				byteLen = uint64(dAtA[iNdEx])
				iNdEx++
			} else {
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return fmt.Errorf("proto: integer overflow")
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					byteLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						if shift == 63 && b > 1 {
							return fmt.Errorf("proto: varint overflow")
						}
						break
					}
				}
			}
			if byteLen > uint64(math.MaxInt) {
				return io.ErrUnexpectedEOF
			}
			intByteLen := int(byteLen)
			postIndex := iNdEx + intByteLen
			if postIndex < 0 {
				return fmt.Errorf("proto: negative length")
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Redaction == nil {
				m.Redaction = new(RedactionResult)
			}
			if err := m.Redaction.unmarshal(dAtA[iNdEx:postIndex], depth+1); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			n, err := skipValue(dAtA[iNdEx:], wireType, fieldNum)
			if err != nil {
				return err
			}
			iNdEx += n
		}
	}
	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *UpdateJobStatusResponse) Unmarshal(b []byte) error {
	return m.unmarshal(b, 0)
}

func (m *UpdateJobStatusResponse) UnmarshalWithDepth(b []byte, depth int) error {
	if depth < 0 {
		depth = 0
	}
	return m.unmarshal(b, depth)
}

func (m *UpdateJobStatusResponse) unmarshal(dAtA []byte, depth int) error {
	if depth > maxUnmarshalDepth {
		return fmt.Errorf("exceeded max recursion depth")
	}
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		if iNdEx < l && dAtA[iNdEx] < 0x80 {
			wire = uint64(dAtA[iNdEx])
			iNdEx++
		} else {
			for shift := uint(0); ; shift += 7 {
				if shift >= 35 {
					return fmt.Errorf("proto: integer overflow")
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		}
		if wire>>3 < 1 || wire>>3 > 0x1FFFFFFF {
			return fmt.Errorf("invalid field number")
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		switch fieldNum {
		case 1: // success
			if wireType != 0 {
				n, err := skipValue(dAtA[iNdEx:], wireType, fieldNum)
				if err != nil {
					return err
				}
				iNdEx += n
				continue
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return fmt.Errorf("proto: integer overflow")
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint64(b&0x7F) << shift
				if b < 0x80 {
					if shift == 63 && b > 1 {
						return fmt.Errorf("proto: varint overflow")
					}
					break
				}
			}
			m.Success = v != 0
			m.fieldsPresent[0] |= 1 << 0
		default:
			n, err := skipValue(dAtA[iNdEx:], wireType, fieldNum)
			if err != nil {
				return err
			}
			iNdEx += n
		}
	}
	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *SubmitRedactionRequest) Unmarshal(b []byte) error {
	return m.unmarshal(b, 0)
}

func (m *SubmitRedactionRequest) UnmarshalWithDepth(b []byte, depth int) error {
	if depth < 0 {
		depth = 0
	}
	return m.unmarshal(b, depth)
}

func (m *SubmitRedactionRequest) unmarshal(dAtA []byte, depth int) error {
	if depth > maxUnmarshalDepth {
		return fmt.Errorf("exceeded max recursion depth")
	}
	l := len(dAtA)
	iNdEx := 0
	if l >= 256 {
		var preIdx int
		var field2count int
		for preIdx < l {
			var preWire uint64
			for shift := uint(0); ; shift += 7 {
				if preIdx >= l {
					break
				}
				b := dAtA[preIdx]
				preIdx++
				preWire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			preNum := int32(preWire >> 3)
			preTyp := int(preWire & 0x7)
			switch preNum {
			case 2:
				field2count++
			}
			switch preTyp {
			case 0:
				for preIdx < l {
					preIdx++
					if dAtA[preIdx-1] < 0x80 {
						break
					}
				}
			case 1:
				preIdx += 8
			case 2:
				var preLen uint64
				for shift := uint(0); ; shift += 7 {
					if preIdx >= l {
						break
					}
					b := dAtA[preIdx]
					preIdx++
					preLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				preIdx += int(preLen)
			case 5:
				preIdx += 4
			default:
				preIdx = -1
			}
			if preIdx < 0 || preIdx > l {
				break
			}
		}
		preCapMax := l / 2
		if c := field2count; c > 0 {
			if c > preCapMax {
				c = preCapMax
			}
			m.TraceIds = make([][]byte, 0, c)
		}
	}
	for iNdEx < l {
		var wire uint64
		if iNdEx < l && dAtA[iNdEx] < 0x80 {
			wire = uint64(dAtA[iNdEx])
			iNdEx++
		} else {
			for shift := uint(0); ; shift += 7 {
				if shift >= 35 {
					return fmt.Errorf("proto: integer overflow")
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		}
		if wire>>3 < 1 || wire>>3 > 0x1FFFFFFF {
			return fmt.Errorf("invalid field number")
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		switch fieldNum {
		case 1: // tenant_id
			if wireType != 2 {
				n, err := skipValue(dAtA[iNdEx:], wireType, fieldNum)
				if err != nil {
					return err
				}
				iNdEx += n
				continue
			}
			var byteLen uint64
			if iNdEx < l && dAtA[iNdEx] < 0x80 {
				byteLen = uint64(dAtA[iNdEx])
				iNdEx++
			} else {
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return fmt.Errorf("proto: integer overflow")
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					byteLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						if shift == 63 && b > 1 {
							return fmt.Errorf("proto: varint overflow")
						}
						break
					}
				}
			}
			if byteLen > uint64(math.MaxInt) {
				return io.ErrUnexpectedEOF
			}
			intByteLen := int(byteLen)
			postIndex := iNdEx + intByteLen
			if postIndex < 0 {
				return fmt.Errorf("proto: negative length")
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TenantId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
			m.fieldsPresent[0] |= 1 << 0
		case 2: // trace_ids
			if wireType != 2 {
				n, err := skipValue(dAtA[iNdEx:], wireType, fieldNum)
				if err != nil {
					return err
				}
				iNdEx += n
				continue
			}
			var byteLen uint64
			if iNdEx < l && dAtA[iNdEx] < 0x80 {
				byteLen = uint64(dAtA[iNdEx])
				iNdEx++
			} else {
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return fmt.Errorf("proto: integer overflow")
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					byteLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						if shift == 63 && b > 1 {
							return fmt.Errorf("proto: varint overflow")
						}
						break
					}
				}
			}
			if byteLen > uint64(math.MaxInt) {
				return io.ErrUnexpectedEOF
			}
			intByteLen := int(byteLen)
			postIndex := iNdEx + intByteLen
			if postIndex < 0 {
				return fmt.Errorf("proto: negative length")
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TraceIds = append(m.TraceIds, append([]byte(nil), dAtA[iNdEx:postIndex]...))
			iNdEx = postIndex
		default:
			n, err := skipValue(dAtA[iNdEx:], wireType, fieldNum)
			if err != nil {
				return err
			}
			iNdEx += n
		}
	}
	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *SubmitRedactionResponse) Unmarshal(b []byte) error {
	return m.unmarshal(b, 0)
}

func (m *SubmitRedactionResponse) UnmarshalWithDepth(b []byte, depth int) error {
	if depth < 0 {
		depth = 0
	}
	return m.unmarshal(b, depth)
}

func (m *SubmitRedactionResponse) unmarshal(dAtA []byte, depth int) error {
	if depth > maxUnmarshalDepth {
		return fmt.Errorf("exceeded max recursion depth")
	}
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		if iNdEx < l && dAtA[iNdEx] < 0x80 {
			wire = uint64(dAtA[iNdEx])
			iNdEx++
		} else {
			for shift := uint(0); ; shift += 7 {
				if shift >= 35 {
					return fmt.Errorf("proto: integer overflow")
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		}
		if wire>>3 < 1 || wire>>3 > 0x1FFFFFFF {
			return fmt.Errorf("invalid field number")
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		switch fieldNum {
		case 1: // batch_id
			if wireType != 2 {
				n, err := skipValue(dAtA[iNdEx:], wireType, fieldNum)
				if err != nil {
					return err
				}
				iNdEx += n
				continue
			}
			var byteLen uint64
			if iNdEx < l && dAtA[iNdEx] < 0x80 {
				byteLen = uint64(dAtA[iNdEx])
				iNdEx++
			} else {
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return fmt.Errorf("proto: integer overflow")
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					byteLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						if shift == 63 && b > 1 {
							return fmt.Errorf("proto: varint overflow")
						}
						break
					}
				}
			}
			if byteLen > uint64(math.MaxInt) {
				return io.ErrUnexpectedEOF
			}
			intByteLen := int(byteLen)
			postIndex := iNdEx + intByteLen
			if postIndex < 0 {
				return fmt.Errorf("proto: negative length")
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BatchId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
			m.fieldsPresent[0] |= 1 << 0
		case 2: // jobs_created
			if wireType != 0 {
				n, err := skipValue(dAtA[iNdEx:], wireType, fieldNum)
				if err != nil {
					return err
				}
				iNdEx += n
				continue
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return fmt.Errorf("proto: integer overflow")
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint64(b&0x7F) << shift
				if b < 0x80 {
					if shift == 63 && b > 1 {
						return fmt.Errorf("proto: varint overflow")
					}
					break
				}
			}
			m.JobsCreated = int32(v)
			m.fieldsPresent[0] |= 1 << 1
		default:
			n, err := skipValue(dAtA[iNdEx:], wireType, fieldNum)
			if err != nil {
				return err
			}
			iNdEx += n
		}
	}
	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *RedactionResult) Unmarshal(b []byte) error {
	return m.unmarshal(b, 0)
}

func (m *RedactionResult) UnmarshalWithDepth(b []byte, depth int) error {
	if depth < 0 {
		depth = 0
	}
	return m.unmarshal(b, depth)
}

func (m *RedactionResult) unmarshal(dAtA []byte, depth int) error {
	if depth > maxUnmarshalDepth {
		return fmt.Errorf("exceeded max recursion depth")
	}
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		if iNdEx < l && dAtA[iNdEx] < 0x80 {
			wire = uint64(dAtA[iNdEx])
			iNdEx++
		} else {
			for shift := uint(0); ; shift += 7 {
				if shift >= 35 {
					return fmt.Errorf("proto: integer overflow")
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		}
		if wire>>3 < 1 || wire>>3 > 0x1FFFFFFF {
			return fmt.Errorf("invalid field number")
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		switch fieldNum {
		case 1: // traces_found
			if wireType != 0 {
				n, err := skipValue(dAtA[iNdEx:], wireType, fieldNum)
				if err != nil {
					return err
				}
				iNdEx += n
				continue
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return fmt.Errorf("proto: integer overflow")
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint64(b&0x7F) << shift
				if b < 0x80 {
					if shift == 63 && b > 1 {
						return fmt.Errorf("proto: varint overflow")
					}
					break
				}
			}
			m.TracesFound = int32(v)
			m.fieldsPresent[0] |= 1 << 0
		default:
			n, err := skipValue(dAtA[iNdEx:], wireType, fieldNum)
			if err != nil {
				return err
			}
			iNdEx += n
		}
	}
	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *RedactionBatch) Unmarshal(b []byte) error {
	return m.unmarshal(b, 0)
}

func (m *RedactionBatch) UnmarshalWithDepth(b []byte, depth int) error {
	if depth < 0 {
		depth = 0
	}
	return m.unmarshal(b, depth)
}

func (m *RedactionBatch) unmarshal(dAtA []byte, depth int) error {
	if depth > maxUnmarshalDepth {
		return fmt.Errorf("exceeded max recursion depth")
	}
	l := len(dAtA)
	iNdEx := 0
	if l >= 256 {
		var preIdx int
		var field3count int
		var field5count int
		for preIdx < l {
			var preWire uint64
			for shift := uint(0); ; shift += 7 {
				if preIdx >= l {
					break
				}
				b := dAtA[preIdx]
				preIdx++
				preWire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			preNum := int32(preWire >> 3)
			preTyp := int(preWire & 0x7)
			switch preNum {
			case 3:
				field3count++
			case 5:
				field5count++
			}
			switch preTyp {
			case 0:
				for preIdx < l {
					preIdx++
					if dAtA[preIdx-1] < 0x80 {
						break
					}
				}
			case 1:
				preIdx += 8
			case 2:
				var preLen uint64
				for shift := uint(0); ; shift += 7 {
					if preIdx >= l {
						break
					}
					b := dAtA[preIdx]
					preIdx++
					preLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				preIdx += int(preLen)
			case 5:
				preIdx += 4
			default:
				preIdx = -1
			}
			if preIdx < 0 || preIdx > l {
				break
			}
		}
		preCapMax := l / 2
		if c := field3count; c > 0 {
			if c > preCapMax {
				c = preCapMax
			}
			m.TraceIds = make([][]byte, 0, c)
		}
		if c := field5count; c > 0 {
			if c > preCapMax {
				c = preCapMax
			}
			m.SkippedCompactionJobIds = make([]string, 0, c)
		}
	}
	for iNdEx < l {
		var wire uint64
		if iNdEx < l && dAtA[iNdEx] < 0x80 {
			wire = uint64(dAtA[iNdEx])
			iNdEx++
		} else {
			for shift := uint(0); ; shift += 7 {
				if shift >= 35 {
					return fmt.Errorf("proto: integer overflow")
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		}
		if wire>>3 < 1 || wire>>3 > 0x1FFFFFFF {
			return fmt.Errorf("invalid field number")
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		switch fieldNum {
		case 1: // batch_id
			if wireType != 2 {
				n, err := skipValue(dAtA[iNdEx:], wireType, fieldNum)
				if err != nil {
					return err
				}
				iNdEx += n
				continue
			}
			var byteLen uint64
			if iNdEx < l && dAtA[iNdEx] < 0x80 {
				byteLen = uint64(dAtA[iNdEx])
				iNdEx++
			} else {
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return fmt.Errorf("proto: integer overflow")
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					byteLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						if shift == 63 && b > 1 {
							return fmt.Errorf("proto: varint overflow")
						}
						break
					}
				}
			}
			if byteLen > uint64(math.MaxInt) {
				return io.ErrUnexpectedEOF
			}
			intByteLen := int(byteLen)
			postIndex := iNdEx + intByteLen
			if postIndex < 0 {
				return fmt.Errorf("proto: negative length")
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BatchId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
			m.fieldsPresent[0] |= 1 << 0
		case 2: // tenant_id
			if wireType != 2 {
				n, err := skipValue(dAtA[iNdEx:], wireType, fieldNum)
				if err != nil {
					return err
				}
				iNdEx += n
				continue
			}
			var byteLen uint64
			if iNdEx < l && dAtA[iNdEx] < 0x80 {
				byteLen = uint64(dAtA[iNdEx])
				iNdEx++
			} else {
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return fmt.Errorf("proto: integer overflow")
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					byteLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						if shift == 63 && b > 1 {
							return fmt.Errorf("proto: varint overflow")
						}
						break
					}
				}
			}
			if byteLen > uint64(math.MaxInt) {
				return io.ErrUnexpectedEOF
			}
			intByteLen := int(byteLen)
			postIndex := iNdEx + intByteLen
			if postIndex < 0 {
				return fmt.Errorf("proto: negative length")
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TenantId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
			m.fieldsPresent[0] |= 1 << 1
		case 3: // trace_ids
			if wireType != 2 {
				n, err := skipValue(dAtA[iNdEx:], wireType, fieldNum)
				if err != nil {
					return err
				}
				iNdEx += n
				continue
			}
			var byteLen uint64
			if iNdEx < l && dAtA[iNdEx] < 0x80 {
				byteLen = uint64(dAtA[iNdEx])
				iNdEx++
			} else {
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return fmt.Errorf("proto: integer overflow")
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					byteLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						if shift == 63 && b > 1 {
							return fmt.Errorf("proto: varint overflow")
						}
						break
					}
				}
			}
			if byteLen > uint64(math.MaxInt) {
				return io.ErrUnexpectedEOF
			}
			intByteLen := int(byteLen)
			postIndex := iNdEx + intByteLen
			if postIndex < 0 {
				return fmt.Errorf("proto: negative length")
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TraceIds = append(m.TraceIds, append([]byte(nil), dAtA[iNdEx:postIndex]...))
			iNdEx = postIndex
		case 4: // created_at_unix_nano
			if wireType != 0 {
				n, err := skipValue(dAtA[iNdEx:], wireType, fieldNum)
				if err != nil {
					return err
				}
				iNdEx += n
				continue
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return fmt.Errorf("proto: integer overflow")
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint64(b&0x7F) << shift
				if b < 0x80 {
					if shift == 63 && b > 1 {
						return fmt.Errorf("proto: varint overflow")
					}
					break
				}
			}
			m.CreatedAtUnixNano = int64(v)
			m.fieldsPresent[0] |= 1 << 2
		case 5: // skipped_compaction_job_ids
			if wireType != 2 {
				n, err := skipValue(dAtA[iNdEx:], wireType, fieldNum)
				if err != nil {
					return err
				}
				iNdEx += n
				continue
			}
			var byteLen uint64
			if iNdEx < l && dAtA[iNdEx] < 0x80 {
				byteLen = uint64(dAtA[iNdEx])
				iNdEx++
			} else {
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return fmt.Errorf("proto: integer overflow")
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					byteLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						if shift == 63 && b > 1 {
							return fmt.Errorf("proto: varint overflow")
						}
						break
					}
				}
			}
			if byteLen > uint64(math.MaxInt) {
				return io.ErrUnexpectedEOF
			}
			intByteLen := int(byteLen)
			postIndex := iNdEx + intByteLen
			if postIndex < 0 {
				return fmt.Errorf("proto: negative length")
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SkippedCompactionJobIds = append(m.SkippedCompactionJobIds, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 6: // rescan_after_unix_nano
			if wireType != 0 {
				n, err := skipValue(dAtA[iNdEx:], wireType, fieldNum)
				if err != nil {
					return err
				}
				iNdEx += n
				continue
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return fmt.Errorf("proto: integer overflow")
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint64(b&0x7F) << shift
				if b < 0x80 {
					if shift == 63 && b > 1 {
						return fmt.Errorf("proto: varint overflow")
					}
					break
				}
			}
			m.RescanAfterUnixNano = int64(v)
			m.fieldsPresent[0] |= 1 << 3
		default:
			n, err := skipValue(dAtA[iNdEx:], wireType, fieldNum)
			if err != nil {
				return err
			}
			iNdEx += n
		}
	}
	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *RedactionBatches) Unmarshal(b []byte) error {
	return m.unmarshal(b, 0)
}

func (m *RedactionBatches) UnmarshalWithDepth(b []byte, depth int) error {
	if depth < 0 {
		depth = 0
	}
	return m.unmarshal(b, depth)
}

func (m *RedactionBatches) unmarshal(dAtA []byte, depth int) error {
	if depth > maxUnmarshalDepth {
		return fmt.Errorf("exceeded max recursion depth")
	}
	l := len(dAtA)
	iNdEx := 0
	if l >= 256 {
		var preIdx int
		var field1count int
		for preIdx < l {
			var preWire uint64
			for shift := uint(0); ; shift += 7 {
				if preIdx >= l {
					break
				}
				b := dAtA[preIdx]
				preIdx++
				preWire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			preNum := int32(preWire >> 3)
			preTyp := int(preWire & 0x7)
			switch preNum {
			case 1:
				field1count++
			}
			switch preTyp {
			case 0:
				for preIdx < l {
					preIdx++
					if dAtA[preIdx-1] < 0x80 {
						break
					}
				}
			case 1:
				preIdx += 8
			case 2:
				var preLen uint64
				for shift := uint(0); ; shift += 7 {
					if preIdx >= l {
						break
					}
					b := dAtA[preIdx]
					preIdx++
					preLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				preIdx += int(preLen)
			case 5:
				preIdx += 4
			default:
				preIdx = -1
			}
			if preIdx < 0 || preIdx > l {
				break
			}
		}
		preCapMax := l / 2
		if c := field1count; c > 0 {
			if c > preCapMax {
				c = preCapMax
			}
			m.Batches = make([]*RedactionBatch, 0, c)
		}
	}
	for iNdEx < l {
		var wire uint64
		if iNdEx < l && dAtA[iNdEx] < 0x80 {
			wire = uint64(dAtA[iNdEx])
			iNdEx++
		} else {
			for shift := uint(0); ; shift += 7 {
				if shift >= 35 {
					return fmt.Errorf("proto: integer overflow")
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		}
		if wire>>3 < 1 || wire>>3 > 0x1FFFFFFF {
			return fmt.Errorf("invalid field number")
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		switch fieldNum {
		case 1: // batches
			if wireType != 2 {
				n, err := skipValue(dAtA[iNdEx:], wireType, fieldNum)
				if err != nil {
					return err
				}
				iNdEx += n
				continue
			}
			var byteLen uint64
			if iNdEx < l && dAtA[iNdEx] < 0x80 {
				byteLen = uint64(dAtA[iNdEx])
				iNdEx++
			} else {
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return fmt.Errorf("proto: integer overflow")
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					byteLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						if shift == 63 && b > 1 {
							return fmt.Errorf("proto: varint overflow")
						}
						break
					}
				}
			}
			if byteLen > uint64(math.MaxInt) {
				return io.ErrUnexpectedEOF
			}
			intByteLen := int(byteLen)
			postIndex := iNdEx + intByteLen
			if postIndex < 0 {
				return fmt.Errorf("proto: negative length")
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Batches = append(m.Batches, &RedactionBatch{})
			if err := m.Batches[len(m.Batches)-1].unmarshal(dAtA[iNdEx:postIndex], depth+1); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			n, err := skipValue(dAtA[iNdEx:], wireType, fieldNum)
			if err != nil {
				return err
			}
			iNdEx += n
		}
	}
	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
