// Code generated by wiresmith. DO NOT EDIT.
// source: tempopb/tempo.proto

package tempopb

import (
	"fmt"
	"github.com/grafana/tempo/pkg/tempopb/common/v1"
	tracev1 "github.com/grafana/tempo/pkg/tempopb/trace/v1"
	"github.com/grafana/wiresmith/protohelpers"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/runtime/protoimpl"
	"google.golang.org/protobuf/types/known/timestamppb"
	"reflect"
	"slices"
	"sort"
	"strconv"
	"strings"
	"unsafe"
)

// Cold companion utilities for tempopb/tempo.proto.
//
// This file holds two cold concerns merged into one compilation unit:
//
//   - Reflection / registration glue: the per-message ProtoReflect()
//     methods, the per-enum Descriptor()/Type()/Number() methods, the
//     embedded FileDescriptorProto blob, the file_*_msgTypes /
//     file_*_enumTypes arrays, and the init() that registers everything
//     with protoregistry.GlobalFiles and protoregistry.GlobalTypes.
//   - The per-message String() debug dumps (hand-rolled, deterministic,
//     non-reflection — see compiler/generator/emit_string.go).
//
// None of these are called on the marshal / unmarshal / size hot path.
//
// Why a separate file? Putting this code (plus its descriptorpb /
// protoreflect / protoimpl imports — ~64KB of descriptorpb alone, ~377KB
// added to __TEXT overall) next to the hot Marshal/Unmarshal functions
// caused a measured +7–14% regression on otlp benchmarks (UnmarshalProfiles
// regressed by +12.6%) due to icache / iTLB / BTB pressure: the hot
// loops themselves were unchanged, but cold reflection code interleaved
// in the same compilation unit shifted hot functions onto different
// cache sets and pushed them ~131KB further into the binary. Emitting
// the cold half here, in its own .o, lets the linker place it away
// from the hot half and recovers that throughput. reflect and String()
// are both cold and were already split out, so merging them (cold→cold)
// preserves the rationale while halving the companion-file count.
//
// See compiler/generator/emit_registration.go for the full rationale
// and the benchmark methodology. DO NOT inline this file's contents
// back into the main .pb.go without re-measuring.

func (m *TraceByIDRequest) String() string {
	if m == nil {
		return "<nil>"
	}
	var b strings.Builder
	if len(m.TraceID) > 0 {
		b.WriteString("traceID: ")
		b.WriteString(strconv.Quote(string(m.TraceID)))
		b.WriteString(" ")
	}
	if len(m.BlockStart) > 0 {
		b.WriteString("blockStart: ")
		b.WriteString(strconv.Quote(m.BlockStart))
		b.WriteString(" ")
	}
	if len(m.BlockEnd) > 0 {
		b.WriteString("blockEnd: ")
		b.WriteString(strconv.Quote(m.BlockEnd))
		b.WriteString(" ")
	}
	if len(m.QueryMode) > 0 {
		b.WriteString("queryMode: ")
		b.WriteString(strconv.Quote(m.QueryMode))
		b.WriteString(" ")
	}
	if m.AllowPartialTrace {
		b.WriteString("allowPartialTrace: ")
		fmt.Fprintf(&b, "%v", m.AllowPartialTrace)
		b.WriteString(" ")
	}
	b.WriteString("RF1After: ")
	fmt.Fprintf(&b, "%v", m.RF1After)
	b.WriteString(" ")
	return strings.TrimSpace(b.String())
}

func (m *TraceByIDResponse) String() string {
	if m == nil {
		return "<nil>"
	}
	var b strings.Builder
	if m.Trace != nil {
		b.WriteString("trace: ")
		b.WriteString("{")
		b.WriteString(m.Trace.String())
		b.WriteString("}")
		b.WriteString(" ")
	}
	if m.Metrics != nil {
		b.WriteString("metrics: ")
		b.WriteString("{")
		b.WriteString(m.Metrics.String())
		b.WriteString("}")
		b.WriteString(" ")
	}
	if m.Status != 0 {
		b.WriteString("status: ")
		b.WriteString(m.Status.String())
		b.WriteString(" ")
	}
	if len(m.Message) > 0 {
		b.WriteString("message: ")
		b.WriteString(strconv.Quote(m.Message))
		b.WriteString(" ")
	}
	return strings.TrimSpace(b.String())
}

func (m *TraceByIDMetrics) String() string {
	if m == nil {
		return "<nil>"
	}
	var b strings.Builder
	if m.InspectedBytes != 0 {
		b.WriteString("inspectedBytes: ")
		fmt.Fprintf(&b, "%v", m.InspectedBytes)
		b.WriteString(" ")
	}
	return strings.TrimSpace(b.String())
}

func (m *SearchRequest) String() string {
	if m == nil {
		return "<nil>"
	}
	var b strings.Builder
	{
		entries := make([]string, 0, len(m.Tags))
		for k, v := range m.Tags {
			var eb strings.Builder
			eb.WriteString("key: ")
			eb.WriteString(strconv.Quote(k))
			eb.WriteString(" ")
			eb.WriteString("value: ")
			eb.WriteString(strconv.Quote(v))
			eb.WriteString(" ")
			entries = append(entries, strings.TrimSpace(eb.String()))
		}
		sort.Strings(entries)
		for _, e := range entries {
			b.WriteString("Tags: {")
			b.WriteString(e)
			b.WriteString("}")
			b.WriteString(" ")
		}
	}
	if m.MinDurationMs != 0 {
		b.WriteString("MinDurationMs: ")
		fmt.Fprintf(&b, "%v", m.MinDurationMs)
		b.WriteString(" ")
	}
	if m.MaxDurationMs != 0 {
		b.WriteString("MaxDurationMs: ")
		fmt.Fprintf(&b, "%v", m.MaxDurationMs)
		b.WriteString(" ")
	}
	if m.Limit != 0 {
		b.WriteString("Limit: ")
		fmt.Fprintf(&b, "%v", m.Limit)
		b.WriteString(" ")
	}
	if m.Start != 0 {
		b.WriteString("start: ")
		fmt.Fprintf(&b, "%v", m.Start)
		b.WriteString(" ")
	}
	if m.End != 0 {
		b.WriteString("end: ")
		fmt.Fprintf(&b, "%v", m.End)
		b.WriteString(" ")
	}
	if len(m.Query) > 0 {
		b.WriteString("Query: ")
		b.WriteString(strconv.Quote(m.Query))
		b.WriteString(" ")
	}
	if m.SpansPerSpanSet != 0 {
		b.WriteString("SpansPerSpanSet: ")
		fmt.Fprintf(&b, "%v", m.SpansPerSpanSet)
		b.WriteString(" ")
	}
	b.WriteString("RF1After: ")
	fmt.Fprintf(&b, "%v", m.RF1After)
	b.WriteString(" ")
	for _, e := range m.SkipASTTransformations {
		b.WriteString("skipASTTransformations: ")
		b.WriteString(strconv.Quote(e))
		b.WriteString(" ")
	}
	return strings.TrimSpace(b.String())
}

func (m *SearchBlockRequest) String() string {
	if m == nil {
		return "<nil>"
	}
	var b strings.Builder
	if m.SearchReq != nil {
		b.WriteString("searchReq: ")
		b.WriteString("{")
		b.WriteString(m.SearchReq.String())
		b.WriteString("}")
		b.WriteString(" ")
	}
	if len(m.BlockID) > 0 {
		b.WriteString("blockID: ")
		b.WriteString(strconv.Quote(m.BlockID))
		b.WriteString(" ")
	}
	if m.StartPage != 0 {
		b.WriteString("startPage: ")
		fmt.Fprintf(&b, "%v", m.StartPage)
		b.WriteString(" ")
	}
	if m.PagesToSearch != 0 {
		b.WriteString("pagesToSearch: ")
		fmt.Fprintf(&b, "%v", m.PagesToSearch)
		b.WriteString(" ")
	}
	if m.IndexPageSize != 0 {
		b.WriteString("indexPageSize: ")
		fmt.Fprintf(&b, "%v", m.IndexPageSize)
		b.WriteString(" ")
	}
	if m.TotalRecords != 0 {
		b.WriteString("totalRecords: ")
		fmt.Fprintf(&b, "%v", m.TotalRecords)
		b.WriteString(" ")
	}
	if len(m.Version) > 0 {
		b.WriteString("version: ")
		b.WriteString(strconv.Quote(m.Version))
		b.WriteString(" ")
	}
	if m.Size_ != 0 {
		b.WriteString("size: ")
		fmt.Fprintf(&b, "%v", m.Size_)
		b.WriteString(" ")
	}
	if m.FooterSize != 0 {
		b.WriteString("footerSize: ")
		fmt.Fprintf(&b, "%v", m.FooterSize)
		b.WriteString(" ")
	}
	for _, e := range m.DedicatedColumns {
		b.WriteString("dedicatedColumns: ")
		b.WriteString("{")
		b.WriteString(e.String())
		b.WriteString("}")
		b.WriteString(" ")
	}
	return strings.TrimSpace(b.String())
}

func (m *DedicatedColumn) String() string {
	if m == nil {
		return "<nil>"
	}
	var b strings.Builder
	if m.Type != 0 {
		b.WriteString("type: ")
		b.WriteString(m.Type.String())
		b.WriteString(" ")
	}
	if len(m.Name) > 0 {
		b.WriteString("name: ")
		b.WriteString(strconv.Quote(m.Name))
		b.WriteString(" ")
	}
	if m.Scope != 0 {
		b.WriteString("scope: ")
		b.WriteString(m.Scope.String())
		b.WriteString(" ")
	}
	if m.Options != 0 {
		b.WriteString("options: ")
		b.WriteString(m.Options.String())
		b.WriteString(" ")
	}
	return strings.TrimSpace(b.String())
}

func (m *SearchResponse) String() string {
	if m == nil {
		return "<nil>"
	}
	var b strings.Builder
	for _, e := range m.Traces {
		b.WriteString("traces: ")
		b.WriteString("{")
		b.WriteString(e.String())
		b.WriteString("}")
		b.WriteString(" ")
	}
	if m.Metrics != nil {
		b.WriteString("metrics: ")
		b.WriteString("{")
		b.WriteString(m.Metrics.String())
		b.WriteString("}")
		b.WriteString(" ")
	}
	return strings.TrimSpace(b.String())
}

func (m *TraceSearchMetadata) String() string {
	if m == nil {
		return "<nil>"
	}
	var b strings.Builder
	if len(m.TraceID) > 0 {
		b.WriteString("traceID: ")
		b.WriteString(strconv.Quote(m.TraceID))
		b.WriteString(" ")
	}
	if len(m.RootServiceName) > 0 {
		b.WriteString("rootServiceName: ")
		b.WriteString(strconv.Quote(m.RootServiceName))
		b.WriteString(" ")
	}
	if len(m.RootTraceName) > 0 {
		b.WriteString("rootTraceName: ")
		b.WriteString(strconv.Quote(m.RootTraceName))
		b.WriteString(" ")
	}
	if m.StartTimeUnixNano != 0 {
		b.WriteString("startTimeUnixNano: ")
		fmt.Fprintf(&b, "%v", m.StartTimeUnixNano)
		b.WriteString(" ")
	}
	if m.DurationMs != 0 {
		b.WriteString("durationMs: ")
		fmt.Fprintf(&b, "%v", m.DurationMs)
		b.WriteString(" ")
	}
	if m.SpanSet != nil {
		b.WriteString("spanSet: ")
		b.WriteString("{")
		b.WriteString(m.SpanSet.String())
		b.WriteString("}")
		b.WriteString(" ")
	}
	for _, e := range m.SpanSets {
		b.WriteString("spanSets: ")
		b.WriteString("{")
		b.WriteString(e.String())
		b.WriteString("}")
		b.WriteString(" ")
	}
	{
		entries := make([]string, 0, len(m.ServiceStats))
		for k, v := range m.ServiceStats {
			var eb strings.Builder
			eb.WriteString("key: ")
			eb.WriteString(strconv.Quote(k))
			eb.WriteString(" ")
			eb.WriteString("value: {")
			eb.WriteString(v.String())
			eb.WriteString("}")
			entries = append(entries, strings.TrimSpace(eb.String()))
		}
		sort.Strings(entries)
		for _, e := range entries {
			b.WriteString("serviceStats: {")
			b.WriteString(e)
			b.WriteString("}")
			b.WriteString(" ")
		}
	}
	return strings.TrimSpace(b.String())
}

func (m *ServiceStats) String() string {
	if m == nil {
		return "<nil>"
	}
	var b strings.Builder
	if m.SpanCount != 0 {
		b.WriteString("spanCount: ")
		fmt.Fprintf(&b, "%v", m.SpanCount)
		b.WriteString(" ")
	}
	if m.ErrorCount != 0 {
		b.WriteString("errorCount: ")
		fmt.Fprintf(&b, "%v", m.ErrorCount)
		b.WriteString(" ")
	}
	return strings.TrimSpace(b.String())
}

func (m *SpanSet) String() string {
	if m == nil {
		return "<nil>"
	}
	var b strings.Builder
	for _, e := range m.Spans {
		b.WriteString("spans: ")
		b.WriteString("{")
		b.WriteString(e.String())
		b.WriteString("}")
		b.WriteString(" ")
	}
	if m.Matched != 0 {
		b.WriteString("matched: ")
		fmt.Fprintf(&b, "%v", m.Matched)
		b.WriteString(" ")
	}
	for _, e := range m.Attributes {
		b.WriteString("attributes: ")
		b.WriteString("{")
		b.WriteString(e.String())
		b.WriteString("}")
		b.WriteString(" ")
	}
	return strings.TrimSpace(b.String())
}

func (m *Span) String() string {
	if m == nil {
		return "<nil>"
	}
	var b strings.Builder
	if len(m.SpanID) > 0 {
		b.WriteString("spanID: ")
		b.WriteString(strconv.Quote(m.SpanID))
		b.WriteString(" ")
	}
	if len(m.Name) > 0 {
		b.WriteString("name: ")
		b.WriteString(strconv.Quote(m.Name))
		b.WriteString(" ")
	}
	if m.StartTimeUnixNano != 0 {
		b.WriteString("startTimeUnixNano: ")
		fmt.Fprintf(&b, "%v", m.StartTimeUnixNano)
		b.WriteString(" ")
	}
	if m.DurationNanos != 0 {
		b.WriteString("durationNanos: ")
		fmt.Fprintf(&b, "%v", m.DurationNanos)
		b.WriteString(" ")
	}
	for _, e := range m.Attributes {
		b.WriteString("attributes: ")
		b.WriteString("{")
		b.WriteString(e.String())
		b.WriteString("}")
		b.WriteString(" ")
	}
	return strings.TrimSpace(b.String())
}

func (m *SearchMetrics) String() string {
	if m == nil {
		return "<nil>"
	}
	var b strings.Builder
	if m.InspectedTraces != 0 {
		b.WriteString("inspectedTraces: ")
		fmt.Fprintf(&b, "%v", m.InspectedTraces)
		b.WriteString(" ")
	}
	if m.InspectedBytes != 0 {
		b.WriteString("inspectedBytes: ")
		fmt.Fprintf(&b, "%v", m.InspectedBytes)
		b.WriteString(" ")
	}
	if m.TotalBlocks != 0 {
		b.WriteString("totalBlocks: ")
		fmt.Fprintf(&b, "%v", m.TotalBlocks)
		b.WriteString(" ")
	}
	if m.CompletedJobs != 0 {
		b.WriteString("completedJobs: ")
		fmt.Fprintf(&b, "%v", m.CompletedJobs)
		b.WriteString(" ")
	}
	if m.TotalJobs != 0 {
		b.WriteString("totalJobs: ")
		fmt.Fprintf(&b, "%v", m.TotalJobs)
		b.WriteString(" ")
	}
	if m.TotalBlockBytes != 0 {
		b.WriteString("totalBlockBytes: ")
		fmt.Fprintf(&b, "%v", m.TotalBlockBytes)
		b.WriteString(" ")
	}
	if m.InspectedSpans != 0 {
		b.WriteString("inspectedSpans: ")
		fmt.Fprintf(&b, "%v", m.InspectedSpans)
		b.WriteString(" ")
	}
	return strings.TrimSpace(b.String())
}

func (m *SearchTagsRequest) String() string {
	if m == nil {
		return "<nil>"
	}
	var b strings.Builder
	if len(m.Scope) > 0 {
		b.WriteString("scope: ")
		b.WriteString(strconv.Quote(m.Scope))
		b.WriteString(" ")
	}
	if len(m.Query) > 0 {
		b.WriteString("query: ")
		b.WriteString(strconv.Quote(m.Query))
		b.WriteString(" ")
	}
	if m.Start != 0 {
		b.WriteString("start: ")
		fmt.Fprintf(&b, "%v", m.Start)
		b.WriteString(" ")
	}
	if m.End != 0 {
		b.WriteString("end: ")
		fmt.Fprintf(&b, "%v", m.End)
		b.WriteString(" ")
	}
	if m.MaxTagsPerScope != 0 {
		b.WriteString("maxTagsPerScope: ")
		fmt.Fprintf(&b, "%v", m.MaxTagsPerScope)
		b.WriteString(" ")
	}
	if m.StaleValuesThreshold != 0 {
		b.WriteString("staleValuesThreshold: ")
		fmt.Fprintf(&b, "%v", m.StaleValuesThreshold)
		b.WriteString(" ")
	}
	b.WriteString("RF1After: ")
	fmt.Fprintf(&b, "%v", m.RF1After)
	b.WriteString(" ")
	return strings.TrimSpace(b.String())
}

func (m *SearchTagsBlockRequest) String() string {
	if m == nil {
		return "<nil>"
	}
	var b strings.Builder
	if m.SearchReq != nil {
		b.WriteString("searchReq: ")
		b.WriteString("{")
		b.WriteString(m.SearchReq.String())
		b.WriteString("}")
		b.WriteString(" ")
	}
	if len(m.BlockID) > 0 {
		b.WriteString("blockID: ")
		b.WriteString(strconv.Quote(m.BlockID))
		b.WriteString(" ")
	}
	if m.StartPage != 0 {
		b.WriteString("startPage: ")
		fmt.Fprintf(&b, "%v", m.StartPage)
		b.WriteString(" ")
	}
	if m.PagesToSearch != 0 {
		b.WriteString("pagesToSearch: ")
		fmt.Fprintf(&b, "%v", m.PagesToSearch)
		b.WriteString(" ")
	}
	if m.IndexPageSize != 0 {
		b.WriteString("indexPageSize: ")
		fmt.Fprintf(&b, "%v", m.IndexPageSize)
		b.WriteString(" ")
	}
	if m.TotalRecords != 0 {
		b.WriteString("totalRecords: ")
		fmt.Fprintf(&b, "%v", m.TotalRecords)
		b.WriteString(" ")
	}
	if len(m.Version) > 0 {
		b.WriteString("version: ")
		b.WriteString(strconv.Quote(m.Version))
		b.WriteString(" ")
	}
	if m.Size_ != 0 {
		b.WriteString("size: ")
		fmt.Fprintf(&b, "%v", m.Size_)
		b.WriteString(" ")
	}
	if m.FooterSize != 0 {
		b.WriteString("footerSize: ")
		fmt.Fprintf(&b, "%v", m.FooterSize)
		b.WriteString(" ")
	}
	for _, e := range m.DedicatedColumns {
		b.WriteString("dedicatedColumns: ")
		b.WriteString("{")
		b.WriteString(e.String())
		b.WriteString("}")
		b.WriteString(" ")
	}
	if m.MaxTagsPerScope != 0 {
		b.WriteString("maxTagsPerScope: ")
		fmt.Fprintf(&b, "%v", m.MaxTagsPerScope)
		b.WriteString(" ")
	}
	if m.StaleValueThreshold != 0 {
		b.WriteString("staleValueThreshold: ")
		fmt.Fprintf(&b, "%v", m.StaleValueThreshold)
		b.WriteString(" ")
	}
	return strings.TrimSpace(b.String())
}

func (m *SearchTagValuesBlockRequest) String() string {
	if m == nil {
		return "<nil>"
	}
	var b strings.Builder
	if m.SearchReq != nil {
		b.WriteString("searchReq: ")
		b.WriteString("{")
		b.WriteString(m.SearchReq.String())
		b.WriteString("}")
		b.WriteString(" ")
	}
	if len(m.BlockID) > 0 {
		b.WriteString("blockID: ")
		b.WriteString(strconv.Quote(m.BlockID))
		b.WriteString(" ")
	}
	if m.StartPage != 0 {
		b.WriteString("startPage: ")
		fmt.Fprintf(&b, "%v", m.StartPage)
		b.WriteString(" ")
	}
	if m.PagesToSearch != 0 {
		b.WriteString("pagesToSearch: ")
		fmt.Fprintf(&b, "%v", m.PagesToSearch)
		b.WriteString(" ")
	}
	if m.IndexPageSize != 0 {
		b.WriteString("indexPageSize: ")
		fmt.Fprintf(&b, "%v", m.IndexPageSize)
		b.WriteString(" ")
	}
	if m.TotalRecords != 0 {
		b.WriteString("totalRecords: ")
		fmt.Fprintf(&b, "%v", m.TotalRecords)
		b.WriteString(" ")
	}
	if len(m.Version) > 0 {
		b.WriteString("version: ")
		b.WriteString(strconv.Quote(m.Version))
		b.WriteString(" ")
	}
	if m.Size_ != 0 {
		b.WriteString("size: ")
		fmt.Fprintf(&b, "%v", m.Size_)
		b.WriteString(" ")
	}
	if m.FooterSize != 0 {
		b.WriteString("footerSize: ")
		fmt.Fprintf(&b, "%v", m.FooterSize)
		b.WriteString(" ")
	}
	for _, e := range m.DedicatedColumns {
		b.WriteString("dedicatedColumns: ")
		b.WriteString("{")
		b.WriteString(e.String())
		b.WriteString("}")
		b.WriteString(" ")
	}
	return strings.TrimSpace(b.String())
}

func (m *SearchTagsResponse) String() string {
	if m == nil {
		return "<nil>"
	}
	var b strings.Builder
	for _, e := range m.TagNames {
		b.WriteString("tagNames: ")
		b.WriteString(strconv.Quote(e))
		b.WriteString(" ")
	}
	if m.Metrics != nil {
		b.WriteString("metrics: ")
		b.WriteString("{")
		b.WriteString(m.Metrics.String())
		b.WriteString("}")
		b.WriteString(" ")
	}
	return strings.TrimSpace(b.String())
}

func (m *SearchTagsV2Response) String() string {
	if m == nil {
		return "<nil>"
	}
	var b strings.Builder
	for _, e := range m.Scopes {
		b.WriteString("scopes: ")
		b.WriteString("{")
		b.WriteString(e.String())
		b.WriteString("}")
		b.WriteString(" ")
	}
	if m.Metrics != nil {
		b.WriteString("metrics: ")
		b.WriteString("{")
		b.WriteString(m.Metrics.String())
		b.WriteString("}")
		b.WriteString(" ")
	}
	return strings.TrimSpace(b.String())
}

func (m *SearchTagsV2Scope) String() string {
	if m == nil {
		return "<nil>"
	}
	var b strings.Builder
	if len(m.Name) > 0 {
		b.WriteString("name: ")
		b.WriteString(strconv.Quote(m.Name))
		b.WriteString(" ")
	}
	for _, e := range m.Tags {
		b.WriteString("tags: ")
		b.WriteString(strconv.Quote(e))
		b.WriteString(" ")
	}
	return strings.TrimSpace(b.String())
}

func (m *SearchTagValuesRequest) String() string {
	if m == nil {
		return "<nil>"
	}
	var b strings.Builder
	if len(m.TagName) > 0 {
		b.WriteString("tagName: ")
		b.WriteString(strconv.Quote(m.TagName))
		b.WriteString(" ")
	}
	if len(m.Query) > 0 {
		b.WriteString("query: ")
		b.WriteString(strconv.Quote(m.Query))
		b.WriteString(" ")
	}
	if m.Start != 0 {
		b.WriteString("start: ")
		fmt.Fprintf(&b, "%v", m.Start)
		b.WriteString(" ")
	}
	if m.End != 0 {
		b.WriteString("end: ")
		fmt.Fprintf(&b, "%v", m.End)
		b.WriteString(" ")
	}
	if m.MaxTagValues != 0 {
		b.WriteString("maxTagValues: ")
		fmt.Fprintf(&b, "%v", m.MaxTagValues)
		b.WriteString(" ")
	}
	if m.StaleValueThreshold != 0 {
		b.WriteString("staleValueThreshold: ")
		fmt.Fprintf(&b, "%v", m.StaleValueThreshold)
		b.WriteString(" ")
	}
	b.WriteString("RF1After: ")
	fmt.Fprintf(&b, "%v", m.RF1After)
	b.WriteString(" ")
	return strings.TrimSpace(b.String())
}

func (m *SearchTagValuesResponse) String() string {
	if m == nil {
		return "<nil>"
	}
	var b strings.Builder
	for _, e := range m.TagValues {
		b.WriteString("tagValues: ")
		b.WriteString(strconv.Quote(e))
		b.WriteString(" ")
	}
	if m.Metrics != nil {
		b.WriteString("metrics: ")
		b.WriteString("{")
		b.WriteString(m.Metrics.String())
		b.WriteString("}")
		b.WriteString(" ")
	}
	return strings.TrimSpace(b.String())
}

func (m *TagValue) String() string {
	if m == nil {
		return "<nil>"
	}
	var b strings.Builder
	if len(m.Type) > 0 {
		b.WriteString("type: ")
		b.WriteString(strconv.Quote(m.Type))
		b.WriteString(" ")
	}
	if len(m.Value) > 0 {
		b.WriteString("value: ")
		b.WriteString(strconv.Quote(m.Value))
		b.WriteString(" ")
	}
	return strings.TrimSpace(b.String())
}

func (m *SearchTagValuesV2Response) String() string {
	if m == nil {
		return "<nil>"
	}
	var b strings.Builder
	for _, e := range m.TagValues {
		b.WriteString("tagValues: ")
		b.WriteString("{")
		b.WriteString(e.String())
		b.WriteString("}")
		b.WriteString(" ")
	}
	if m.Metrics != nil {
		b.WriteString("metrics: ")
		b.WriteString("{")
		b.WriteString(m.Metrics.String())
		b.WriteString("}")
		b.WriteString(" ")
	}
	return strings.TrimSpace(b.String())
}

func (m *MetadataMetrics) String() string {
	if m == nil {
		return "<nil>"
	}
	var b strings.Builder
	if m.InspectedBytes != 0 {
		b.WriteString("inspectedBytes: ")
		fmt.Fprintf(&b, "%v", m.InspectedBytes)
		b.WriteString(" ")
	}
	if m.TotalJobs != 0 {
		b.WriteString("totalJobs: ")
		fmt.Fprintf(&b, "%v", m.TotalJobs)
		b.WriteString(" ")
	}
	if m.CompletedJobs != 0 {
		b.WriteString("completedJobs: ")
		fmt.Fprintf(&b, "%v", m.CompletedJobs)
		b.WriteString(" ")
	}
	if m.TotalBlocks != 0 {
		b.WriteString("totalBlocks: ")
		fmt.Fprintf(&b, "%v", m.TotalBlocks)
		b.WriteString(" ")
	}
	if m.TotalBlockBytes != 0 {
		b.WriteString("totalBlockBytes: ")
		fmt.Fprintf(&b, "%v", m.TotalBlockBytes)
		b.WriteString(" ")
	}
	return strings.TrimSpace(b.String())
}

func (m *Trace) String() string {
	if m == nil {
		return "<nil>"
	}
	var b strings.Builder
	for _, e := range m.ResourceSpans {
		b.WriteString("resourceSpans: ")
		b.WriteString("{")
		b.WriteString(e.String())
		b.WriteString("}")
		b.WriteString(" ")
	}
	return strings.TrimSpace(b.String())
}

func (m *PushResponse) String() string {
	if m == nil {
		return "<nil>"
	}
	var b strings.Builder
	for _, e := range m.ErrorsByTrace {
		b.WriteString("errorsByTrace: ")
		b.WriteString(e.String())
		b.WriteString(" ")
	}
	return strings.TrimSpace(b.String())
}

func (m *PushBytesRequest) String() string {
	if m == nil {
		return "<nil>"
	}
	var b strings.Builder
	for _, e := range m.Traces {
		b.WriteString("traces: ")
		fmt.Fprintf(&b, "%v", e)
		b.WriteString(" ")
	}
	for _, e := range m.Ids {
		b.WriteString("ids: ")
		b.WriteString(strconv.Quote(string(e)))
		b.WriteString(" ")
	}
	if m.SkipMetricsGeneration {
		b.WriteString("skipMetricsGeneration: ")
		fmt.Fprintf(&b, "%v", m.SkipMetricsGeneration)
		b.WriteString(" ")
	}
	return strings.TrimSpace(b.String())
}

func (m *PushSpansRequest) String() string {
	if m == nil {
		return "<nil>"
	}
	var b strings.Builder
	for _, e := range m.Batches {
		b.WriteString("batches: ")
		b.WriteString("{")
		b.WriteString(e.String())
		b.WriteString("}")
		b.WriteString(" ")
	}
	if m.SkipMetricsGeneration {
		b.WriteString("skipMetricsGeneration: ")
		fmt.Fprintf(&b, "%v", m.SkipMetricsGeneration)
		b.WriteString(" ")
	}
	return strings.TrimSpace(b.String())
}

func (m *TraceBytes) String() string {
	if m == nil {
		return "<nil>"
	}
	var b strings.Builder
	for _, e := range m.Traces {
		b.WriteString("traces: ")
		b.WriteString(strconv.Quote(string(e)))
		b.WriteString(" ")
	}
	return strings.TrimSpace(b.String())
}

func (m *LinkSlice) String() string {
	if m == nil {
		return "<nil>"
	}
	var b strings.Builder
	for _, e := range m.Links {
		b.WriteString("links: ")
		b.WriteString("{")
		b.WriteString(e.String())
		b.WriteString("}")
		b.WriteString(" ")
	}
	return strings.TrimSpace(b.String())
}

func (m *QueryInstantRequest) String() string {
	if m == nil {
		return "<nil>"
	}
	var b strings.Builder
	if len(m.Query) > 0 {
		b.WriteString("query: ")
		b.WriteString(strconv.Quote(m.Query))
		b.WriteString(" ")
	}
	if m.Start != 0 {
		b.WriteString("start: ")
		fmt.Fprintf(&b, "%v", m.Start)
		b.WriteString(" ")
	}
	if m.End != 0 {
		b.WriteString("end: ")
		fmt.Fprintf(&b, "%v", m.End)
		b.WriteString(" ")
	}
	return strings.TrimSpace(b.String())
}

func (m *QueryInstantResponse) String() string {
	if m == nil {
		return "<nil>"
	}
	var b strings.Builder
	for _, e := range m.Series {
		b.WriteString("series: ")
		b.WriteString("{")
		b.WriteString(e.String())
		b.WriteString("}")
		b.WriteString(" ")
	}
	if m.Metrics != nil {
		b.WriteString("metrics: ")
		b.WriteString("{")
		b.WriteString(m.Metrics.String())
		b.WriteString("}")
		b.WriteString(" ")
	}
	if m.Status != 0 {
		b.WriteString("status: ")
		b.WriteString(m.Status.String())
		b.WriteString(" ")
	}
	if len(m.Message) > 0 {
		b.WriteString("message: ")
		b.WriteString(strconv.Quote(m.Message))
		b.WriteString(" ")
	}
	return strings.TrimSpace(b.String())
}

func (m *InstantSeries) String() string {
	if m == nil {
		return "<nil>"
	}
	var b strings.Builder
	for _, e := range m.Labels {
		b.WriteString("labels: ")
		b.WriteString("{")
		b.WriteString(e.String())
		b.WriteString("}")
		b.WriteString(" ")
	}
	if m.Value != 0 {
		b.WriteString("value: ")
		fmt.Fprintf(&b, "%v", m.Value)
		b.WriteString(" ")
	}
	return strings.TrimSpace(b.String())
}

func (m *QueryRangeRequest) String() string {
	if m == nil {
		return "<nil>"
	}
	var b strings.Builder
	if len(m.Query) > 0 {
		b.WriteString("query: ")
		b.WriteString(strconv.Quote(m.Query))
		b.WriteString(" ")
	}
	if m.Start != 0 {
		b.WriteString("start: ")
		fmt.Fprintf(&b, "%v", m.Start)
		b.WriteString(" ")
	}
	if m.End != 0 {
		b.WriteString("end: ")
		fmt.Fprintf(&b, "%v", m.End)
		b.WriteString(" ")
	}
	if m.Step != 0 {
		b.WriteString("step: ")
		fmt.Fprintf(&b, "%v", m.Step)
		b.WriteString(" ")
	}
	if len(m.QueryMode) > 0 {
		b.WriteString("queryMode: ")
		b.WriteString(strconv.Quote(m.QueryMode))
		b.WriteString(" ")
	}
	if len(m.BlockID) > 0 {
		b.WriteString("blockID: ")
		b.WriteString(strconv.Quote(m.BlockID))
		b.WriteString(" ")
	}
	if m.StartPage != 0 {
		b.WriteString("startPage: ")
		fmt.Fprintf(&b, "%v", m.StartPage)
		b.WriteString(" ")
	}
	if m.PagesToSearch != 0 {
		b.WriteString("pagesToSearch: ")
		fmt.Fprintf(&b, "%v", m.PagesToSearch)
		b.WriteString(" ")
	}
	if len(m.Version) > 0 {
		b.WriteString("version: ")
		b.WriteString(strconv.Quote(m.Version))
		b.WriteString(" ")
	}
	if m.Size_ != 0 {
		b.WriteString("size: ")
		fmt.Fprintf(&b, "%v", m.Size_)
		b.WriteString(" ")
	}
	if m.FooterSize != 0 {
		b.WriteString("footerSize: ")
		fmt.Fprintf(&b, "%v", m.FooterSize)
		b.WriteString(" ")
	}
	for _, e := range m.DedicatedColumns {
		b.WriteString("dedicatedColumns: ")
		b.WriteString("{")
		b.WriteString(e.String())
		b.WriteString("}")
		b.WriteString(" ")
	}
	if m.Exemplars != 0 {
		b.WriteString("exemplars: ")
		fmt.Fprintf(&b, "%v", m.Exemplars)
		b.WriteString(" ")
	}
	if m.MaxSeries != 0 {
		b.WriteString("maxSeries: ")
		fmt.Fprintf(&b, "%v", m.MaxSeries)
		b.WriteString(" ")
	}
	if m.Instant != nil {
		b.WriteString("instant: ")
		fmt.Fprintf(&b, "%v", (*m.Instant))
		b.WriteString(" ")
	}
	for _, e := range m.SkipASTTransformations {
		b.WriteString("skipASTTransformations: ")
		b.WriteString(strconv.Quote(e))
		b.WriteString(" ")
	}
	return strings.TrimSpace(b.String())
}

func (m *QueryRangeResponse) String() string {
	if m == nil {
		return "<nil>"
	}
	var b strings.Builder
	for _, e := range m.Series {
		b.WriteString("series: ")
		b.WriteString("{")
		b.WriteString(e.String())
		b.WriteString("}")
		b.WriteString(" ")
	}
	if m.Metrics != nil {
		b.WriteString("metrics: ")
		b.WriteString("{")
		b.WriteString(m.Metrics.String())
		b.WriteString("}")
		b.WriteString(" ")
	}
	if m.Status != 0 {
		b.WriteString("status: ")
		b.WriteString(m.Status.String())
		b.WriteString(" ")
	}
	if len(m.Message) > 0 {
		b.WriteString("message: ")
		b.WriteString(strconv.Quote(m.Message))
		b.WriteString(" ")
	}
	return strings.TrimSpace(b.String())
}

func (m *Exemplar) String() string {
	if m == nil {
		return "<nil>"
	}
	var b strings.Builder
	for _, e := range m.Labels {
		b.WriteString("labels: ")
		b.WriteString("{")
		b.WriteString(e.String())
		b.WriteString("}")
		b.WriteString(" ")
	}
	if m.Value != 0 {
		b.WriteString("value: ")
		fmt.Fprintf(&b, "%v", m.Value)
		b.WriteString(" ")
	}
	if m.TimestampMs != 0 {
		b.WriteString("timestamp_ms: ")
		fmt.Fprintf(&b, "%v", m.TimestampMs)
		b.WriteString(" ")
	}
	return strings.TrimSpace(b.String())
}

func (m *Sample) String() string {
	if m == nil {
		return "<nil>"
	}
	var b strings.Builder
	if m.Value != 0 {
		b.WriteString("value: ")
		fmt.Fprintf(&b, "%v", m.Value)
		b.WriteString(" ")
	}
	if m.TimestampMs != 0 {
		b.WriteString("timestamp_ms: ")
		fmt.Fprintf(&b, "%v", m.TimestampMs)
		b.WriteString(" ")
	}
	return strings.TrimSpace(b.String())
}

func (m *TimeSeries) String() string {
	if m == nil {
		return "<nil>"
	}
	var b strings.Builder
	for _, e := range m.Labels {
		b.WriteString("labels: ")
		b.WriteString("{")
		b.WriteString(e.String())
		b.WriteString("}")
		b.WriteString(" ")
	}
	for _, e := range m.Samples {
		b.WriteString("samples: ")
		b.WriteString("{")
		b.WriteString(e.String())
		b.WriteString("}")
		b.WriteString(" ")
	}
	for _, e := range m.Exemplars {
		b.WriteString("exemplars: ")
		b.WriteString("{")
		b.WriteString(e.String())
		b.WriteString("}")
		b.WriteString(" ")
	}
	return strings.TrimSpace(b.String())
}

func (m *TraceByIDRequest) Clone() *TraceByIDRequest {
	if m == nil {
		return nil
	}
	out := &TraceByIDRequest{}
	out.TraceID = slices.Clone(m.TraceID)
	out.BlockStart = m.BlockStart
	out.BlockEnd = m.BlockEnd
	out.QueryMode = m.QueryMode
	out.AllowPartialTrace = m.AllowPartialTrace
	out.RF1After = m.RF1After
	return out
}

func (m *TraceByIDResponse) Clone() *TraceByIDResponse {
	if m == nil {
		return nil
	}
	out := &TraceByIDResponse{}
	out.Trace = m.Trace.Clone()
	out.Metrics = m.Metrics.Clone()
	out.Status = m.Status
	out.Message = m.Message
	return out
}

func (m *TraceByIDMetrics) Clone() *TraceByIDMetrics {
	if m == nil {
		return nil
	}
	out := &TraceByIDMetrics{}
	out.InspectedBytes = m.InspectedBytes
	return out
}

func (m *SearchRequest) Clone() *SearchRequest {
	if m == nil {
		return nil
	}
	out := &SearchRequest{}
	if m.Tags != nil {
		out.Tags = make(map[string]string, len(m.Tags))
		for k, v := range m.Tags {
			out.Tags[k] = v
		}
	}
	out.MinDurationMs = m.MinDurationMs
	out.MaxDurationMs = m.MaxDurationMs
	out.Limit = m.Limit
	out.Start = m.Start
	out.End = m.End
	out.Query = m.Query
	out.SpansPerSpanSet = m.SpansPerSpanSet
	out.RF1After = m.RF1After
	out.SkipASTTransformations = slices.Clone(m.SkipASTTransformations)
	return out
}

func (m *SearchBlockRequest) Clone() *SearchBlockRequest {
	if m == nil {
		return nil
	}
	out := &SearchBlockRequest{}
	out.SearchReq = m.SearchReq.Clone()
	out.BlockID = m.BlockID
	out.StartPage = m.StartPage
	out.PagesToSearch = m.PagesToSearch
	out.IndexPageSize = m.IndexPageSize
	out.TotalRecords = m.TotalRecords
	out.Version = m.Version
	out.Size_ = m.Size_
	out.FooterSize = m.FooterSize
	out.DedicatedColumns = slices.Clone(m.DedicatedColumns)
	for i := range out.DedicatedColumns {
		out.DedicatedColumns[i] = out.DedicatedColumns[i].Clone()
	}
	return out
}

func (m *DedicatedColumn) Clone() *DedicatedColumn {
	if m == nil {
		return nil
	}
	out := &DedicatedColumn{}
	out.Scope = m.Scope
	out.Name = m.Name
	out.Type = m.Type
	out.Options = m.Options
	return out
}

func (m *SearchResponse) Clone() *SearchResponse {
	if m == nil {
		return nil
	}
	out := &SearchResponse{}
	out.Traces = slices.Clone(m.Traces)
	for i := range out.Traces {
		out.Traces[i] = out.Traces[i].Clone()
	}
	out.Metrics = m.Metrics.Clone()
	return out
}

func (m *TraceSearchMetadata) Clone() *TraceSearchMetadata {
	if m == nil {
		return nil
	}
	out := &TraceSearchMetadata{}
	out.TraceID = m.TraceID
	out.RootServiceName = m.RootServiceName
	out.RootTraceName = m.RootTraceName
	out.StartTimeUnixNano = m.StartTimeUnixNano
	out.DurationMs = m.DurationMs
	out.SpanSet = m.SpanSet.Clone()
	out.SpanSets = slices.Clone(m.SpanSets)
	for i := range out.SpanSets {
		out.SpanSets[i] = out.SpanSets[i].Clone()
	}
	if m.ServiceStats != nil {
		out.ServiceStats = make(map[string]ServiceStats, len(m.ServiceStats))
		for k, v := range m.ServiceStats {
			out.ServiceStats[k] = *v.Clone()
		}
	}
	return out
}

func (m *ServiceStats) Clone() *ServiceStats {
	if m == nil {
		return nil
	}
	out := &ServiceStats{}
	out.SpanCount = m.SpanCount
	out.ErrorCount = m.ErrorCount
	return out
}

func (m *SpanSet) Clone() *SpanSet {
	if m == nil {
		return nil
	}
	out := &SpanSet{}
	out.Spans = slices.Clone(m.Spans)
	for i := range out.Spans {
		out.Spans[i] = out.Spans[i].Clone()
	}
	out.Matched = m.Matched
	out.Attributes = slices.Clone(m.Attributes)
	for i := range out.Attributes {
		out.Attributes[i] = out.Attributes[i].Clone()
	}
	return out
}

func (m *Span) Clone() *Span {
	if m == nil {
		return nil
	}
	out := &Span{}
	out.SpanID = m.SpanID
	out.Name = m.Name
	out.StartTimeUnixNano = m.StartTimeUnixNano
	out.DurationNanos = m.DurationNanos
	out.Attributes = slices.Clone(m.Attributes)
	for i := range out.Attributes {
		out.Attributes[i] = out.Attributes[i].Clone()
	}
	return out
}

func (m *SearchMetrics) Clone() *SearchMetrics {
	if m == nil {
		return nil
	}
	out := &SearchMetrics{}
	out.InspectedTraces = m.InspectedTraces
	out.InspectedBytes = m.InspectedBytes
	out.TotalBlocks = m.TotalBlocks
	out.CompletedJobs = m.CompletedJobs
	out.TotalJobs = m.TotalJobs
	out.TotalBlockBytes = m.TotalBlockBytes
	out.InspectedSpans = m.InspectedSpans
	return out
}

func (m *SearchTagsRequest) Clone() *SearchTagsRequest {
	if m == nil {
		return nil
	}
	out := &SearchTagsRequest{}
	out.Scope = m.Scope
	out.Query = m.Query
	out.Start = m.Start
	out.End = m.End
	out.MaxTagsPerScope = m.MaxTagsPerScope
	out.StaleValuesThreshold = m.StaleValuesThreshold
	out.RF1After = m.RF1After
	return out
}

func (m *SearchTagsBlockRequest) Clone() *SearchTagsBlockRequest {
	if m == nil {
		return nil
	}
	out := &SearchTagsBlockRequest{}
	out.SearchReq = m.SearchReq.Clone()
	out.BlockID = m.BlockID
	out.StartPage = m.StartPage
	out.PagesToSearch = m.PagesToSearch
	out.IndexPageSize = m.IndexPageSize
	out.TotalRecords = m.TotalRecords
	out.Version = m.Version
	out.Size_ = m.Size_
	out.FooterSize = m.FooterSize
	out.DedicatedColumns = slices.Clone(m.DedicatedColumns)
	for i := range out.DedicatedColumns {
		out.DedicatedColumns[i] = out.DedicatedColumns[i].Clone()
	}
	out.MaxTagsPerScope = m.MaxTagsPerScope
	out.StaleValueThreshold = m.StaleValueThreshold
	return out
}

func (m *SearchTagValuesBlockRequest) Clone() *SearchTagValuesBlockRequest {
	if m == nil {
		return nil
	}
	out := &SearchTagValuesBlockRequest{}
	out.SearchReq = m.SearchReq.Clone()
	out.BlockID = m.BlockID
	out.StartPage = m.StartPage
	out.PagesToSearch = m.PagesToSearch
	out.IndexPageSize = m.IndexPageSize
	out.TotalRecords = m.TotalRecords
	out.Version = m.Version
	out.Size_ = m.Size_
	out.FooterSize = m.FooterSize
	out.DedicatedColumns = slices.Clone(m.DedicatedColumns)
	for i := range out.DedicatedColumns {
		out.DedicatedColumns[i] = out.DedicatedColumns[i].Clone()
	}
	return out
}

func (m *SearchTagsResponse) Clone() *SearchTagsResponse {
	if m == nil {
		return nil
	}
	out := &SearchTagsResponse{}
	out.TagNames = slices.Clone(m.TagNames)
	out.Metrics = m.Metrics.Clone()
	return out
}

func (m *SearchTagsV2Response) Clone() *SearchTagsV2Response {
	if m == nil {
		return nil
	}
	out := &SearchTagsV2Response{}
	out.Scopes = slices.Clone(m.Scopes)
	for i := range out.Scopes {
		out.Scopes[i] = out.Scopes[i].Clone()
	}
	out.Metrics = m.Metrics.Clone()
	return out
}

func (m *SearchTagsV2Scope) Clone() *SearchTagsV2Scope {
	if m == nil {
		return nil
	}
	out := &SearchTagsV2Scope{}
	out.Name = m.Name
	out.Tags = slices.Clone(m.Tags)
	return out
}

func (m *SearchTagValuesRequest) Clone() *SearchTagValuesRequest {
	if m == nil {
		return nil
	}
	out := &SearchTagValuesRequest{}
	out.TagName = m.TagName
	out.Query = m.Query
	out.Start = m.Start
	out.End = m.End
	out.MaxTagValues = m.MaxTagValues
	out.StaleValueThreshold = m.StaleValueThreshold
	out.RF1After = m.RF1After
	return out
}

func (m *SearchTagValuesResponse) Clone() *SearchTagValuesResponse {
	if m == nil {
		return nil
	}
	out := &SearchTagValuesResponse{}
	out.TagValues = slices.Clone(m.TagValues)
	out.Metrics = m.Metrics.Clone()
	return out
}

func (m *TagValue) Clone() *TagValue {
	if m == nil {
		return nil
	}
	out := &TagValue{}
	out.Type = m.Type
	out.Value = m.Value
	return out
}

func (m *SearchTagValuesV2Response) Clone() *SearchTagValuesV2Response {
	if m == nil {
		return nil
	}
	out := &SearchTagValuesV2Response{}
	out.TagValues = slices.Clone(m.TagValues)
	for i := range out.TagValues {
		out.TagValues[i] = out.TagValues[i].Clone()
	}
	out.Metrics = m.Metrics.Clone()
	return out
}

func (m *MetadataMetrics) Clone() *MetadataMetrics {
	if m == nil {
		return nil
	}
	out := &MetadataMetrics{}
	out.InspectedBytes = m.InspectedBytes
	out.TotalJobs = m.TotalJobs
	out.CompletedJobs = m.CompletedJobs
	out.TotalBlocks = m.TotalBlocks
	out.TotalBlockBytes = m.TotalBlockBytes
	return out
}

func (m *Trace) Clone() *Trace {
	if m == nil {
		return nil
	}
	out := &Trace{}
	out.ResourceSpans = slices.Clone(m.ResourceSpans)
	for i := range out.ResourceSpans {
		out.ResourceSpans[i] = out.ResourceSpans[i].Clone()
	}
	return out
}

func (m *PushResponse) Clone() *PushResponse {
	if m == nil {
		return nil
	}
	out := &PushResponse{}
	out.ErrorsByTrace = slices.Clone(m.ErrorsByTrace)
	return out
}

func (m *PushBytesRequest) Clone() *PushBytesRequest {
	if m == nil {
		return nil
	}
	out := &PushBytesRequest{}
	out.Traces = slices.Clone(m.Traces)
	out.Ids = slices.Clone(m.Ids)
	for i := range out.Ids {
		out.Ids[i] = slices.Clone(m.Ids[i])
	}
	out.SkipMetricsGeneration = m.SkipMetricsGeneration
	return out
}

func (m *PushSpansRequest) Clone() *PushSpansRequest {
	if m == nil {
		return nil
	}
	out := &PushSpansRequest{}
	out.Batches = slices.Clone(m.Batches)
	for i := range out.Batches {
		out.Batches[i] = out.Batches[i].Clone()
	}
	out.SkipMetricsGeneration = m.SkipMetricsGeneration
	return out
}

func (m *TraceBytes) Clone() *TraceBytes {
	if m == nil {
		return nil
	}
	out := &TraceBytes{}
	out.Traces = slices.Clone(m.Traces)
	for i := range out.Traces {
		out.Traces[i] = slices.Clone(m.Traces[i])
	}
	return out
}

func (m *LinkSlice) Clone() *LinkSlice {
	if m == nil {
		return nil
	}
	out := &LinkSlice{}
	out.Links = slices.Clone(m.Links)
	for i := range out.Links {
		out.Links[i] = out.Links[i].Clone()
	}
	return out
}

func (m *QueryInstantRequest) Clone() *QueryInstantRequest {
	if m == nil {
		return nil
	}
	out := &QueryInstantRequest{}
	out.Query = m.Query
	out.Start = m.Start
	out.End = m.End
	return out
}

func (m *QueryInstantResponse) Clone() *QueryInstantResponse {
	if m == nil {
		return nil
	}
	out := &QueryInstantResponse{}
	out.Series = slices.Clone(m.Series)
	for i := range out.Series {
		out.Series[i] = out.Series[i].Clone()
	}
	out.Metrics = m.Metrics.Clone()
	out.Status = m.Status
	out.Message = m.Message
	return out
}

func (m *InstantSeries) Clone() *InstantSeries {
	if m == nil {
		return nil
	}
	out := &InstantSeries{}
	out.Labels = slices.Clone(m.Labels)
	for i := range out.Labels {
		out.Labels[i] = *m.Labels[i].Clone()
	}
	out.Value = m.Value
	return out
}

func (m *QueryRangeRequest) Clone() *QueryRangeRequest {
	if m == nil {
		return nil
	}
	out := &QueryRangeRequest{}
	out.Query = m.Query
	out.Start = m.Start
	out.End = m.End
	out.Step = m.Step
	out.QueryMode = m.QueryMode
	out.BlockID = m.BlockID
	out.StartPage = m.StartPage
	out.PagesToSearch = m.PagesToSearch
	out.Version = m.Version
	out.Size_ = m.Size_
	out.FooterSize = m.FooterSize
	out.DedicatedColumns = slices.Clone(m.DedicatedColumns)
	for i := range out.DedicatedColumns {
		out.DedicatedColumns[i] = out.DedicatedColumns[i].Clone()
	}
	out.Exemplars = m.Exemplars
	out.MaxSeries = m.MaxSeries
	if m.Instant != nil {
		tmp := *m.Instant
		out.Instant = &tmp
	}
	out.SkipASTTransformations = slices.Clone(m.SkipASTTransformations)
	return out
}

func (m *QueryRangeResponse) Clone() *QueryRangeResponse {
	if m == nil {
		return nil
	}
	out := &QueryRangeResponse{}
	out.Series = slices.Clone(m.Series)
	for i := range out.Series {
		out.Series[i] = out.Series[i].Clone()
	}
	out.Metrics = m.Metrics.Clone()
	out.Status = m.Status
	out.Message = m.Message
	return out
}

func (m *Exemplar) Clone() *Exemplar {
	if m == nil {
		return nil
	}
	out := &Exemplar{}
	out.Labels = slices.Clone(m.Labels)
	for i := range out.Labels {
		out.Labels[i] = *m.Labels[i].Clone()
	}
	out.Value = m.Value
	out.TimestampMs = m.TimestampMs
	return out
}

func (m *Sample) Clone() *Sample {
	if m == nil {
		return nil
	}
	out := &Sample{}
	out.TimestampMs = m.TimestampMs
	out.Value = m.Value
	return out
}

func (m *TimeSeries) Clone() *TimeSeries {
	if m == nil {
		return nil
	}
	out := &TimeSeries{}
	out.Labels = slices.Clone(m.Labels)
	for i := range out.Labels {
		out.Labels[i] = *m.Labels[i].Clone()
	}
	out.Samples = slices.Clone(m.Samples)
	for i := range out.Samples {
		out.Samples[i] = *m.Samples[i].Clone()
	}
	out.Exemplars = slices.Clone(m.Exemplars)
	for i := range out.Exemplars {
		out.Exemplars[i] = *m.Exemplars[i].Clone()
	}
	return out
}

func (x PushErrorReason) Descriptor() protoreflect.EnumDescriptor {
	file_tempopb_tempo_proto_init()
	return file_tempopb_tempo_proto_enumTypes[0].Desc
}

func (x PushErrorReason) Type() protoreflect.EnumType {
	file_tempopb_tempo_proto_init()
	return &file_tempopb_tempo_proto_enumTypes[0]
}

func (x PushErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

func (x PartialStatus) Descriptor() protoreflect.EnumDescriptor {
	file_tempopb_tempo_proto_init()
	return file_tempopb_tempo_proto_enumTypes[1].Desc
}

func (x PartialStatus) Type() protoreflect.EnumType {
	file_tempopb_tempo_proto_init()
	return &file_tempopb_tempo_proto_enumTypes[1]
}

func (x PartialStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

func (x DedicatedColumn_Scope) Descriptor() protoreflect.EnumDescriptor {
	file_tempopb_tempo_proto_init()
	return file_tempopb_tempo_proto_enumTypes[2].Desc
}

func (x DedicatedColumn_Scope) Type() protoreflect.EnumType {
	file_tempopb_tempo_proto_init()
	return &file_tempopb_tempo_proto_enumTypes[2]
}

func (x DedicatedColumn_Scope) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

func (x DedicatedColumn_Type) Descriptor() protoreflect.EnumDescriptor {
	file_tempopb_tempo_proto_init()
	return file_tempopb_tempo_proto_enumTypes[3].Desc
}

func (x DedicatedColumn_Type) Type() protoreflect.EnumType {
	file_tempopb_tempo_proto_init()
	return &file_tempopb_tempo_proto_enumTypes[3]
}

func (x DedicatedColumn_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

func (x DedicatedColumn_Option) Descriptor() protoreflect.EnumDescriptor {
	file_tempopb_tempo_proto_init()
	return file_tempopb_tempo_proto_enumTypes[4].Desc
}

func (x DedicatedColumn_Option) Type() protoreflect.EnumType {
	file_tempopb_tempo_proto_init()
	return &file_tempopb_tempo_proto_enumTypes[4]
}

func (x DedicatedColumn_Option) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

func (x *TraceByIDRequest) ProtoReflect() protoreflect.Message {
	file_tempopb_tempo_proto_init()
	return protohelpers.NewMessageReflect(&file_tempopb_tempo_proto_msgTypes[0], x)
}

func (x *TraceByIDResponse) ProtoReflect() protoreflect.Message {
	file_tempopb_tempo_proto_init()
	return protohelpers.NewMessageReflect(&file_tempopb_tempo_proto_msgTypes[1], x)
}

func (x *TraceByIDMetrics) ProtoReflect() protoreflect.Message {
	file_tempopb_tempo_proto_init()
	return protohelpers.NewMessageReflect(&file_tempopb_tempo_proto_msgTypes[2], x)
}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	file_tempopb_tempo_proto_init()
	return protohelpers.NewMessageReflect(&file_tempopb_tempo_proto_msgTypes[3], x)
}

func (x *SearchBlockRequest) ProtoReflect() protoreflect.Message {
	file_tempopb_tempo_proto_init()
	return protohelpers.NewMessageReflect(&file_tempopb_tempo_proto_msgTypes[4], x)
}

func (x *DedicatedColumn) ProtoReflect() protoreflect.Message {
	file_tempopb_tempo_proto_init()
	return protohelpers.NewMessageReflect(&file_tempopb_tempo_proto_msgTypes[5], x)
}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	file_tempopb_tempo_proto_init()
	return protohelpers.NewMessageReflect(&file_tempopb_tempo_proto_msgTypes[6], x)
}

func (x *TraceSearchMetadata) ProtoReflect() protoreflect.Message {
	file_tempopb_tempo_proto_init()
	return protohelpers.NewMessageReflect(&file_tempopb_tempo_proto_msgTypes[7], x)
}

func (x *ServiceStats) ProtoReflect() protoreflect.Message {
	file_tempopb_tempo_proto_init()
	return protohelpers.NewMessageReflect(&file_tempopb_tempo_proto_msgTypes[8], x)
}

func (x *SpanSet) ProtoReflect() protoreflect.Message {
	file_tempopb_tempo_proto_init()
	return protohelpers.NewMessageReflect(&file_tempopb_tempo_proto_msgTypes[9], x)
}

func (x *Span) ProtoReflect() protoreflect.Message {
	file_tempopb_tempo_proto_init()
	return protohelpers.NewMessageReflect(&file_tempopb_tempo_proto_msgTypes[10], x)
}

func (x *SearchMetrics) ProtoReflect() protoreflect.Message {
	file_tempopb_tempo_proto_init()
	return protohelpers.NewMessageReflect(&file_tempopb_tempo_proto_msgTypes[11], x)
}

func (x *SearchTagsRequest) ProtoReflect() protoreflect.Message {
	file_tempopb_tempo_proto_init()
	return protohelpers.NewMessageReflect(&file_tempopb_tempo_proto_msgTypes[12], x)
}

func (x *SearchTagsBlockRequest) ProtoReflect() protoreflect.Message {
	file_tempopb_tempo_proto_init()
	return protohelpers.NewMessageReflect(&file_tempopb_tempo_proto_msgTypes[13], x)
}

func (x *SearchTagValuesBlockRequest) ProtoReflect() protoreflect.Message {
	file_tempopb_tempo_proto_init()
	return protohelpers.NewMessageReflect(&file_tempopb_tempo_proto_msgTypes[14], x)
}

func (x *SearchTagsResponse) ProtoReflect() protoreflect.Message {
	file_tempopb_tempo_proto_init()
	return protohelpers.NewMessageReflect(&file_tempopb_tempo_proto_msgTypes[15], x)
}

func (x *SearchTagsV2Response) ProtoReflect() protoreflect.Message {
	file_tempopb_tempo_proto_init()
	return protohelpers.NewMessageReflect(&file_tempopb_tempo_proto_msgTypes[16], x)
}

func (x *SearchTagsV2Scope) ProtoReflect() protoreflect.Message {
	file_tempopb_tempo_proto_init()
	return protohelpers.NewMessageReflect(&file_tempopb_tempo_proto_msgTypes[17], x)
}

func (x *SearchTagValuesRequest) ProtoReflect() protoreflect.Message {
	file_tempopb_tempo_proto_init()
	return protohelpers.NewMessageReflect(&file_tempopb_tempo_proto_msgTypes[18], x)
}

func (x *SearchTagValuesResponse) ProtoReflect() protoreflect.Message {
	file_tempopb_tempo_proto_init()
	return protohelpers.NewMessageReflect(&file_tempopb_tempo_proto_msgTypes[19], x)
}

func (x *TagValue) ProtoReflect() protoreflect.Message {
	file_tempopb_tempo_proto_init()
	return protohelpers.NewMessageReflect(&file_tempopb_tempo_proto_msgTypes[20], x)
}

func (x *SearchTagValuesV2Response) ProtoReflect() protoreflect.Message {
	file_tempopb_tempo_proto_init()
	return protohelpers.NewMessageReflect(&file_tempopb_tempo_proto_msgTypes[21], x)
}

func (x *MetadataMetrics) ProtoReflect() protoreflect.Message {
	file_tempopb_tempo_proto_init()
	return protohelpers.NewMessageReflect(&file_tempopb_tempo_proto_msgTypes[22], x)
}

func (x *Trace) ProtoReflect() protoreflect.Message {
	file_tempopb_tempo_proto_init()
	return protohelpers.NewMessageReflect(&file_tempopb_tempo_proto_msgTypes[23], x)
}

func (x *PushResponse) ProtoReflect() protoreflect.Message {
	file_tempopb_tempo_proto_init()
	return protohelpers.NewMessageReflect(&file_tempopb_tempo_proto_msgTypes[24], x)
}

func (x *PushBytesRequest) ProtoReflect() protoreflect.Message {
	file_tempopb_tempo_proto_init()
	return protohelpers.NewMessageReflect(&file_tempopb_tempo_proto_msgTypes[25], x)
}

func (x *PushSpansRequest) ProtoReflect() protoreflect.Message {
	file_tempopb_tempo_proto_init()
	return protohelpers.NewMessageReflect(&file_tempopb_tempo_proto_msgTypes[26], x)
}

func (x *TraceBytes) ProtoReflect() protoreflect.Message {
	file_tempopb_tempo_proto_init()
	return protohelpers.NewMessageReflect(&file_tempopb_tempo_proto_msgTypes[27], x)
}

func (x *LinkSlice) ProtoReflect() protoreflect.Message {
	file_tempopb_tempo_proto_init()
	return protohelpers.NewMessageReflect(&file_tempopb_tempo_proto_msgTypes[28], x)
}

func (x *QueryInstantRequest) ProtoReflect() protoreflect.Message {
	file_tempopb_tempo_proto_init()
	return protohelpers.NewMessageReflect(&file_tempopb_tempo_proto_msgTypes[29], x)
}

func (x *QueryInstantResponse) ProtoReflect() protoreflect.Message {
	file_tempopb_tempo_proto_init()
	return protohelpers.NewMessageReflect(&file_tempopb_tempo_proto_msgTypes[30], x)
}

func (x *InstantSeries) ProtoReflect() protoreflect.Message {
	file_tempopb_tempo_proto_init()
	return protohelpers.NewMessageReflect(&file_tempopb_tempo_proto_msgTypes[31], x)
}

func (x *QueryRangeRequest) ProtoReflect() protoreflect.Message {
	file_tempopb_tempo_proto_init()
	return protohelpers.NewMessageReflect(&file_tempopb_tempo_proto_msgTypes[32], x)
}

func (x *QueryRangeResponse) ProtoReflect() protoreflect.Message {
	file_tempopb_tempo_proto_init()
	return protohelpers.NewMessageReflect(&file_tempopb_tempo_proto_msgTypes[33], x)
}

func (x *Exemplar) ProtoReflect() protoreflect.Message {
	file_tempopb_tempo_proto_init()
	return protohelpers.NewMessageReflect(&file_tempopb_tempo_proto_msgTypes[34], x)
}

func (x *Sample) ProtoReflect() protoreflect.Message {
	file_tempopb_tempo_proto_init()
	return protohelpers.NewMessageReflect(&file_tempopb_tempo_proto_msgTypes[35], x)
}

func (x *TimeSeries) ProtoReflect() protoreflect.Message {
	file_tempopb_tempo_proto_init()
	return protohelpers.NewMessageReflect(&file_tempopb_tempo_proto_msgTypes[36], x)
}

const file_tempopb_tempo_proto_rawDesc = "" +
	"\x0a\x13\x74\x65\x6d\x70\x6f\x70\x62\x2f\x74\x65\x6d\x70\x6f\x2e\x70\x72\x6f\x74\x6f\x12\x07\x74\x65\x6d\x70\x6f\x70\x62\x1a\x16\x63\x6f\x6d\x6d\x6f\x6e\x2f\x76" +
	"\x31\x2f\x63\x6f\x6d\x6d\x6f\x6e\x2e\x70\x72\x6f\x74\x6f\x1a\x14\x74\x72\x61\x63\x65\x2f\x76\x31\x2f\x74\x72\x61\x63\x65\x2e\x70\x72\x6f\x74\x6f\x1a\x1f\x67\x6f" +
	"\x6f\x67\x6c\x65\x2f\x70\x72\x6f\x74\x6f\x62\x75\x66\x2f\x74\x69\x6d\x65\x73\x74\x61\x6d\x70\x2e\x70\x72\x6f\x74\x6f\x22\xf4\x01\x0a\x10\x54\x72\x61\x63\x65\x42" +
	"\x79\x49\x44\x52\x65\x71\x75\x65\x73\x74\x12\x18\x0a\x07\x74\x72\x61\x63\x65\x49\x44\x18\x01\x20\x01\x28\x0c\x52\x07\x74\x72\x61\x63\x65\x49\x44\x12\x1e\x0a\x0a" +
	"\x62\x6c\x6f\x63\x6b\x53\x74\x61\x72\x74\x18\x02\x20\x01\x28\x09\x52\x0a\x62\x6c\x6f\x63\x6b\x53\x74\x61\x72\x74\x12\x1a\x0a\x08\x62\x6c\x6f\x63\x6b\x45\x6e\x64" +
	"\x18\x03\x20\x01\x28\x09\x52\x08\x62\x6c\x6f\x63\x6b\x45\x6e\x64\x12\x1c\x0a\x09\x71\x75\x65\x72\x79\x4d\x6f\x64\x65\x18\x05\x20\x01\x28\x09\x52\x09\x71\x75\x65" +
	"\x72\x79\x4d\x6f\x64\x65\x12\x2c\x0a\x11\x61\x6c\x6c\x6f\x77\x50\x61\x72\x74\x69\x61\x6c\x54\x72\x61\x63\x65\x18\x06\x20\x01\x28\x08\x52\x11\x61\x6c\x6c\x6f\x77" +
	"\x50\x61\x72\x74\x69\x61\x6c\x54\x72\x61\x63\x65\x12\x3e\x0a\x08\x52\x46\x31\x41\x66\x74\x65\x72\x18\x07\x20\x01\x28\x0b\x32\x1a\x2e\x67\x6f\x6f\x67\x6c\x65\x2e" +
	"\x70\x72\x6f\x74\x6f\x62\x75\x66\x2e\x54\x69\x6d\x65\x73\x74\x61\x6d\x70\x42\x06\x90\xb7\x18\x01\x18\x01\x52\x08\x52\x46\x31\x41\x66\x74\x65\x72\x22\xc4\x01\x0a" +
	"\x11\x54\x72\x61\x63\x65\x42\x79\x49\x44\x52\x65\x73\x70\x6f\x6e\x73\x65\x12\x2a\x0a\x05\x74\x72\x61\x63\x65\x18\x01\x20\x01\x28\x0b\x32\x0e\x2e\x74\x65\x6d\x70" +
	"\x6f\x70\x62\x2e\x54\x72\x61\x63\x65\x42\x04\xf0\xb6\x18\x01\x52\x05\x74\x72\x61\x63\x65\x12\x39\x0a\x07\x6d\x65\x74\x72\x69\x63\x73\x18\x02\x20\x01\x28\x0b\x32" +
	"\x19\x2e\x74\x65\x6d\x70\x6f\x70\x62\x2e\x54\x72\x61\x63\x65\x42\x79\x49\x44\x4d\x65\x74\x72\x69\x63\x73\x42\x04\xf0\xb6\x18\x01\x52\x07\x6d\x65\x74\x72\x69\x63" +
	"\x73\x12\x2e\x0a\x06\x73\x74\x61\x74\x75\x73\x18\x03\x20\x01\x28\x0e\x32\x16\x2e\x74\x65\x6d\x70\x6f\x70\x62\x2e\x50\x61\x72\x74\x69\x61\x6c\x53\x74\x61\x74\x75" +
	"\x73\x52\x06\x73\x74\x61\x74\x75\x73\x12\x18\x0a\x07\x6d\x65\x73\x73\x61\x67\x65\x18\x04\x20\x01\x28\x09\x52\x07\x6d\x65\x73\x73\x61\x67\x65\x22\x3a\x0a\x10\x54" +
	"\x72\x61\x63\x65\x42\x79\x49\x44\x4d\x65\x74\x72\x69\x63\x73\x12\x26\x0a\x0e\x69\x6e\x73\x70\x65\x63\x74\x65\x64\x42\x79\x74\x65\x73\x18\x01\x20\x01\x28\x04\x52" +
	"\x0e\x69\x6e\x73\x70\x65\x63\x74\x65\x64\x42\x79\x74\x65\x73\x22\xc0\x03\x0a\x0d\x53\x65\x61\x72\x63\x68\x52\x65\x71\x75\x65\x73\x74\x12\x34\x0a\x04\x54\x61\x67" +
	"\x73\x18\x01\x20\x03\x28\x0b\x32\x20\x2e\x74\x65\x6d\x70\x6f\x70\x62\x2e\x53\x65\x61\x72\x63\x68\x52\x65\x71\x75\x65\x73\x74\x2e\x54\x61\x67\x73\x45\x6e\x74\x72" +
	"\x79\x52\x04\x54\x61\x67\x73\x12\x24\x0a\x0d\x4d\x69\x6e\x44\x75\x72\x61\x74\x69\x6f\x6e\x4d\x73\x18\x02\x20\x01\x28\x0d\x52\x0d\x4d\x69\x6e\x44\x75\x72\x61\x74" +
	"\x69\x6f\x6e\x4d\x73\x12\x24\x0a\x0d\x4d\x61\x78\x44\x75\x72\x61\x74\x69\x6f\x6e\x4d\x73\x18\x03\x20\x01\x28\x0d\x52\x0d\x4d\x61\x78\x44\x75\x72\x61\x74\x69\x6f" +
	"\x6e\x4d\x73\x12\x14\x0a\x05\x4c\x69\x6d\x69\x74\x18\x04\x20\x01\x28\x0d\x52\x05\x4c\x69\x6d\x69\x74\x12\x14\x0a\x05\x73\x74\x61\x72\x74\x18\x05\x20\x01\x28\x0d" +
	"\x52\x05\x73\x74\x61\x72\x74\x12\x10\x0a\x03\x65\x6e\x64\x18\x06\x20\x01\x28\x0d\x52\x03\x65\x6e\x64\x12\x14\x0a\x05\x51\x75\x65\x72\x79\x18\x08\x20\x01\x28\x09" +
	"\x52\x05\x51\x75\x65\x72\x79\x12\x28\x0a\x0f\x53\x70\x61\x6e\x73\x50\x65\x72\x53\x70\x61\x6e\x53\x65\x74\x18\x09\x20\x01\x28\x0d\x52\x0f\x53\x70\x61\x6e\x73\x50" +
	"\x65\x72\x53\x70\x61\x6e\x53\x65\x74\x12\x3e\x0a\x08\x52\x46\x31\x41\x66\x74\x65\x72\x18\x0a\x20\x01\x28\x0b\x32\x1a\x2e\x67\x6f\x6f\x67\x6c\x65\x2e\x70\x72\x6f" +
	"\x74\x6f\x62\x75\x66\x2e\x54\x69\x6d\x65\x73\x74\x61\x6d\x70\x42\x06\x90\xb7\x18\x01\x18\x01\x52\x08\x52\x46\x31\x41\x66\x74\x65\x72\x12\x36\x0a\x16\x73\x6b\x69" +
	"\x70\x41\x53\x54\x54\x72\x61\x6e\x73\x66\x6f\x72\x6d\x61\x74\x69\x6f\x6e\x73\x18\x0b\x20\x03\x28\x09\x52\x16\x73\x6b\x69\x70\x41\x53\x54\x54\x72\x61\x6e\x73\x66" +
	"\x6f\x72\x6d\x61\x74\x69\x6f\x6e\x73\x1a\x37\x0a\x09\x54\x61\x67\x73\x45\x6e\x74\x72\x79\x12\x10\x0a\x03\x6b\x65\x79\x18\x01\x20\x01\x28\x09\x52\x03\x6b\x65\x79" +
	"\x12\x14\x0a\x05\x76\x61\x6c\x75\x65\x18\x02\x20\x01\x28\x09\x52\x05\x76\x61\x6c\x75\x65\x3a\x02\x38\x01\x22\x9d\x03\x0a\x12\x53\x65\x61\x72\x63\x68\x42\x6c\x6f" +
	"\x63\x6b\x52\x65\x71\x75\x65\x73\x74\x12\x3a\x0a\x09\x73\x65\x61\x72\x63\x68\x52\x65\x71\x18\x01\x20\x01\x28\x0b\x32\x16\x2e\x74\x65\x6d\x70\x6f\x70\x62\x2e\x53" +
	"\x65\x61\x72\x63\x68\x52\x65\x71\x75\x65\x73\x74\x42\x04\xf0\xb6\x18\x01\x52\x09\x73\x65\x61\x72\x63\x68\x52\x65\x71\x12\x18\x0a\x07\x62\x6c\x6f\x63\x6b\x49\x44" +
	"\x18\x02\x20\x01\x28\x09\x52\x07\x62\x6c\x6f\x63\x6b\x49\x44\x12\x1c\x0a\x09\x73\x74\x61\x72\x74\x50\x61\x67\x65\x18\x03\x20\x01\x28\x0d\x52\x09\x73\x74\x61\x72" +
	"\x74\x50\x61\x67\x65\x12\x24\x0a\x0d\x70\x61\x67\x65\x73\x54\x6f\x53\x65\x61\x72\x63\x68\x18\x04\x20\x01\x28\x0d\x52\x0d\x70\x61\x67\x65\x73\x54\x6f\x53\x65\x61" +
	"\x72\x63\x68\x12\x24\x0a\x0d\x69\x6e\x64\x65\x78\x50\x61\x67\x65\x53\x69\x7a\x65\x18\x06\x20\x01\x28\x0d\x52\x0d\x69\x6e\x64\x65\x78\x50\x61\x67\x65\x53\x69\x7a" +
	"\x65\x12\x22\x0a\x0c\x74\x6f\x74\x61\x6c\x52\x65\x63\x6f\x72\x64\x73\x18\x07\x20\x01\x28\x0d\x52\x0c\x74\x6f\x74\x61\x6c\x52\x65\x63\x6f\x72\x64\x73\x12\x18\x0a" +
	"\x07\x76\x65\x72\x73\x69\x6f\x6e\x18\x09\x20\x01\x28\x09\x52\x07\x76\x65\x72\x73\x69\x6f\x6e\x12\x1d\x0a\x04\x73\x69\x7a\x65\x18\x0a\x20\x01\x28\x04\x42\x09\x8a" +
	"\xb7\x18\x05\x53\x69\x7a\x65\x5f\x52\x04\x73\x69\x7a\x65\x12\x1e\x0a\x0a\x66\x6f\x6f\x74\x65\x72\x53\x69\x7a\x65\x18\x0b\x20\x01\x28\x0d\x52\x0a\x66\x6f\x6f\x74" +
	"\x65\x72\x53\x69\x7a\x65\x12\x4a\x0a\x10\x64\x65\x64\x69\x63\x61\x74\x65\x64\x43\x6f\x6c\x75\x6d\x6e\x73\x18\x0c\x20\x03\x28\x0b\x32\x18\x2e\x74\x65\x6d\x70\x6f" +
	"\x70\x62\x2e\x44\x65\x64\x69\x63\x61\x74\x65\x64\x43\x6f\x6c\x75\x6d\x6e\x42\x04\xf0\xb6\x18\x01\x52\x10\x64\x65\x64\x69\x63\x61\x74\x65\x64\x43\x6f\x6c\x75\x6d" +
	"\x6e\x73\x22\xbb\x02\x0a\x0f\x44\x65\x64\x69\x63\x61\x74\x65\x64\x43\x6f\x6c\x75\x6d\x6e\x12\x34\x0a\x05\x73\x63\x6f\x70\x65\x18\x03\x20\x01\x28\x0e\x32\x1e\x2e" +
	"\x74\x65\x6d\x70\x6f\x70\x62\x2e\x44\x65\x64\x69\x63\x61\x74\x65\x64\x43\x6f\x6c\x75\x6d\x6e\x2e\x53\x63\x6f\x70\x65\x52\x05\x73\x63\x6f\x70\x65\x12\x12\x0a\x04" +
	"\x6e\x61\x6d\x65\x18\x02\x20\x01\x28\x09\x52\x04\x6e\x61\x6d\x65\x12\x31\x0a\x04\x74\x79\x70\x65\x18\x01\x20\x01\x28\x0e\x32\x1d\x2e\x74\x65\x6d\x70\x6f\x70\x62" +
	"\x2e\x44\x65\x64\x69\x63\x61\x74\x65\x64\x43\x6f\x6c\x75\x6d\x6e\x2e\x54\x79\x70\x65\x52\x04\x74\x79\x70\x65\x12\x39\x0a\x07\x6f\x70\x74\x69\x6f\x6e\x73\x18\x04" +
	"\x20\x01\x28\x0e\x32\x1f\x2e\x74\x65\x6d\x70\x6f\x70\x62\x2e\x44\x65\x64\x69\x63\x61\x74\x65\x64\x43\x6f\x6c\x75\x6d\x6e\x2e\x4f\x70\x74\x69\x6f\x6e\x52\x07\x6f" +
	"\x70\x74\x69\x6f\x6e\x73\x22\x2a\x0a\x05\x53\x63\x6f\x70\x65\x12\x08\x0a\x04\x53\x50\x41\x4e\x10\x00\x12\x0c\x0a\x08\x52\x45\x53\x4f\x55\x52\x43\x45\x10\x01\x12" +
	"\x09\x0a\x05\x45\x56\x45\x4e\x54\x10\x02\x22\x1b\x0a\x04\x54\x79\x70\x65\x12\x0a\x0a\x06\x53\x54\x52\x49\x4e\x47\x10\x00\x12\x07\x0a\x03\x49\x4e\x54\x10\x01\x22" +
	"\x27\x0a\x06\x4f\x70\x74\x69\x6f\x6e\x12\x08\x0a\x04\x4e\x4f\x4e\x45\x10\x00\x12\x09\x0a\x05\x41\x52\x52\x41\x59\x10\x01\x12\x08\x0a\x04\x42\x4c\x4f\x42\x10\x02" +
	"\x22\x84\x01\x0a\x0e\x53\x65\x61\x72\x63\x68\x52\x65\x73\x70\x6f\x6e\x73\x65\x12\x3a\x0a\x06\x74\x72\x61\x63\x65\x73\x18\x01\x20\x03\x28\x0b\x32\x1c\x2e\x74\x65" +
	"\x6d\x70\x6f\x70\x62\x2e\x54\x72\x61\x63\x65\x53\x65\x61\x72\x63\x68\x4d\x65\x74\x61\x64\x61\x74\x61\x42\x04\xf0\xb6\x18\x01\x52\x06\x74\x72\x61\x63\x65\x73\x12" +
	"\x36\x0a\x07\x6d\x65\x74\x72\x69\x63\x73\x18\x02\x20\x01\x28\x0b\x32\x16\x2e\x74\x65\x6d\x70\x6f\x70\x62\x2e\x53\x65\x61\x72\x63\x68\x4d\x65\x74\x72\x69\x63\x73" +
	"\x42\x04\xf0\xb6\x18\x01\x52\x07\x6d\x65\x74\x72\x69\x63\x73\x22\xdf\x03\x0a\x13\x54\x72\x61\x63\x65\x53\x65\x61\x72\x63\x68\x4d\x65\x74\x61\x64\x61\x74\x61\x12" +
	"\x18\x0a\x07\x74\x72\x61\x63\x65\x49\x44\x18\x01\x20\x01\x28\x09\x52\x07\x74\x72\x61\x63\x65\x49\x44\x12\x28\x0a\x0f\x72\x6f\x6f\x74\x53\x65\x72\x76\x69\x63\x65" +
	"\x4e\x61\x6d\x65\x18\x02\x20\x01\x28\x09\x52\x0f\x72\x6f\x6f\x74\x53\x65\x72\x76\x69\x63\x65\x4e\x61\x6d\x65\x12\x24\x0a\x0d\x72\x6f\x6f\x74\x54\x72\x61\x63\x65" +
	"\x4e\x61\x6d\x65\x18\x03\x20\x01\x28\x09\x52\x0d\x72\x6f\x6f\x74\x54\x72\x61\x63\x65\x4e\x61\x6d\x65\x12\x2c\x0a\x11\x73\x74\x61\x72\x74\x54\x69\x6d\x65\x55\x6e" +
	"\x69\x78\x4e\x61\x6e\x6f\x18\x04\x20\x01\x28\x04\x52\x11\x73\x74\x61\x72\x74\x54\x69\x6d\x65\x55\x6e\x69\x78\x4e\x61\x6e\x6f\x12\x1e\x0a\x0a\x64\x75\x72\x61\x74" +
	"\x69\x6f\x6e\x4d\x73\x18\x05\x20\x01\x28\x0d\x52\x0a\x64\x75\x72\x61\x74\x69\x6f\x6e\x4d\x73\x12\x30\x0a\x07\x73\x70\x61\x6e\x53\x65\x74\x18\x06\x20\x01\x28\x0b" +
	"\x32\x10\x2e\x74\x65\x6d\x70\x6f\x70\x62\x2e\x53\x70\x61\x6e\x53\x65\x74\x42\x04\xf0\xb6\x18\x01\x52\x07\x73\x70\x61\x6e\x53\x65\x74\x12\x32\x0a\x08\x73\x70\x61" +
	"\x6e\x53\x65\x74\x73\x18\x07\x20\x03\x28\x0b\x32\x10\x2e\x74\x65\x6d\x70\x6f\x70\x62\x2e\x53\x70\x61\x6e\x53\x65\x74\x42\x04\xf0\xb6\x18\x01\x52\x08\x73\x70\x61" +
	"\x6e\x53\x65\x74\x73\x12\x52\x0a\x0c\x73\x65\x72\x76\x69\x63\x65\x53\x74\x61\x74\x73\x18\x08\x20\x03\x28\x0b\x32\x2e\x2e\x74\x65\x6d\x70\x6f\x70\x62\x2e\x54\x72" +
	"\x61\x63\x65\x53\x65\x61\x72\x63\x68\x4d\x65\x74\x61\x64\x61\x74\x61\x2e\x53\x65\x72\x76\x69\x63\x65\x53\x74\x61\x74\x73\x45\x6e\x74\x72\x79\x52\x0c\x73\x65\x72" +
	"\x76\x69\x63\x65\x53\x74\x61\x74\x73\x1a\x56\x0a\x11\x53\x65\x72\x76\x69\x63\x65\x53\x74\x61\x74\x73\x45\x6e\x74\x72\x79\x12\x10\x0a\x03\x6b\x65\x79\x18\x01\x20" +
	"\x01\x28\x09\x52\x03\x6b\x65\x79\x12\x2b\x0a\x05\x76\x61\x6c\x75\x65\x18\x02\x20\x01\x28\x0b\x32\x15\x2e\x74\x65\x6d\x70\x6f\x70\x62\x2e\x53\x65\x72\x76\x69\x63" +
	"\x65\x53\x74\x61\x74\x73\x52\x05\x76\x61\x6c\x75\x65\x3a\x02\x38\x01\x22\x4c\x0a\x0c\x53\x65\x72\x76\x69\x63\x65\x53\x74\x61\x74\x73\x12\x1c\x0a\x09\x73\x70\x61" +
	"\x6e\x43\x6f\x75\x6e\x74\x18\x01\x20\x01\x28\x0d\x52\x09\x73\x70\x61\x6e\x43\x6f\x75\x6e\x74\x12\x1e\x0a\x0a\x65\x72\x72\x6f\x72\x43\x6f\x75\x6e\x74\x18\x02\x20" +
	"\x01\x28\x0d\x52\x0a\x65\x72\x72\x6f\x72\x43\x6f\x75\x6e\x74\x22\x91\x01\x0a\x07\x53\x70\x61\x6e\x53\x65\x74\x12\x29\x0a\x05\x73\x70\x61\x6e\x73\x18\x01\x20\x03" +
	"\x28\x0b\x32\x0d\x2e\x74\x65\x6d\x70\x6f\x70\x62\x2e\x53\x70\x61\x6e\x42\x04\xf0\xb6\x18\x01\x52\x05\x73\x70\x61\x6e\x73\x12\x18\x0a\x07\x6d\x61\x74\x63\x68\x65" +
	"\x64\x18\x02\x20\x01\x28\x0d\x52\x07\x6d\x61\x74\x63\x68\x65\x64\x12\x41\x0a\x0a\x61\x74\x74\x72\x69\x62\x75\x74\x65\x73\x18\x03\x20\x03\x28\x0b\x32\x1b\x2e\x74" +
	"\x65\x6d\x70\x6f\x70\x62\x2e\x63\x6f\x6d\x6d\x6f\x6e\x2e\x76\x31\x2e\x4b\x65\x79\x56\x61\x6c\x75\x65\x42\x04\xf0\xb6\x18\x01\x52\x0a\x61\x74\x74\x72\x69\x62\x75" +
	"\x74\x65\x73\x22\xc9\x01\x0a\x04\x53\x70\x61\x6e\x12\x16\x0a\x06\x73\x70\x61\x6e\x49\x44\x18\x01\x20\x01\x28\x09\x52\x06\x73\x70\x61\x6e\x49\x44\x12\x12\x0a\x04" +
	"\x6e\x61\x6d\x65\x18\x02\x20\x01\x28\x09\x52\x04\x6e\x61\x6d\x65\x12\x2c\x0a\x11\x73\x74\x61\x72\x74\x54\x69\x6d\x65\x55\x6e\x69\x78\x4e\x61\x6e\x6f\x18\x03\x20" +
	"\x01\x28\x04\x52\x11\x73\x74\x61\x72\x74\x54\x69\x6d\x65\x55\x6e\x69\x78\x4e\x61\x6e\x6f\x12\x24\x0a\x0d\x64\x75\x72\x61\x74\x69\x6f\x6e\x4e\x61\x6e\x6f\x73\x18" +
	"\x04\x20\x01\x28\x04\x52\x0d\x64\x75\x72\x61\x74\x69\x6f\x6e\x4e\x61\x6e\x6f\x73\x12\x41\x0a\x0a\x61\x74\x74\x72\x69\x62\x75\x74\x65\x73\x18\x05\x20\x03\x28\x0b" +
	"\x32\x1b\x2e\x74\x65\x6d\x70\x6f\x70\x62\x2e\x63\x6f\x6d\x6d\x6f\x6e\x2e\x76\x31\x2e\x4b\x65\x79\x56\x61\x6c\x75\x65\x42\x04\xf0\xb6\x18\x01\x52\x0a\x61\x74\x74" +
	"\x72\x69\x62\x75\x74\x65\x73\x22\x99\x02\x0a\x0d\x53\x65\x61\x72\x63\x68\x4d\x65\x74\x72\x69\x63\x73\x12\x28\x0a\x0f\x69\x6e\x73\x70\x65\x63\x74\x65\x64\x54\x72" +
	"\x61\x63\x65\x73\x18\x01\x20\x01\x28\x0d\x52\x0f\x69\x6e\x73\x70\x65\x63\x74\x65\x64\x54\x72\x61\x63\x65\x73\x12\x26\x0a\x0e\x69\x6e\x73\x70\x65\x63\x74\x65\x64" +
	"\x42\x79\x74\x65\x73\x18\x02\x20\x01\x28\x04\x52\x0e\x69\x6e\x73\x70\x65\x63\x74\x65\x64\x42\x79\x74\x65\x73\x12\x20\x0a\x0b\x74\x6f\x74\x61\x6c\x42\x6c\x6f\x63" +
	"\x6b\x73\x18\x03\x20\x01\x28\x0d\x52\x0b\x74\x6f\x74\x61\x6c\x42\x6c\x6f\x63\x6b\x73\x12\x24\x0a\x0d\x63\x6f\x6d\x70\x6c\x65\x74\x65\x64\x4a\x6f\x62\x73\x18\x04" +
	"\x20\x01\x28\x0d\x52\x0d\x63\x6f\x6d\x70\x6c\x65\x74\x65\x64\x4a\x6f\x62\x73\x12\x1c\x0a\x09\x74\x6f\x74\x61\x6c\x4a\x6f\x62\x73\x18\x05\x20\x01\x28\x0d\x52\x09" +
	"\x74\x6f\x74\x61\x6c\x4a\x6f\x62\x73\x12\x28\x0a\x0f\x74\x6f\x74\x61\x6c\x42\x6c\x6f\x63\x6b\x42\x79\x74\x65\x73\x18\x06\x20\x01\x28\x04\x52\x0f\x74\x6f\x74\x61" +
	"\x6c\x42\x6c\x6f\x63\x6b\x42\x79\x74\x65\x73\x12\x26\x0a\x0e\x69\x6e\x73\x70\x65\x63\x74\x65\x64\x53\x70\x61\x6e\x73\x18\x07\x20\x01\x28\x04\x52\x0e\x69\x6e\x73" +
	"\x70\x65\x63\x74\x65\x64\x53\x70\x61\x6e\x73\x22\x85\x02\x0a\x11\x53\x65\x61\x72\x63\x68\x54\x61\x67\x73\x52\x65\x71\x75\x65\x73\x74\x12\x14\x0a\x05\x73\x63\x6f" +
	"\x70\x65\x18\x01\x20\x01\x28\x09\x52\x05\x73\x63\x6f\x70\x65\x12\x14\x0a\x05\x71\x75\x65\x72\x79\x18\x02\x20\x01\x28\x09\x52\x05\x71\x75\x65\x72\x79\x12\x14\x0a" +
	"\x05\x73\x74\x61\x72\x74\x18\x03\x20\x01\x28\x0d\x52\x05\x73\x74\x61\x72\x74\x12\x10\x0a\x03\x65\x6e\x64\x18\x04\x20\x01\x28\x0d\x52\x03\x65\x6e\x64\x12\x28\x0a" +
	"\x0f\x6d\x61\x78\x54\x61\x67\x73\x50\x65\x72\x53\x63\x6f\x70\x65\x18\x05\x20\x01\x28\x0d\x52\x0f\x6d\x61\x78\x54\x61\x67\x73\x50\x65\x72\x53\x63\x6f\x70\x65\x12" +
	"\x32\x0a\x14\x73\x74\x61\x6c\x65\x56\x61\x6c\x75\x65\x73\x54\x68\x72\x65\x73\x68\x6f\x6c\x64\x18\x06\x20\x01\x28\x0d\x52\x14\x73\x74\x61\x6c\x65\x56\x61\x6c\x75" +
	"\x65\x73\x54\x68\x72\x65\x73\x68\x6f\x6c\x64\x12\x3e\x0a\x08\x52\x46\x31\x41\x66\x74\x65\x72\x18\x07\x20\x01\x28\x0b\x32\x1a\x2e\x67\x6f\x6f\x67\x6c\x65\x2e\x70" +
	"\x72\x6f\x74\x6f\x62\x75\x66\x2e\x54\x69\x6d\x65\x73\x74\x61\x6d\x70\x42\x06\x90\xb7\x18\x01\x18\x01\x52\x08\x52\x46\x31\x41\x66\x74\x65\x72\x22\x81\x04\x0a\x16" +
	"\x53\x65\x61\x72\x63\x68\x54\x61\x67\x73\x42\x6c\x6f\x63\x6b\x52\x65\x71\x75\x65\x73\x74\x12\x3e\x0a\x09\x73\x65\x61\x72\x63\x68\x52\x65\x71\x18\x01\x20\x01\x28" +
	"\x0b\x32\x1a\x2e\x74\x65\x6d\x70\x6f\x70\x62\x2e\x53\x65\x61\x72\x63\x68\x54\x61\x67\x73\x52\x65\x71\x75\x65\x73\x74\x42\x04\xf0\xb6\x18\x01\x52\x09\x73\x65\x61" +
	"\x72\x63\x68\x52\x65\x71\x12\x18\x0a\x07\x62\x6c\x6f\x63\x6b\x49\x44\x18\x02\x20\x01\x28\x09\x52\x07\x62\x6c\x6f\x63\x6b\x49\x44\x12\x1c\x0a\x09\x73\x74\x61\x72" +
	"\x74\x50\x61\x67\x65\x18\x03\x20\x01\x28\x0d\x52\x09\x73\x74\x61\x72\x74\x50\x61\x67\x65\x12\x24\x0a\x0d\x70\x61\x67\x65\x73\x54\x6f\x53\x65\x61\x72\x63\x68\x18" +
	"\x04\x20\x01\x28\x0d\x52\x0d\x70\x61\x67\x65\x73\x54\x6f\x53\x65\x61\x72\x63\x68\x12\x24\x0a\x0d\x69\x6e\x64\x65\x78\x50\x61\x67\x65\x53\x69\x7a\x65\x18\x06\x20" +
	"\x01\x28\x0d\x52\x0d\x69\x6e\x64\x65\x78\x50\x61\x67\x65\x53\x69\x7a\x65\x12\x22\x0a\x0c\x74\x6f\x74\x61\x6c\x52\x65\x63\x6f\x72\x64\x73\x18\x07\x20\x01\x28\x0d" +
	"\x52\x0c\x74\x6f\x74\x61\x6c\x52\x65\x63\x6f\x72\x64\x73\x12\x18\x0a\x07\x76\x65\x72\x73\x69\x6f\x6e\x18\x09\x20\x01\x28\x09\x52\x07\x76\x65\x72\x73\x69\x6f\x6e" +
	"\x12\x1d\x0a\x04\x73\x69\x7a\x65\x18\x0a\x20\x01\x28\x04\x42\x09\x8a\xb7\x18\x05\x53\x69\x7a\x65\x5f\x52\x04\x73\x69\x7a\x65\x12\x1e\x0a\x0a\x66\x6f\x6f\x74\x65" +
	"\x72\x53\x69\x7a\x65\x18\x0b\x20\x01\x28\x0d\x52\x0a\x66\x6f\x6f\x74\x65\x72\x53\x69\x7a\x65\x12\x4a\x0a\x10\x64\x65\x64\x69\x63\x61\x74\x65\x64\x43\x6f\x6c\x75" +
	"\x6d\x6e\x73\x18\x0c\x20\x03\x28\x0b\x32\x18\x2e\x74\x65\x6d\x70\x6f\x70\x62\x2e\x44\x65\x64\x69\x63\x61\x74\x65\x64\x43\x6f\x6c\x75\x6d\x6e\x42\x04\xf0\xb6\x18" +
	"\x01\x52\x10\x64\x65\x64\x69\x63\x61\x74\x65\x64\x43\x6f\x6c\x75\x6d\x6e\x73\x12\x28\x0a\x0f\x6d\x61\x78\x54\x61\x67\x73\x50\x65\x72\x53\x63\x6f\x70\x65\x18\x0d" +
	"\x20\x01\x28\x0d\x52\x0f\x6d\x61\x78\x54\x61\x67\x73\x50\x65\x72\x53\x63\x6f\x70\x65\x12\x30\x0a\x13\x73\x74\x61\x6c\x65\x56\x61\x6c\x75\x65\x54\x68\x72\x65\x73" +
	"\x68\x6f\x6c\x64\x18\x0e\x20\x01\x28\x0d\x52\x13\x73\x74\x61\x6c\x65\x56\x61\x6c\x75\x65\x54\x68\x72\x65\x73\x68\x6f\x6c\x64\x22\xaf\x03\x0a\x1b\x53\x65\x61\x72" +
	"\x63\x68\x54\x61\x67\x56\x61\x6c\x75\x65\x73\x42\x6c\x6f\x63\x6b\x52\x65\x71\x75\x65\x73\x74\x12\x43\x0a\x09\x73\x65\x61\x72\x63\x68\x52\x65\x71\x18\x01\x20\x01" +
	"\x28\x0b\x32\x1f\x2e\x74\x65\x6d\x70\x6f\x70\x62\x2e\x53\x65\x61\x72\x63\x68\x54\x61\x67\x56\x61\x6c\x75\x65\x73\x52\x65\x71\x75\x65\x73\x74\x42\x04\xf0\xb6\x18" +
	"\x01\x52\x09\x73\x65\x61\x72\x63\x68\x52\x65\x71\x12\x18\x0a\x07\x62\x6c\x6f\x63\x6b\x49\x44\x18\x02\x20\x01\x28\x09\x52\x07\x62\x6c\x6f\x63\x6b\x49\x44\x12\x1c" +
	"\x0a\x09\x73\x74\x61\x72\x74\x50\x61\x67\x65\x18\x03\x20\x01\x28\x0d\x52\x09\x73\x74\x61\x72\x74\x50\x61\x67\x65\x12\x24\x0a\x0d\x70\x61\x67\x65\x73\x54\x6f\x53" +
	"\x65\x61\x72\x63\x68\x18\x04\x20\x01\x28\x0d\x52\x0d\x70\x61\x67\x65\x73\x54\x6f\x53\x65\x61\x72\x63\x68\x12\x24\x0a\x0d\x69\x6e\x64\x65\x78\x50\x61\x67\x65\x53" +
	"\x69\x7a\x65\x18\x06\x20\x01\x28\x0d\x52\x0d\x69\x6e\x64\x65\x78\x50\x61\x67\x65\x53\x69\x7a\x65\x12\x22\x0a\x0c\x74\x6f\x74\x61\x6c\x52\x65\x63\x6f\x72\x64\x73" +
	"\x18\x07\x20\x01\x28\x0d\x52\x0c\x74\x6f\x74\x61\x6c\x52\x65\x63\x6f\x72\x64\x73\x12\x18\x0a\x07\x76\x65\x72\x73\x69\x6f\x6e\x18\x09\x20\x01\x28\x09\x52\x07\x76" +
	"\x65\x72\x73\x69\x6f\x6e\x12\x1d\x0a\x04\x73\x69\x7a\x65\x18\x0a\x20\x01\x28\x04\x42\x09\x8a\xb7\x18\x05\x53\x69\x7a\x65\x5f\x52\x04\x73\x69\x7a\x65\x12\x1e\x0a" +
	"\x0a\x66\x6f\x6f\x74\x65\x72\x53\x69\x7a\x65\x18\x0b\x20\x01\x28\x0d\x52\x0a\x66\x6f\x6f\x74\x65\x72\x53\x69\x7a\x65\x12\x4a\x0a\x10\x64\x65\x64\x69\x63\x61\x74" +
	"\x65\x64\x43\x6f\x6c\x75\x6d\x6e\x73\x18\x0c\x20\x03\x28\x0b\x32\x18\x2e\x74\x65\x6d\x70\x6f\x70\x62\x2e\x44\x65\x64\x69\x63\x61\x74\x65\x64\x43\x6f\x6c\x75\x6d" +
	"\x6e\x42\x04\xf0\xb6\x18\x01\x52\x10\x64\x65\x64\x69\x63\x61\x74\x65\x64\x43\x6f\x6c\x75\x6d\x6e\x73\x22\x6a\x0a\x12\x53\x65\x61\x72\x63\x68\x54\x61\x67\x73\x52" +
	"\x65\x73\x70\x6f\x6e\x73\x65\x12\x1a\x0a\x08\x74\x61\x67\x4e\x61\x6d\x65\x73\x18\x01\x20\x03\x28\x09\x52\x08\x74\x61\x67\x4e\x61\x6d\x65\x73\x12\x38\x0a\x07\x6d" +
	"\x65\x74\x72\x69\x63\x73\x18\x02\x20\x01\x28\x0b\x32\x18\x2e\x74\x65\x6d\x70\x6f\x70\x62\x2e\x4d\x65\x74\x61\x64\x61\x74\x61\x4d\x65\x74\x72\x69\x63\x73\x42\x04" +
	"\xf0\xb6\x18\x01\x52\x07\x6d\x65\x74\x72\x69\x63\x73\x22\x8a\x01\x0a\x14\x53\x65\x61\x72\x63\x68\x54\x61\x67\x73\x56\x32\x52\x65\x73\x70\x6f\x6e\x73\x65\x12\x38" +
	"\x0a\x06\x73\x63\x6f\x70\x65\x73\x18\x01\x20\x03\x28\x0b\x32\x1a\x2e\x74\x65\x6d\x70\x6f\x70\x62\x2e\x53\x65\x61\x72\x63\x68\x54\x61\x67\x73\x56\x32\x53\x63\x6f" +
	"\x70\x65\x42\x04\xf0\xb6\x18\x01\x52\x06\x73\x63\x6f\x70\x65\x73\x12\x38\x0a\x07\x6d\x65\x74\x72\x69\x63\x73\x18\x02\x20\x01\x28\x0b\x32\x18\x2e\x74\x65\x6d\x70" +
	"\x6f\x70\x62\x2e\x4d\x65\x74\x61\x64\x61\x74\x61\x4d\x65\x74\x72\x69\x63\x73\x42\x04\xf0\xb6\x18\x01\x52\x07\x6d\x65\x74\x72\x69\x63\x73\x22\x3b\x0a\x11\x53\x65" +
	"\x61\x72\x63\x68\x54\x61\x67\x73\x56\x32\x53\x63\x6f\x70\x65\x12\x12\x0a\x04\x6e\x61\x6d\x65\x18\x01\x20\x01\x28\x09\x52\x04\x6e\x61\x6d\x65\x12\x12\x0a\x04\x74" +
	"\x61\x67\x73\x18\x02\x20\x03\x28\x09\x52\x04\x74\x61\x67\x73\x22\x86\x02\x0a\x16\x53\x65\x61\x72\x63\x68\x54\x61\x67\x56\x61\x6c\x75\x65\x73\x52\x65\x71\x75\x65" +
	"\x73\x74\x12\x18\x0a\x07\x74\x61\x67\x4e\x61\x6d\x65\x18\x01\x20\x01\x28\x09\x52\x07\x74\x61\x67\x4e\x61\x6d\x65\x12\x14\x0a\x05\x71\x75\x65\x72\x79\x18\x02\x20" +
	"\x01\x28\x09\x52\x05\x71\x75\x65\x72\x79\x12\x14\x0a\x05\x73\x74\x61\x72\x74\x18\x04\x20\x01\x28\x0d\x52\x05\x73\x74\x61\x72\x74\x12\x10\x0a\x03\x65\x6e\x64\x18" +
	"\x05\x20\x01\x28\x0d\x52\x03\x65\x6e\x64\x12\x22\x0a\x0c\x6d\x61\x78\x54\x61\x67\x56\x61\x6c\x75\x65\x73\x18\x06\x20\x01\x28\x0d\x52\x0c\x6d\x61\x78\x54\x61\x67" +
	"\x56\x61\x6c\x75\x65\x73\x12\x30\x0a\x13\x73\x74\x61\x6c\x65\x56\x61\x6c\x75\x65\x54\x68\x72\x65\x73\x68\x6f\x6c\x64\x18\x07\x20\x01\x28\x0d\x52\x13\x73\x74\x61" +
	"\x6c\x65\x56\x61\x6c\x75\x65\x54\x68\x72\x65\x73\x68\x6f\x6c\x64\x12\x3e\x0a\x08\x52\x46\x31\x41\x66\x74\x65\x72\x18\x08\x20\x01\x28\x0b\x32\x1a\x2e\x67\x6f\x6f" +
	"\x67\x6c\x65\x2e\x70\x72\x6f\x74\x6f\x62\x75\x66\x2e\x54\x69\x6d\x65\x73\x74\x61\x6d\x70\x42\x06\x90\xb7\x18\x01\x18\x01\x52\x08\x52\x46\x31\x41\x66\x74\x65\x72" +
	"\x22\x71\x0a\x17\x53\x65\x61\x72\x63\x68\x54\x61\x67\x56\x61\x6c\x75\x65\x73\x52\x65\x73\x70\x6f\x6e\x73\x65\x12\x1c\x0a\x09\x74\x61\x67\x56\x61\x6c\x75\x65\x73" +
	"\x18\x01\x20\x03\x28\x09\x52\x09\x74\x61\x67\x56\x61\x6c\x75\x65\x73\x12\x38\x0a\x07\x6d\x65\x74\x72\x69\x63\x73\x18\x02\x20\x01\x28\x0b\x32\x18\x2e\x74\x65\x6d" +
	"\x70\x6f\x70\x62\x2e\x4d\x65\x74\x61\x64\x61\x74\x61\x4d\x65\x74\x72\x69\x63\x73\x42\x04\xf0\xb6\x18\x01\x52\x07\x6d\x65\x74\x72\x69\x63\x73\x22\x34\x0a\x08\x54" +
	"\x61\x67\x56\x61\x6c\x75\x65\x12\x12\x0a\x04\x74\x79\x70\x65\x18\x01\x20\x01\x28\x09\x52\x04\x74\x79\x70\x65\x12\x14\x0a\x05\x76\x61\x6c\x75\x65\x18\x02\x20\x01" +
	"\x28\x09\x52\x05\x76\x61\x6c\x75\x65\x22\x8c\x01\x0a\x19\x53\x65\x61\x72\x63\x68\x54\x61\x67\x56\x61\x6c\x75\x65\x73\x56\x32\x52\x65\x73\x70\x6f\x6e\x73\x65\x12" +
	"\x35\x0a\x09\x74\x61\x67\x56\x61\x6c\x75\x65\x73\x18\x01\x20\x03\x28\x0b\x32\x11\x2e\x74\x65\x6d\x70\x6f\x70\x62\x2e\x54\x61\x67\x56\x61\x6c\x75\x65\x42\x04\xf0" +
	"\xb6\x18\x01\x52\x09\x74\x61\x67\x56\x61\x6c\x75\x65\x73\x12\x38\x0a\x07\x6d\x65\x74\x72\x69\x63\x73\x18\x02\x20\x01\x28\x0b\x32\x18\x2e\x74\x65\x6d\x70\x6f\x70" +
	"\x62\x2e\x4d\x65\x74\x61\x64\x61\x74\x61\x4d\x65\x74\x72\x69\x63\x73\x42\x04\xf0\xb6\x18\x01\x52\x07\x6d\x65\x74\x72\x69\x63\x73\x22\xc9\x01\x0a\x0f\x4d\x65\x74" +
	"\x61\x64\x61\x74\x61\x4d\x65\x74\x72\x69\x63\x73\x12\x26\x0a\x0e\x69\x6e\x73\x70\x65\x63\x74\x65\x64\x42\x79\x74\x65\x73\x18\x01\x20\x01\x28\x04\x52\x0e\x69\x6e" +
	"\x73\x70\x65\x63\x74\x65\x64\x42\x79\x74\x65\x73\x12\x1c\x0a\x09\x74\x6f\x74\x61\x6c\x4a\x6f\x62\x73\x18\x02\x20\x01\x28\x0d\x52\x09\x74\x6f\x74\x61\x6c\x4a\x6f" +
	"\x62\x73\x12\x24\x0a\x0d\x63\x6f\x6d\x70\x6c\x65\x74\x65\x64\x4a\x6f\x62\x73\x18\x03\x20\x01\x28\x0d\x52\x0d\x63\x6f\x6d\x70\x6c\x65\x74\x65\x64\x4a\x6f\x62\x73" +
	"\x12\x20\x0a\x0b\x74\x6f\x74\x61\x6c\x42\x6c\x6f\x63\x6b\x73\x18\x04\x20\x01\x28\x0d\x52\x0b\x74\x6f\x74\x61\x6c\x42\x6c\x6f\x63\x6b\x73\x12\x28\x0a\x0f\x74\x6f" +
	"\x74\x61\x6c\x42\x6c\x6f\x63\x6b\x42\x79\x74\x65\x73\x18\x05\x20\x01\x28\x04\x52\x0f\x74\x6f\x74\x61\x6c\x42\x6c\x6f\x63\x6b\x42\x79\x74\x65\x73\x22\x54\x0a\x05" +
	"\x54\x72\x61\x63\x65\x12\x4b\x0a\x0d\x72\x65\x73\x6f\x75\x72\x63\x65\x53\x70\x61\x6e\x73\x18\x01\x20\x03\x28\x0b\x32\x1f\x2e\x74\x65\x6d\x70\x6f\x70\x62\x2e\x74" +
	"\x72\x61\x63\x65\x2e\x76\x31\x2e\x52\x65\x73\x6f\x75\x72\x63\x65\x53\x70\x61\x6e\x73\x42\x04\xf0\xb6\x18\x01\x52\x0d\x72\x65\x73\x6f\x75\x72\x63\x65\x53\x70\x61" +
	"\x6e\x73\x22\x4e\x0a\x0c\x50\x75\x73\x68\x52\x65\x73\x70\x6f\x6e\x73\x65\x12\x3e\x0a\x0d\x65\x72\x72\x6f\x72\x73\x42\x79\x54\x72\x61\x63\x65\x18\x01\x20\x03\x28" +
	"\x0e\x32\x18\x2e\x74\x65\x6d\x70\x6f\x70\x62\x2e\x50\x75\x73\x68\x45\x72\x72\x6f\x72\x52\x65\x61\x73\x6f\x6e\x52\x0d\x65\x72\x72\x6f\x72\x73\x42\x79\x54\x72\x61" +
	"\x63\x65\x22\x85\x01\x0a\x10\x50\x75\x73\x68\x42\x79\x74\x65\x73\x52\x65\x71\x75\x65\x73\x74\x12\x29\x0a\x06\x74\x72\x61\x63\x65\x73\x18\x02\x20\x03\x28\x0c\x42" +
	"\x11\x82\xb7\x18\x0d\x50\x72\x65\x61\x6c\x6c\x6f\x63\x42\x79\x74\x65\x73\x52\x06\x74\x72\x61\x63\x65\x73\x12\x10\x0a\x03\x69\x64\x73\x18\x03\x20\x03\x28\x0c\x52" +
	"\x03\x69\x64\x73\x12\x34\x0a\x15\x73\x6b\x69\x70\x4d\x65\x74\x72\x69\x63\x73\x47\x65\x6e\x65\x72\x61\x74\x69\x6f\x6e\x18\x05\x20\x01\x28\x08\x52\x15\x73\x6b\x69" +
	"\x70\x4d\x65\x74\x72\x69\x63\x73\x47\x65\x6e\x65\x72\x61\x74\x69\x6f\x6e\x22\x89\x01\x0a\x10\x50\x75\x73\x68\x53\x70\x61\x6e\x73\x52\x65\x71\x75\x65\x73\x74\x12" +
	"\x3f\x0a\x07\x62\x61\x74\x63\x68\x65\x73\x18\x01\x20\x03\x28\x0b\x32\x1f\x2e\x74\x65\x6d\x70\x6f\x70\x62\x2e\x74\x72\x61\x63\x65\x2e\x76\x31\x2e\x52\x65\x73\x6f" +
	"\x75\x72\x63\x65\x53\x70\x61\x6e\x73\x42\x04\xf0\xb6\x18\x01\x52\x07\x62\x61\x74\x63\x68\x65\x73\x12\x34\x0a\x15\x73\x6b\x69\x70\x4d\x65\x74\x72\x69\x63\x73\x47" +
	"\x65\x6e\x65\x72\x61\x74\x69\x6f\x6e\x18\x02\x20\x01\x28\x08\x52\x15\x73\x6b\x69\x70\x4d\x65\x74\x72\x69\x63\x73\x47\x65\x6e\x65\x72\x61\x74\x69\x6f\x6e\x22\x24" +
	"\x0a\x0a\x54\x72\x61\x63\x65\x42\x79\x74\x65\x73\x12\x16\x0a\x06\x74\x72\x61\x63\x65\x73\x18\x01\x20\x03\x28\x0c\x52\x06\x74\x72\x61\x63\x65\x73\x22\x44\x0a\x09" +
	"\x4c\x69\x6e\x6b\x53\x6c\x69\x63\x65\x12\x37\x0a\x05\x6c\x69\x6e\x6b\x73\x18\x01\x20\x03\x28\x0b\x32\x1b\x2e\x74\x65\x6d\x70\x6f\x70\x62\x2e\x74\x72\x61\x63\x65" +
	"\x2e\x76\x31\x2e\x53\x70\x61\x6e\x2e\x4c\x69\x6e\x6b\x42\x04\xf0\xb6\x18\x01\x52\x05\x6c\x69\x6e\x6b\x73\x22\x53\x0a\x13\x51\x75\x65\x72\x79\x49\x6e\x73\x74\x61" +
	"\x6e\x74\x52\x65\x71\x75\x65\x73\x74\x12\x14\x0a\x05\x71\x75\x65\x72\x79\x18\x01\x20\x01\x28\x09\x52\x05\x71\x75\x65\x72\x79\x12\x14\x0a\x05\x73\x74\x61\x72\x74" +
	"\x18\x02\x20\x01\x28\x04\x52\x05\x73\x74\x61\x72\x74\x12\x10\x0a\x03\x65\x6e\x64\x18\x03\x20\x01\x28\x04\x52\x03\x65\x6e\x64\x22\xce\x01\x0a\x14\x51\x75\x65\x72" +
	"\x79\x49\x6e\x73\x74\x61\x6e\x74\x52\x65\x73\x70\x6f\x6e\x73\x65\x12\x34\x0a\x06\x73\x65\x72\x69\x65\x73\x18\x01\x20\x03\x28\x0b\x32\x16\x2e\x74\x65\x6d\x70\x6f" +
	"\x70\x62\x2e\x49\x6e\x73\x74\x61\x6e\x74\x53\x65\x72\x69\x65\x73\x42\x04\xf0\xb6\x18\x01\x52\x06\x73\x65\x72\x69\x65\x73\x12\x36\x0a\x07\x6d\x65\x74\x72\x69\x63" +
	"\x73\x18\x02\x20\x01\x28\x0b\x32\x16\x2e\x74\x65\x6d\x70\x6f\x70\x62\x2e\x53\x65\x61\x72\x63\x68\x4d\x65\x74\x72\x69\x63\x73\x42\x04\xf0\xb6\x18\x01\x52\x07\x6d" +
	"\x65\x74\x72\x69\x63\x73\x12\x2e\x0a\x06\x73\x74\x61\x74\x75\x73\x18\x03\x20\x01\x28\x0e\x32\x16\x2e\x74\x65\x6d\x70\x6f\x70\x62\x2e\x50\x61\x72\x74\x69\x61\x6c" +
	"\x53\x74\x61\x74\x75\x73\x52\x06\x73\x74\x61\x74\x75\x73\x12\x18\x0a\x07\x6d\x65\x73\x73\x61\x67\x65\x18\x04\x20\x01\x28\x09\x52\x07\x6d\x65\x73\x73\x61\x67\x65" +
	"\x22\x6d\x0a\x0d\x49\x6e\x73\x74\x61\x6e\x74\x53\x65\x72\x69\x65\x73\x12\x33\x0a\x06\x6c\x61\x62\x65\x6c\x73\x18\x01\x20\x03\x28\x0b\x32\x1b\x2e\x74\x65\x6d\x70" +
	"\x6f\x70\x62\x2e\x63\x6f\x6d\x6d\x6f\x6e\x2e\x76\x31\x2e\x4b\x65\x79\x56\x61\x6c\x75\x65\x52\x06\x6c\x61\x62\x65\x6c\x73\x12\x14\x0a\x05\x76\x61\x6c\x75\x65\x18" +
	"\x02\x20\x01\x28\x01\x52\x05\x76\x61\x6c\x75\x65\x4a\x04\x08\x03\x10\x04\x52\x0b\x70\x72\x6f\x6d\x5f\x6c\x61\x62\x65\x6c\x73\x22\xa5\x04\x0a\x11\x51\x75\x65\x72" +
	"\x79\x52\x61\x6e\x67\x65\x52\x65\x71\x75\x65\x73\x74\x12\x14\x0a\x05\x71\x75\x65\x72\x79\x18\x01\x20\x01\x28\x09\x52\x05\x71\x75\x65\x72\x79\x12\x14\x0a\x05\x73" +
	"\x74\x61\x72\x74\x18\x02\x20\x01\x28\x04\x52\x05\x73\x74\x61\x72\x74\x12\x10\x0a\x03\x65\x6e\x64\x18\x03\x20\x01\x28\x04\x52\x03\x65\x6e\x64\x12\x12\x0a\x04\x73" +
	"\x74\x65\x70\x18\x04\x20\x01\x28\x04\x52\x04\x73\x74\x65\x70\x12\x1c\x0a\x09\x71\x75\x65\x72\x79\x4d\x6f\x64\x65\x18\x07\x20\x01\x28\x09\x52\x09\x71\x75\x65\x72" +
	"\x79\x4d\x6f\x64\x65\x12\x18\x0a\x07\x62\x6c\x6f\x63\x6b\x49\x44\x18\x08\x20\x01\x28\x09\x52\x07\x62\x6c\x6f\x63\x6b\x49\x44\x12\x1c\x0a\x09\x73\x74\x61\x72\x74" +
	"\x50\x61\x67\x65\x18\x09\x20\x01\x28\x0d\x52\x09\x73\x74\x61\x72\x74\x50\x61\x67\x65\x12\x24\x0a\x0d\x70\x61\x67\x65\x73\x54\x6f\x53\x65\x61\x72\x63\x68\x18\x0a" +
	"\x20\x01\x28\x0d\x52\x0d\x70\x61\x67\x65\x73\x54\x6f\x53\x65\x61\x72\x63\x68\x12\x18\x0a\x07\x76\x65\x72\x73\x69\x6f\x6e\x18\x0b\x20\x01\x28\x09\x52\x07\x76\x65" +
	"\x72\x73\x69\x6f\x6e\x12\x1d\x0a\x04\x73\x69\x7a\x65\x18\x0d\x20\x01\x28\x04\x42\x09\x8a\xb7\x18\x05\x53\x69\x7a\x65\x5f\x52\x04\x73\x69\x7a\x65\x12\x1e\x0a\x0a" +
	"\x66\x6f\x6f\x74\x65\x72\x53\x69\x7a\x65\x18\x0e\x20\x01\x28\x0d\x52\x0a\x66\x6f\x6f\x74\x65\x72\x53\x69\x7a\x65\x12\x4a\x0a\x10\x64\x65\x64\x69\x63\x61\x74\x65" +
	"\x64\x43\x6f\x6c\x75\x6d\x6e\x73\x18\x0f\x20\x03\x28\x0b\x32\x18\x2e\x74\x65\x6d\x70\x6f\x70\x62\x2e\x44\x65\x64\x69\x63\x61\x74\x65\x64\x43\x6f\x6c\x75\x6d\x6e" +
	"\x42\x04\xf0\xb6\x18\x01\x52\x10\x64\x65\x64\x69\x63\x61\x74\x65\x64\x43\x6f\x6c\x75\x6d\x6e\x73\x12\x1c\x0a\x09\x65\x78\x65\x6d\x70\x6c\x61\x72\x73\x18\x10\x20" +
	"\x01\x28\x0d\x52\x09\x65\x78\x65\x6d\x70\x6c\x61\x72\x73\x12\x1c\x0a\x09\x6d\x61\x78\x53\x65\x72\x69\x65\x73\x18\x11\x20\x01\x28\x0d\x52\x09\x6d\x61\x78\x53\x65" +
	"\x72\x69\x65\x73\x12\x1d\x0a\x07\x69\x6e\x73\x74\x61\x6e\x74\x18\x12\x20\x01\x28\x08\x48\x00\x52\x07\x69\x6e\x73\x74\x61\x6e\x74\x88\x01\x01\x12\x36\x0a\x16\x73" +
	"\x6b\x69\x70\x41\x53\x54\x54\x72\x61\x6e\x73\x66\x6f\x72\x6d\x61\x74\x69\x6f\x6e\x73\x18\x13\x20\x03\x28\x09\x52\x16\x73\x6b\x69\x70\x41\x53\x54\x54\x72\x61\x6e" +
	"\x73\x66\x6f\x72\x6d\x61\x74\x69\x6f\x6e\x73\x42\x0a\x0a\x08\x5f\x69\x6e\x73\x74\x61\x6e\x74\x22\xc9\x01\x0a\x12\x51\x75\x65\x72\x79\x52\x61\x6e\x67\x65\x52\x65" +
	"\x73\x70\x6f\x6e\x73\x65\x12\x31\x0a\x06\x73\x65\x72\x69\x65\x73\x18\x01\x20\x03\x28\x0b\x32\x13\x2e\x74\x65\x6d\x70\x6f\x70\x62\x2e\x54\x69\x6d\x65\x53\x65\x72" +
	"\x69\x65\x73\x42\x04\xf0\xb6\x18\x01\x52\x06\x73\x65\x72\x69\x65\x73\x12\x36\x0a\x07\x6d\x65\x74\x72\x69\x63\x73\x18\x02\x20\x01\x28\x0b\x32\x16\x2e\x74\x65\x6d" +
	"\x70\x6f\x70\x62\x2e\x53\x65\x61\x72\x63\x68\x4d\x65\x74\x72\x69\x63\x73\x42\x04\xf0\xb6\x18\x01\x52\x07\x6d\x65\x74\x72\x69\x63\x73\x12\x2e\x0a\x06\x73\x74\x61" +
	"\x74\x75\x73\x18\x03\x20\x01\x28\x0e\x32\x16\x2e\x74\x65\x6d\x70\x6f\x70\x62\x2e\x50\x61\x72\x74\x69\x61\x6c\x53\x74\x61\x74\x75\x73\x52\x06\x73\x74\x61\x74\x75" +
	"\x73\x12\x18\x0a\x07\x6d\x65\x73\x73\x61\x67\x65\x18\x04\x20\x01\x28\x09\x52\x07\x6d\x65\x73\x73\x61\x67\x65\x22\x78\x0a\x08\x45\x78\x65\x6d\x70\x6c\x61\x72\x12" +
	"\x33\x0a\x06\x6c\x61\x62\x65\x6c\x73\x18\x01\x20\x03\x28\x0b\x32\x1b\x2e\x74\x65\x6d\x70\x6f\x70\x62\x2e\x63\x6f\x6d\x6d\x6f\x6e\x2e\x76\x31\x2e\x4b\x65\x79\x56" +
	"\x61\x6c\x75\x65\x52\x06\x6c\x61\x62\x65\x6c\x73\x12\x14\x0a\x05\x76\x61\x6c\x75\x65\x18\x02\x20\x01\x28\x01\x52\x05\x76\x61\x6c\x75\x65\x12\x21\x0a\x0c\x74\x69" +
	"\x6d\x65\x73\x74\x61\x6d\x70\x5f\x6d\x73\x18\x03\x20\x01\x28\x03\x52\x0b\x74\x69\x6d\x65\x73\x74\x61\x6d\x70\x4d\x73\x22\x41\x0a\x06\x53\x61\x6d\x70\x6c\x65\x12" +
	"\x21\x0a\x0c\x74\x69\x6d\x65\x73\x74\x61\x6d\x70\x5f\x6d\x73\x18\x02\x20\x01\x28\x03\x52\x0b\x74\x69\x6d\x65\x73\x74\x61\x6d\x70\x4d\x73\x12\x14\x0a\x05\x76\x61" +
	"\x6c\x75\x65\x18\x01\x20\x01\x28\x01\x52\x05\x76\x61\x6c\x75\x65\x22\xb0\x01\x0a\x0a\x54\x69\x6d\x65\x53\x65\x72\x69\x65\x73\x12\x33\x0a\x06\x6c\x61\x62\x65\x6c" +
	"\x73\x18\x01\x20\x03\x28\x0b\x32\x1b\x2e\x74\x65\x6d\x70\x6f\x70\x62\x2e\x63\x6f\x6d\x6d\x6f\x6e\x2e\x76\x31\x2e\x4b\x65\x79\x56\x61\x6c\x75\x65\x52\x06\x6c\x61" +
	"\x62\x65\x6c\x73\x12\x29\x0a\x07\x73\x61\x6d\x70\x6c\x65\x73\x18\x02\x20\x03\x28\x0b\x32\x0f\x2e\x74\x65\x6d\x70\x6f\x70\x62\x2e\x53\x61\x6d\x70\x6c\x65\x52\x07" +
	"\x73\x61\x6d\x70\x6c\x65\x73\x12\x2f\x0a\x09\x65\x78\x65\x6d\x70\x6c\x61\x72\x73\x18\x04\x20\x03\x28\x0b\x32\x11\x2e\x74\x65\x6d\x70\x6f\x70\x62\x2e\x45\x78\x65" +
	"\x6d\x70\x6c\x61\x72\x52\x09\x65\x78\x65\x6d\x70\x6c\x61\x72\x73\x4a\x04\x08\x03\x10\x04\x52\x0b\x70\x72\x6f\x6d\x5f\x6c\x61\x62\x65\x6c\x73\x2a\x5c\x0a\x0f\x50" +
	"\x75\x73\x68\x45\x72\x72\x6f\x72\x52\x65\x61\x73\x6f\x6e\x12\x0c\x0a\x08\x4e\x4f\x5f\x45\x52\x52\x4f\x52\x10\x00\x12\x13\x0a\x0f\x4d\x41\x58\x5f\x4c\x49\x56\x45" +
	"\x5f\x54\x52\x41\x43\x45\x53\x10\x01\x12\x13\x0a\x0f\x54\x52\x41\x43\x45\x5f\x54\x4f\x4f\x5f\x4c\x41\x52\x47\x45\x10\x02\x12\x11\x0a\x0d\x55\x4e\x4b\x4e\x4f\x57" +
	"\x4e\x5f\x45\x52\x52\x4f\x52\x10\x03\x2a\x2a\x0a\x0d\x50\x61\x72\x74\x69\x61\x6c\x53\x74\x61\x74\x75\x73\x12\x0c\x0a\x08\x43\x4f\x4d\x50\x4c\x45\x54\x45\x10\x00" +
	"\x12\x0b\x0a\x07\x50\x41\x52\x54\x49\x41\x4c\x10\x01\x42\x04\xc8\xb7\x18\x01\x62\x06\x70\x72\x6f\x74\x6f\x33"

var file_tempopb_tempo_proto_fd protoreflect.FileDescriptor

var file_tempopb_tempo_proto_msgTypes = make([]protoimpl.MessageInfo, 39)
var file_tempopb_tempo_proto_enumTypes = make([]protoimpl.EnumInfo, 5)

var file_tempopb_tempo_proto_goTypes = []any{
	(PushErrorReason)(0),                // 0: tempopb.PushErrorReason
	(PartialStatus)(0),                  // 1: tempopb.PartialStatus
	(DedicatedColumn_Scope)(0),          // 2: tempopb.DedicatedColumn.Scope
	(DedicatedColumn_Type)(0),           // 3: tempopb.DedicatedColumn.Type
	(DedicatedColumn_Option)(0),         // 4: tempopb.DedicatedColumn.Option
	(*TraceByIDRequest)(nil),            // 5: tempopb.TraceByIDRequest
	(*TraceByIDResponse)(nil),           // 6: tempopb.TraceByIDResponse
	(*TraceByIDMetrics)(nil),            // 7: tempopb.TraceByIDMetrics
	(*SearchRequest)(nil),               // 8: tempopb.SearchRequest
	(*SearchBlockRequest)(nil),          // 9: tempopb.SearchBlockRequest
	(*DedicatedColumn)(nil),             // 10: tempopb.DedicatedColumn
	(*SearchResponse)(nil),              // 11: tempopb.SearchResponse
	(*TraceSearchMetadata)(nil),         // 12: tempopb.TraceSearchMetadata
	(*ServiceStats)(nil),                // 13: tempopb.ServiceStats
	(*SpanSet)(nil),                     // 14: tempopb.SpanSet
	(*Span)(nil),                        // 15: tempopb.Span
	(*SearchMetrics)(nil),               // 16: tempopb.SearchMetrics
	(*SearchTagsRequest)(nil),           // 17: tempopb.SearchTagsRequest
	(*SearchTagsBlockRequest)(nil),      // 18: tempopb.SearchTagsBlockRequest
	(*SearchTagValuesBlockRequest)(nil), // 19: tempopb.SearchTagValuesBlockRequest
	(*SearchTagsResponse)(nil),          // 20: tempopb.SearchTagsResponse
	(*SearchTagsV2Response)(nil),        // 21: tempopb.SearchTagsV2Response
	(*SearchTagsV2Scope)(nil),           // 22: tempopb.SearchTagsV2Scope
	(*SearchTagValuesRequest)(nil),      // 23: tempopb.SearchTagValuesRequest
	(*SearchTagValuesResponse)(nil),     // 24: tempopb.SearchTagValuesResponse
	(*TagValue)(nil),                    // 25: tempopb.TagValue
	(*SearchTagValuesV2Response)(nil),   // 26: tempopb.SearchTagValuesV2Response
	(*MetadataMetrics)(nil),             // 27: tempopb.MetadataMetrics
	(*Trace)(nil),                       // 28: tempopb.Trace
	(*PushResponse)(nil),                // 29: tempopb.PushResponse
	(*PushBytesRequest)(nil),            // 30: tempopb.PushBytesRequest
	(*PushSpansRequest)(nil),            // 31: tempopb.PushSpansRequest
	(*TraceBytes)(nil),                  // 32: tempopb.TraceBytes
	(*LinkSlice)(nil),                   // 33: tempopb.LinkSlice
	(*QueryInstantRequest)(nil),         // 34: tempopb.QueryInstantRequest
	(*QueryInstantResponse)(nil),        // 35: tempopb.QueryInstantResponse
	(*InstantSeries)(nil),               // 36: tempopb.InstantSeries
	(*QueryRangeRequest)(nil),           // 37: tempopb.QueryRangeRequest
	(*QueryRangeResponse)(nil),          // 38: tempopb.QueryRangeResponse
	(*Exemplar)(nil),                    // 39: tempopb.Exemplar
	(*Sample)(nil),                      // 40: tempopb.Sample
	(*TimeSeries)(nil),                  // 41: tempopb.TimeSeries
	nil,                                 // 42: tempopb.SearchRequest.TagsEntry
	nil,                                 // 43: tempopb.TraceSearchMetadata.ServiceStatsEntry
	(*timestamppb.Timestamp)(nil),       // 44: google.protobuf.Timestamp
	(*v1.KeyValue)(nil),                 // 45: tempopb.common.v1.KeyValue
	(*tracev1.ResourceSpans)(nil),       // 46: tempopb.trace.v1.ResourceSpans
	(*tracev1.Span_Link)(nil),           // 47: tempopb.trace.v1.Span.Link
}

var file_tempopb_tempo_proto_depIdxs = []int32{
	44, // 0: tempopb.TraceByIDRequest.RF1After:type_name -> google.protobuf.Timestamp
	28, // 1: tempopb.TraceByIDResponse.trace:type_name -> tempopb.Trace
	7,  // 2: tempopb.TraceByIDResponse.metrics:type_name -> tempopb.TraceByIDMetrics
	1,  // 3: tempopb.TraceByIDResponse.status:type_name -> tempopb.PartialStatus
	42, // 4: tempopb.SearchRequest.Tags:type_name -> tempopb.SearchRequest.TagsEntry
	44, // 5: tempopb.SearchRequest.RF1After:type_name -> google.protobuf.Timestamp
	8,  // 6: tempopb.SearchBlockRequest.searchReq:type_name -> tempopb.SearchRequest
	10, // 7: tempopb.SearchBlockRequest.dedicatedColumns:type_name -> tempopb.DedicatedColumn
	2,  // 8: tempopb.DedicatedColumn.scope:type_name -> tempopb.DedicatedColumn.Scope
	3,  // 9: tempopb.DedicatedColumn.type:type_name -> tempopb.DedicatedColumn.Type
	4,  // 10: tempopb.DedicatedColumn.options:type_name -> tempopb.DedicatedColumn.Option
	12, // 11: tempopb.SearchResponse.traces:type_name -> tempopb.TraceSearchMetadata
	16, // 12: tempopb.SearchResponse.metrics:type_name -> tempopb.SearchMetrics
	14, // 13: tempopb.TraceSearchMetadata.spanSet:type_name -> tempopb.SpanSet
	14, // 14: tempopb.TraceSearchMetadata.spanSets:type_name -> tempopb.SpanSet
	43, // 15: tempopb.TraceSearchMetadata.serviceStats:type_name -> tempopb.TraceSearchMetadata.ServiceStatsEntry
	15, // 16: tempopb.SpanSet.spans:type_name -> tempopb.Span
	45, // 17: tempopb.SpanSet.attributes:type_name -> tempopb.common.v1.KeyValue
	45, // 18: tempopb.Span.attributes:type_name -> tempopb.common.v1.KeyValue
	44, // 19: tempopb.SearchTagsRequest.RF1After:type_name -> google.protobuf.Timestamp
	17, // 20: tempopb.SearchTagsBlockRequest.searchReq:type_name -> tempopb.SearchTagsRequest
	10, // 21: tempopb.SearchTagsBlockRequest.dedicatedColumns:type_name -> tempopb.DedicatedColumn
	23, // 22: tempopb.SearchTagValuesBlockRequest.searchReq:type_name -> tempopb.SearchTagValuesRequest
	10, // 23: tempopb.SearchTagValuesBlockRequest.dedicatedColumns:type_name -> tempopb.DedicatedColumn
	27, // 24: tempopb.SearchTagsResponse.metrics:type_name -> tempopb.MetadataMetrics
	22, // 25: tempopb.SearchTagsV2Response.scopes:type_name -> tempopb.SearchTagsV2Scope
	27, // 26: tempopb.SearchTagsV2Response.metrics:type_name -> tempopb.MetadataMetrics
	44, // 27: tempopb.SearchTagValuesRequest.RF1After:type_name -> google.protobuf.Timestamp
	27, // 28: tempopb.SearchTagValuesResponse.metrics:type_name -> tempopb.MetadataMetrics
	25, // 29: tempopb.SearchTagValuesV2Response.tagValues:type_name -> tempopb.TagValue
	27, // 30: tempopb.SearchTagValuesV2Response.metrics:type_name -> tempopb.MetadataMetrics
	46, // 31: tempopb.Trace.resourceSpans:type_name -> tempopb.trace.v1.ResourceSpans
	0,  // 32: tempopb.PushResponse.errorsByTrace:type_name -> tempopb.PushErrorReason
	46, // 33: tempopb.PushSpansRequest.batches:type_name -> tempopb.trace.v1.ResourceSpans
	47, // 34: tempopb.LinkSlice.links:type_name -> tempopb.trace.v1.Span.Link
	36, // 35: tempopb.QueryInstantResponse.series:type_name -> tempopb.InstantSeries
	16, // 36: tempopb.QueryInstantResponse.metrics:type_name -> tempopb.SearchMetrics
	1,  // 37: tempopb.QueryInstantResponse.status:type_name -> tempopb.PartialStatus
	45, // 38: tempopb.InstantSeries.labels:type_name -> tempopb.common.v1.KeyValue
	10, // 39: tempopb.QueryRangeRequest.dedicatedColumns:type_name -> tempopb.DedicatedColumn
	41, // 40: tempopb.QueryRangeResponse.series:type_name -> tempopb.TimeSeries
	16, // 41: tempopb.QueryRangeResponse.metrics:type_name -> tempopb.SearchMetrics
	1,  // 42: tempopb.QueryRangeResponse.status:type_name -> tempopb.PartialStatus
	45, // 43: tempopb.Exemplar.labels:type_name -> tempopb.common.v1.KeyValue
	45, // 44: tempopb.TimeSeries.labels:type_name -> tempopb.common.v1.KeyValue
	40, // 45: tempopb.TimeSeries.samples:type_name -> tempopb.Sample
	39, // 46: tempopb.TimeSeries.exemplars:type_name -> tempopb.Exemplar
	13, // 47: tempopb.TraceSearchMetadata.ServiceStatsEntry.value:type_name -> tempopb.ServiceStats
	48, // [48:48] is the sub-list for method output_type
	48, // [48:48] is the sub-list for method input_type
	48, // [48:48] is the sub-list for extension type_name
	48, // [48:48] is the sub-list for extension extendee
	0,  // [0:48] is the sub-list for field type_name
}

func init() { file_tempopb_tempo_proto_init() }

func file_tempopb_tempo_proto_init() {
	if file_tempopb_tempo_proto_fd != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tempopb_tempo_proto_rawDesc), len(file_tempopb_tempo_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   39,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tempopb_tempo_proto_goTypes,
		DependencyIndexes: file_tempopb_tempo_proto_depIdxs,
		EnumInfos:         file_tempopb_tempo_proto_enumTypes,
		MessageInfos:      file_tempopb_tempo_proto_msgTypes,
	}.Build()
	file_tempopb_tempo_proto_fd = out.File
	file_tempopb_tempo_proto_goTypes = nil
	file_tempopb_tempo_proto_depIdxs = nil
}
