apiVersion: v1
data:
  overrides.yaml: |
    overrides:
        super_user:
            global:
                max_bytes_per_trace: 3e+07
            ingestion:
                burst_size_bytes: 2e+07
                max_traces_per_user: 100000
                rate_limit_bytes: 2e+07
kind: ConfigMap
metadata:
  name: tempo-overrides
  namespace: tracing
