// Code generated by goyacc -o expr.y.go expr.y. DO NOT EDIT.

//line expr.y:2
package traceql

import __yyfmt__ "fmt"

//line expr.y:2

import (
	"time"
)

//line expr.y:11
type yySymType struct {
	yys               int
	root              RootExpr
	groupOperation    GroupOperation
	coalesceOperation CoalesceOperation

	spansetExpression      SpansetExpression
	wrappedSpansetPipeline Pipeline
	spansetPipeline        Pipeline
	spansetFilter          SpansetFilter
	scalarFilter           ScalarFilter
	scalarFilterOperation  int

	scalarExpression      ScalarExpression
	wrappedScalarPipeline Pipeline
	scalarPipeline        Pipeline
	aggregate             Aggregate

	fieldExpression FieldExpression
	static          Static
	spanField       Static

	binOp          int
	staticInt      int
	staticStr      string
	staticFloat    float64
	staticDuration time.Duration
}

const IDENTIFIER = 57346
const STRING = 57347
const INTEGER = 57348
const FLOAT = 57349
const DURATION = 57350
const DOT = 57351
const OPEN_BRACE = 57352
const CLOSE_BRACE = 57353
const OPEN_PARENS = 57354
const CLOSE_PARENS = 57355
const NIL = 57356
const TRUE = 57357
const FALSE = 57358
const STATUS_ERROR = 57359
const STATUS_OK = 57360
const STATUS_UNSET = 57361
const COUNT = 57362
const AVG = 57363
const MAX = 57364
const MIN = 57365
const SUM = 57366
const BY = 57367
const COALESCE = 57368
const PIPE = 57369
const EQ = 57370
const NEQ = 57371
const LT = 57372
const LTE = 57373
const GT = 57374
const GTE = 57375
const NRE = 57376
const RE = 57377
const DESC = 57378
const TILDE = 57379
const AND = 57380
const OR = 57381
const NOT = 57382
const ADD = 57383
const SUB = 57384
const MUL = 57385
const DIV = 57386
const MOD = 57387
const POW = 57388

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"IDENTIFIER",
	"STRING",
	"INTEGER",
	"FLOAT",
	"DURATION",
	"DOT",
	"OPEN_BRACE",
	"CLOSE_BRACE",
	"OPEN_PARENS",
	"CLOSE_PARENS",
	"NIL",
	"TRUE",
	"FALSE",
	"STATUS_ERROR",
	"STATUS_OK",
	"STATUS_UNSET",
	"COUNT",
	"AVG",
	"MAX",
	"MIN",
	"SUM",
	"BY",
	"COALESCE",
	"PIPE",
	"EQ",
	"NEQ",
	"LT",
	"LTE",
	"GT",
	"GTE",
	"NRE",
	"RE",
	"DESC",
	"TILDE",
	"AND",
	"OR",
	"NOT",
	"ADD",
	"SUB",
	"MUL",
	"DIV",
	"MOD",
	"POW",
}
var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line yacctab:1
var yyExca = [...]int{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 438

var yyAct = [...]int{

	56, 3, 9, 2, 98, 99, 100, 109, 36, 38,
	37, 4, 47, 48, 49, 50, 51, 52, 96, 97,
	98, 99, 100, 109, 109, 41, 42, 43, 44, 45,
	46, 5, 69, 73, 75, 76, 77, 78, 43, 44,
	45, 46, 68, 84, 87, 88, 89, 90, 91, 92,
	60, 10, 46, 31, 34, 94, 93, 10, 112, 113,
	114, 80, 70, 80, 81, 117, 118, 119, 120, 41,
	42, 43, 44, 45, 46, 30, 36, 81, 122, 30,
	148, 10, 116, 69, 123, 83, 121, 67, 115, 38,
	124, 85, 12, 68, 74, 66, 65, 126, 127, 128,
	129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
	139, 140, 141, 70, 110, 111, 64, 96, 97, 98,
	99, 100, 109, 147, 32, 10, 63, 54, 33, 35,
	31, 34, 10, 143, 61, 14, 40, 10, 101, 102,
	103, 104, 105, 106, 108, 107, 146, 53, 110, 111,
	39, 96, 97, 98, 99, 100, 109, 13, 8, 7,
	71, 101, 102, 103, 104, 105, 106, 108, 107, 145,
	1, 110, 111, 0, 96, 97, 98, 99, 100, 109,
	0, 0, 0, 0, 101, 102, 103, 104, 105, 106,
	108, 107, 144, 0, 110, 111, 0, 96, 97, 98,
	99, 100, 109, 0, 0, 0, 0, 101, 102, 103,
	104, 105, 106, 108, 107, 142, 0, 110, 111, 0,
	96, 97, 98, 99, 100, 109, 0, 0, 0, 0,
	101, 102, 103, 104, 105, 106, 108, 107, 125, 0,
	110, 111, 0, 96, 97, 98, 99, 100, 109, 0,
	0, 0, 0, 101, 102, 103, 104, 105, 106, 108,
	107, 95, 0, 110, 111, 0, 96, 97, 98, 99,
	100, 109, 47, 48, 49, 50, 51, 52, 101, 102,
	103, 104, 105, 106, 108, 107, 82, 0, 110, 111,
	0, 96, 97, 98, 99, 100, 109, 0, 0, 86,
	0, 47, 48, 49, 50, 51, 52, 25, 28, 26,
	27, 29, 0, 0, 41, 42, 43, 44, 45, 46,
	62, 15, 16, 17, 21, 0, 0, 55, 57, 0,
	20, 18, 19, 23, 22, 24, 62, 15, 16, 17,
	21, 0, 0, 0, 57, 0, 20, 18, 19, 23,
	22, 24, 0, 0, 0, 0, 59, 0, 58, 0,
	0, 0, 0, 0, 0, 0, 15, 16, 17, 21,
	79, 12, 59, 6, 58, 20, 18, 19, 23, 22,
	24, 25, 28, 26, 27, 29, 11, 72, 0, 32,
	0, 0, 0, 33, 35, 31, 34, 15, 16, 17,
	21, 0, 12, 0, 6, 0, 20, 18, 19, 23,
	22, 24, 25, 28, 26, 27, 29, 11, 15, 16,
	17, 21, 0, 0, 0, 86, 0, 20, 18, 19,
	23, 22, 24, 25, 28, 26, 27, 29,
}
var yyPact = [...]int{

	392, -1000, 52, 92, -1000, -1000, 392, -1000, -1000, -16,
	244, 115, 316, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, 114, 104, 84, 83, 75,
	361, 82, 82, 82, 82, 82, 357, 50, 273, 72,
	413, 287, 287, 287, 287, 287, 287, -1000, -1000, -1000,
	-1000, -1000, -1000, 287, 332, -1000, 250, 332, 332, 332,
	-1000, 79, -1000, 69, 332, 332, 332, 332, -1000, 92,
	-1000, -1000, 74, -1000, 392, 15, 15, -1000, 15, -1000,
	-1000, 361, -1000, -1000, 28, -1000, 392, -5, -5, 6,
	6, 6, 6, 28, 225, -1000, 332, 332, 332, 332,
	332, 332, 332, 332, 332, 332, 332, 332, 332, 332,
	332, 332, 202, -39, -23, 129, -1000, 179, 156, 133,
	110, 67, 48, -16, 37, -1000, -39, -39, -22, -22,
	-22, 76, 76, 76, 76, 76, 76, 76, 76, -22,
	-23, -23, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
}
var yyPgo = [...]int{

	0, 170, 31, 160, 1, 159, 3, 158, 11, 136,
	2, 157, 150, 135, 0, 50, 134,
}
var yyR1 = [...]int{

	0, 1, 2, 3, 4, 4, 4, 4, 4, 4,
	4, 4, 5, 6, 6, 6, 6, 6, 6, 6,
	7, 7, 8, 8, 8, 9, 9, 9, 9, 9,
	9, 10, 10, 10, 10, 10, 10, 10, 10, 10,
	11, 12, 13, 13, 13, 13, 13, 14, 14, 14,
	14, 14, 14, 14, 14, 14, 14, 14, 14, 14,
	14, 14, 14, 14, 14, 14, 14, 14, 15, 15,
	15, 15, 15, 15, 15, 15, 15, 15, 16, 16,
}
var yyR2 = [...]int{

	0, 1, 4, 3, 3, 3, 3, 3, 3, 3,
	1, 1, 3, 1, 1, 1, 3, 3, 3, 3,
	2, 3, 3, 3, 3, 1, 1, 1, 1, 1,
	1, 3, 3, 3, 3, 3, 3, 3, 1, 1,
	3, 3, 3, 4, 4, 4, 4, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 2, 2, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 3,
}
var yyChk = [...]int{

	-1000, -1, -6, -4, -8, -2, 12, -5, -7, -10,
	-15, 25, 10, -11, -13, 5, 6, 7, 15, 16,
	14, 8, 18, 17, 19, 20, 22, 23, 21, 24,
	27, 38, 32, 36, 39, 37, -4, -6, -10, -12,
	-9, 41, 42, 43, 44, 45, 46, 28, 29, 30,
	31, 32, 33, -9, 12, 11, -14, 12, 42, 40,
	-15, -16, 4, 12, 12, 12, 12, 12, -8, -4,
	-2, -3, 26, -4, 12, -4, -4, -4, -4, 13,
	13, 27, 13, 13, -10, -15, 12, -10, -10, -10,
	-10, -10, -10, -10, -14, 11, 41, 42, 43, 44,
	45, 28, 29, 30, 31, 32, 33, 35, 34, 46,
	38, 39, -14, -14, -14, 9, 13, -14, -14, -14,
	-14, 12, -6, -10, -6, 13, -14, -14, -14, -14,
	-14, -14, -14, -14, -14, -14, -14, -14, -14, -14,
	-14, -14, 13, 4, 13, 13, 13, 13, 13,
}
var yyDef = [...]int{

	0, -2, 1, 13, 14, 15, 0, 10, 11, 0,
	0, 0, 0, 38, 39, 68, 69, 70, 71, 72,
	73, 74, 75, 76, 77, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 13, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 25, 26, 27,
	28, 29, 30, 0, 0, 20, 0, 0, 0, 0,
	66, 67, 78, 0, 0, 0, 0, 0, 16, 17,
	18, 19, 0, 5, 0, 6, 7, 8, 9, 4,
	12, 0, 31, 40, 22, 24, 0, 32, 33, 34,
	35, 36, 37, 23, 0, 21, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 64, 65, 0, 42, 0, 0, 0,
	0, 0, 0, 41, 0, 2, 48, 49, 50, 51,
	52, 53, 54, 55, 56, 57, 58, 59, 60, 61,
	62, 63, 47, 79, 43, 44, 45, 46, 3,
}
var yyTok1 = [...]int{

	1,
}
var yyTok2 = [...]int{

	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46,
}
var yyTok3 = [...]int{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := yyPact[state]
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && yyChk[yyAct[n]] == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || yyExca[i+1] != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := yyExca[i]
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = yyTok1[0]
		goto out
	}
	if char < len(yyTok1) {
		token = yyTok1[char]
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = yyTok2[char-yyPrivate]
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = yyTok3[i+0]
		if token == char {
			token = yyTok3[i+1]
			goto out
		}
	}

out:
	if token == 0 {
		token = yyTok2[1] /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = yyPact[yystate]
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = yyAct[yyn]
	if yyChk[yyn] == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = yyDef[yystate]
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && yyExca[xi+1] == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = yyExca[xi+0]
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = yyExca[xi+1]
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = yyPact[yyS[yyp].yys] + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = yyAct[yyn] /* simulate a shift of "error" */
					if yyChk[yystate] == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= yyR2[yyn]
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = yyR1[yyn]
	yyg := yyPgo[yyn]
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = yyAct[yyg]
	} else {
		yystate = yyAct[yyj]
		if yyChk[yystate] != -yyn {
			yystate = yyAct[yyg]
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:81
		{
			yylex.(*lexer).expr = newRootExpr(yyDollar[1].spansetPipeline)
		}
	case 2:
		yyDollar = yyS[yypt-4 : yypt+1]
//line expr.y:85
		{
			yyVAL.groupOperation = newGroupOperation(yyDollar[3].fieldExpression)
		}
	case 3:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:89
		{
			yyVAL.coalesceOperation = newCoalesceOperation()
		}
	case 4:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:96
		{
			yyVAL.spansetExpression = yyDollar[2].spansetExpression
		}
	case 5:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:97
		{
			yyVAL.spansetExpression = newSpansetOperation(opSpansetAnd, yyDollar[1].spansetExpression, yyDollar[3].spansetExpression)
		}
	case 6:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:98
		{
			yyVAL.spansetExpression = newSpansetOperation(opSpansetChild, yyDollar[1].spansetExpression, yyDollar[3].spansetExpression)
		}
	case 7:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:99
		{
			yyVAL.spansetExpression = newSpansetOperation(opSpansetDescendant, yyDollar[1].spansetExpression, yyDollar[3].spansetExpression)
		}
	case 8:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:100
		{
			yyVAL.spansetExpression = newSpansetOperation(opSpansetUnion, yyDollar[1].spansetExpression, yyDollar[3].spansetExpression)
		}
	case 9:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:101
		{
			yyVAL.spansetExpression = newSpansetOperation(opSpansetSibling, yyDollar[1].spansetExpression, yyDollar[3].spansetExpression)
		}
	case 10:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:102
		{
			yyVAL.spansetExpression = yyDollar[1].wrappedSpansetPipeline
		}
	case 11:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:103
		{
			yyVAL.spansetExpression = yyDollar[1].spansetFilter
		}
	case 12:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:107
		{
			yyVAL.wrappedSpansetPipeline = yyDollar[2].spansetPipeline
		}
	case 13:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:110
		{
			yyVAL.spansetPipeline = newPipeline(yyDollar[1].spansetExpression)
		}
	case 14:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:111
		{
			yyVAL.spansetPipeline = newPipeline(yyDollar[1].scalarFilter)
		}
	case 15:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:112
		{
			yyVAL.spansetPipeline = newPipeline(yyDollar[1].groupOperation)
		}
	case 16:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:113
		{
			yyVAL.spansetPipeline = yyDollar[1].spansetPipeline.addItem(yyDollar[3].scalarFilter)
		}
	case 17:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:114
		{
			yyVAL.spansetPipeline = yyDollar[1].spansetPipeline.addItem(yyDollar[3].spansetExpression)
		}
	case 18:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:115
		{
			yyVAL.spansetPipeline = yyDollar[1].spansetPipeline.addItem(yyDollar[3].groupOperation)
		}
	case 19:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:116
		{
			yyVAL.spansetPipeline = yyDollar[1].spansetPipeline.addItem(yyDollar[3].coalesceOperation)
		}
	case 20:
		yyDollar = yyS[yypt-2 : yypt+1]
//line expr.y:120
		{
			yyVAL.spansetFilter = newSpansetFilter(newStaticBool(true))
		}
	case 21:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:121
		{
			yyVAL.spansetFilter = newSpansetFilter(yyDollar[2].fieldExpression)
		}
	case 22:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:125
		{
			yyVAL.scalarFilter = newScalarFilter(yyDollar[2].scalarFilterOperation, yyDollar[1].scalarExpression, yyDollar[3].scalarExpression)
		}
	case 23:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:126
		{
			yyVAL.scalarFilter = newScalarFilter(yyDollar[2].scalarFilterOperation, yyDollar[1].static, yyDollar[3].scalarExpression)
		}
	case 24:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:127
		{
			yyVAL.scalarFilter = newScalarFilter(yyDollar[2].scalarFilterOperation, yyDollar[1].scalarExpression, yyDollar[3].static)
		}
	case 25:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:131
		{
			yyVAL.scalarFilterOperation = opEqual
		}
	case 26:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:132
		{
			yyVAL.scalarFilterOperation = opNotEqual
		}
	case 27:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:133
		{
			yyVAL.scalarFilterOperation = opLess
		}
	case 28:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:134
		{
			yyVAL.scalarFilterOperation = opLessEqual
		}
	case 29:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:135
		{
			yyVAL.scalarFilterOperation = opGreater
		}
	case 30:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:136
		{
			yyVAL.scalarFilterOperation = opGreaterEqual
		}
	case 31:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:143
		{
			yyVAL.scalarExpression = yyDollar[2].scalarExpression
		}
	case 32:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:144
		{
			yyVAL.scalarExpression = newScalarOperation(opAdd, yyDollar[1].scalarExpression, yyDollar[3].scalarExpression)
		}
	case 33:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:145
		{
			yyVAL.scalarExpression = newScalarOperation(opSub, yyDollar[1].scalarExpression, yyDollar[3].scalarExpression)
		}
	case 34:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:146
		{
			yyVAL.scalarExpression = newScalarOperation(opMult, yyDollar[1].scalarExpression, yyDollar[3].scalarExpression)
		}
	case 35:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:147
		{
			yyVAL.scalarExpression = newScalarOperation(opDiv, yyDollar[1].scalarExpression, yyDollar[3].scalarExpression)
		}
	case 36:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:148
		{
			yyVAL.scalarExpression = newScalarOperation(opMod, yyDollar[1].scalarExpression, yyDollar[3].scalarExpression)
		}
	case 37:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:149
		{
			yyVAL.scalarExpression = newScalarOperation(opPower, yyDollar[1].scalarExpression, yyDollar[3].scalarExpression)
		}
	case 38:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:150
		{
			yyVAL.scalarExpression = yyDollar[1].wrappedScalarPipeline
		}
	case 39:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:151
		{
			yyVAL.scalarExpression = yyDollar[1].aggregate
		}
	case 40:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:155
		{
			yyVAL.wrappedScalarPipeline = yyDollar[2].scalarPipeline
		}
	case 41:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:159
		{
			yyVAL.scalarPipeline = yyDollar[1].spansetPipeline.addItem(yyDollar[3].scalarExpression)
		}
	case 42:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:163
		{
			yyVAL.aggregate = newAggregate(aggregateCount, nil)
		}
	case 43:
		yyDollar = yyS[yypt-4 : yypt+1]
//line expr.y:164
		{
			yyVAL.aggregate = newAggregate(aggregateMax, yyDollar[3].fieldExpression)
		}
	case 44:
		yyDollar = yyS[yypt-4 : yypt+1]
//line expr.y:165
		{
			yyVAL.aggregate = newAggregate(aggregateMin, yyDollar[3].fieldExpression)
		}
	case 45:
		yyDollar = yyS[yypt-4 : yypt+1]
//line expr.y:166
		{
			yyVAL.aggregate = newAggregate(aggregateAvg, yyDollar[3].fieldExpression)
		}
	case 46:
		yyDollar = yyS[yypt-4 : yypt+1]
//line expr.y:167
		{
			yyVAL.aggregate = newAggregate(aggregateSum, yyDollar[3].fieldExpression)
		}
	case 47:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:174
		{
			yyVAL.fieldExpression = yyDollar[2].fieldExpression
		}
	case 48:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:175
		{
			yyVAL.fieldExpression = newBinaryOperation(opAdd, yyDollar[1].fieldExpression, yyDollar[3].fieldExpression)
		}
	case 49:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:176
		{
			yyVAL.fieldExpression = newBinaryOperation(opSub, yyDollar[1].fieldExpression, yyDollar[3].fieldExpression)
		}
	case 50:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:177
		{
			yyVAL.fieldExpression = newBinaryOperation(opMult, yyDollar[1].fieldExpression, yyDollar[3].fieldExpression)
		}
	case 51:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:178
		{
			yyVAL.fieldExpression = newBinaryOperation(opDiv, yyDollar[1].fieldExpression, yyDollar[3].fieldExpression)
		}
	case 52:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:179
		{
			yyVAL.fieldExpression = newBinaryOperation(opMod, yyDollar[1].fieldExpression, yyDollar[3].fieldExpression)
		}
	case 53:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:180
		{
			yyVAL.fieldExpression = newBinaryOperation(opEqual, yyDollar[1].fieldExpression, yyDollar[3].fieldExpression)
		}
	case 54:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:181
		{
			yyVAL.fieldExpression = newBinaryOperation(opNotEqual, yyDollar[1].fieldExpression, yyDollar[3].fieldExpression)
		}
	case 55:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:182
		{
			yyVAL.fieldExpression = newBinaryOperation(opLess, yyDollar[1].fieldExpression, yyDollar[3].fieldExpression)
		}
	case 56:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:183
		{
			yyVAL.fieldExpression = newBinaryOperation(opLessEqual, yyDollar[1].fieldExpression, yyDollar[3].fieldExpression)
		}
	case 57:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:184
		{
			yyVAL.fieldExpression = newBinaryOperation(opGreater, yyDollar[1].fieldExpression, yyDollar[3].fieldExpression)
		}
	case 58:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:185
		{
			yyVAL.fieldExpression = newBinaryOperation(opGreaterEqual, yyDollar[1].fieldExpression, yyDollar[3].fieldExpression)
		}
	case 59:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:186
		{
			yyVAL.fieldExpression = newBinaryOperation(opRegex, yyDollar[1].fieldExpression, yyDollar[3].fieldExpression)
		}
	case 60:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:187
		{
			yyVAL.fieldExpression = newBinaryOperation(opNotRegex, yyDollar[1].fieldExpression, yyDollar[3].fieldExpression)
		}
	case 61:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:188
		{
			yyVAL.fieldExpression = newBinaryOperation(opPower, yyDollar[1].fieldExpression, yyDollar[3].fieldExpression)
		}
	case 62:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:189
		{
			yyVAL.fieldExpression = newBinaryOperation(opAnd, yyDollar[1].fieldExpression, yyDollar[3].fieldExpression)
		}
	case 63:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:190
		{
			yyVAL.fieldExpression = newBinaryOperation(opOr, yyDollar[1].fieldExpression, yyDollar[3].fieldExpression)
		}
	case 64:
		yyDollar = yyS[yypt-2 : yypt+1]
//line expr.y:191
		{
			yyVAL.fieldExpression = newUnaryOperation(opSub, yyDollar[2].fieldExpression)
		}
	case 65:
		yyDollar = yyS[yypt-2 : yypt+1]
//line expr.y:192
		{
			yyVAL.fieldExpression = newUnaryOperation(opNot, yyDollar[2].fieldExpression)
		}
	case 66:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:193
		{
			yyVAL.fieldExpression = yyDollar[1].static
		}
	case 67:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:194
		{
			yyVAL.fieldExpression = yyDollar[1].spanField
		}
	case 68:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:201
		{
			yyVAL.static = newStaticString(yyDollar[1].staticStr)
		}
	case 69:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:202
		{
			yyVAL.static = newStaticInt(yyDollar[1].staticInt)
		}
	case 70:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:203
		{
			yyVAL.static = newStaticFloat(yyDollar[1].staticFloat)
		}
	case 71:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:204
		{
			yyVAL.static = newStaticBool(true)
		}
	case 72:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:205
		{
			yyVAL.static = newStaticBool(false)
		}
	case 73:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:206
		{
			yyVAL.static = newStaticNil()
		}
	case 74:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:207
		{
			yyVAL.static = newStaticDuration(yyDollar[1].staticDuration)
		}
	case 75:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:208
		{
			yyVAL.static = newStaticStatus(statusOk)
		}
	case 76:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:209
		{
			yyVAL.static = newStaticStatus(statusError)
		}
	case 77:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:210
		{
			yyVAL.static = newStaticStatus(statusUnset)
		}
	case 78:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:214
		{
			yyVAL.spanField = newStaticIdentifier(yyDollar[1].staticStr)
		}
	case 79:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:215
		{
			yyVAL.spanField = newNamespacedIdentifier(yyDollar[1].spanField, yyDollar[3].staticStr)
		}
	}
	goto yystack /* stack new state and value */
}
