#!/usr/bin/env sh

set -o errexit
set -o nounset
#set -o pipefail

if [ "$1" = "" ]
then
  echo "Usage: $0 architecture postfix required"
  exit 1
fi

SHA="$(git rev-parse --short HEAD)-$1,latest-$1"

# If tag, use tag
TAG=$( (git describe --exact-match 2> /dev/null || echo "") | sed 's/v//g')
if [ -z "$TAG" ]
then
      echo ${SHA}
else
      echo ${TAG}-$1
fi
