stream_over_http_enabled: true
multitenancy_enabled: true

server:
  http_listen_port: 3200
  log_level: info

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: "tempo:4317"
        http:
          endpoint: "tempo:4318"
#  log_received_spans:
#    enabled: true
#  log_discarded_spans:
#    enabled: true
query_frontend:
  mcp_server:
    enabled: true

storage:
  trace:
    backend: local                     # backend configuration to use
    wal:
      path: /var/tempo/wal             # where to store the wal locally
    local:
      path: /var/tempo/blocks


usage_report:
  reporting_enabled: false
