services:
  tempo:
    image: grafana/tempo-debug:latest
    command: [ "-target=all", "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
      - tempo-data:/var/tempo
    environment:
      - DEBUG_BLOCK=0
    ports:
      - "3200:3200" # tempo
      - "4317:4317" # otlp grpc
      - "2345:2345" # delve debug server

  k6-tracing:
    image: ghcr.io/grafana/xk6-client-tracing:v0.0.9
    environment:
      - ENDPOINT=tempo:4317
    restart: always
    depends_on:
      - tempo

  prometheus:
    image: prom/prometheus:latest
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
      - --enable-feature=native-histograms
    volumes:
      - ./prometheus.yaml:/etc/prometheus.yaml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:13.0.1@sha256:0f86bada30d65ef9d0183b90c1e2682ac92d53d95da8bed322b984ea78a4a73a
    volumes:
      - ./grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor
    ports:
      - "3000:3000"
     
  vulture:
    image: grafana/tempo-vulture:latest
    restart: always
    command:
      [
        "-prometheus-listen-address=:8080",
        "-tempo-query-url=http://tempo:3200",
        "-tempo-push-url=http://tempo:4317",
      ]
    depends_on:
      - tempo

volumes:
  tempo-data:
