apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
    jsonData:
      httpMethod: GET

  - name: Tempo 2.x
    type: tempo
    uid: tempo-v2
    access: proxy
    orgId: 1
    url: http://tempo-v2-query-frontend:3200
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
    apiVersion: 1
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: prometheus

  - name: Tempo 3.0
    type: tempo
    uid: tempo-v3
    access: proxy
    orgId: 1
    url: http://tempo-v3-query-frontend:3200
    basicAuth: false
    isDefault: true
    version: 1
    editable: false
    apiVersion: 1
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: prometheus
      streamingEnabled:
        search: true
        metrics: true
