package secrets

import "strings"

// Candidate constraints adapted from Titus v1.2.9 (LICENSE.titus, NOTICE.titus)
// and TruffleHog v3.97.4 (repository AGPL-3.0); modified September 2026.
// Provider sources establish credential roles. Scanner ranges are not issuance
// guarantees; the companion fixtures record the boundary of each supported subset.
var auditedTokensRules2 = []catalogRuleSpec{
	{
		ID:              "facebook-app-secret",
		Regex:           `\b(?:(?:FACEBOOK|FB)_(?:APP|CLIENT)_SECRET["']?[ \t]*[:=][ \t]*["']?([A-Za-z0-9]{32,64})|(?:facebook|FACEBOOK)["']?[ \t]*[:=][ \t]*\{[^{}]{0,50}\b(?:app_id|client_id)["']?[ \t]*:[ \t]*["']?[0-9]{10,19}["'\s,][^{}]{0,100}\b(?:app_secret|client_secret)["']?[ \t]*[:=][ \t]*["']?([A-Za-z0-9]{32,64}))` + catalogRightBoundary + `|(?:^|[^A-Za-z0-9_.-])(?:"(?:[Ff][Aa][Cc][Ee][Bb][Oo][Oo][Kk]_[Aa][Pp][Pp]_[Aa][Cc][Cc][Ee][Ss][Ss]_[Tt][Oo][Kk][Ee][Nn]|[Ff][Bb]_[Aa][Pp][Pp]_[Aa][Cc][Cc][Ee][Ss][Ss]_[Tt][Oo][Kk][Ee][Nn])"|'(?:[Ff][Aa][Cc][Ee][Bb][Oo][Oo][Kk]_[Aa][Pp][Pp]_[Aa][Cc][Cc][Ee][Ss][Ss]_[Tt][Oo][Kk][Ee][Nn]|[Ff][Bb]_[Aa][Pp][Pp]_[Aa][Cc][Cc][Ee][Ss][Ss]_[Tt][Oo][Kk][Ee][Nn])'|(?:[Ff][Aa][Cc][Ee][Bb][Oo][Oo][Kk]_[Aa][Pp][Pp]_[Aa][Cc][Cc][Ee][Ss][Ss]_[Tt][Oo][Kk][Ee][Nn]|[Ff][Bb]_[Aa][Pp][Pp]_[Aa][Cc][Cc][Ee][Ss][Ss]_[Tt][Oo][Kk][Ee][Nn]))[ \t]{0,16}[:=][ \t]{0,16}(?:"([0-9]{15,16}\|[A-Za-z0-9_-]{27,64})"|'([0-9]{15,16}\|[A-Za-z0-9_-]{27,64})')` + catalogRightBoundary,
		Keywords:        []string{"FACEBOOK", "FB_"},
		SecretGroup:     0,
		ValidateContext: validateAuditedAssignmentContext,
		Source:          "https://developers.facebook.com/docs/facebook-login/guides/access-tokens/",
		Description:     "Facebook application/client secret in an explicit provider-qualified secret assignment or a bounded flat Facebook app-ID/client-secret object. Public app IDs, embedded client tokens and generic Facebook key labels are not sufficient. Body and pairing bounds adapt Titus v1.2.9, not an issuer grammar. Also recognizes complete quoted app-ID|app-access-token literals only in exact FACEBOOK_APP_ACCESS_TOKEN/FB_APP_ACCESS_TOKEN assignments. Generic and client-token pipe forms remain excluded because Meta uses the same serialization for public client tokens; bare percent separators are not URI encoding.",
	},
	{
		ID:              "facebook-access-token",
		Regex:           `\b(?:(EAACEdEose0cBA[A-Za-z0-9]+)|(?i:(?:FACEBOOK|FB)_PAGE_ACCESS_TOKEN)["\']?[ \t]{0,4}[:=][ \t]{0,4}["\']?(EAA[MC][A-Za-z0-9]{100,512}))` + catalogRightBoundary,
		Keywords:        []string{"EAACEdEose0cBA", "FACEBOOK_PAGE_ACCESS_TOKEN", "FB_PAGE_ACCESS_TOKEN"},
		SecretGroup:     0,
		Source:          "https://developers.facebook.com/docs/facebook-login/guides/access-tokens/",
		Description:     "Preserve historical bare EAACEdEose0cBA access tokens without changing their width or validator. Add the EAAM/EAAC 100-512 alphanumeric scanner subset only in exact FACEBOOK_PAGE_ACCESS_TOKEN or FB_PAGE_ACCESS_TOKEN assignments. Meta distinguishes confidential Page access from embedded public client tokens; generic provider proximity is not enough.",
		ValidateContext: validateBetterleaksFacebookContext1,
	},
	{
		ID:              "figma-legacy-access-token",
		Regex:           `\b(?:(figd_[A-Za-z0-9_-]{40})|(?:[Xx]-[Ff][Ii][Gg][Mm][Aa]-[Tt][Oo][Kk][Ee][Nn]|FIGMA_(?:TOKEN|ACCESS_TOKEN|API_TOKEN))["']?[ \t]*[:=][ \t]*["']?((?:[A-Fa-f0-9]{4}|[0-9]{6})-[A-Fa-f0-9]{8}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{12}))` + catalogRightBoundary,
		Keywords:        []string{"figd_", "figma"},
		SecretGroup:     0,
		ValidateContext: validateAuditedAssignmentContext,
		Source:          "https://developers.figma.com/docs/rest-api/personal-access-tokens/",
		Description:     "Historical Figma tokens: example-backed figd_ candidates, or UUID-composite values only in an explicit Figma token header/assignment. The malformed upstream prefix class is not copied; unconfirmed OAuth-style prefixes and punctuation alternatives are excluded. Existing figp_ candidates remain solely in figma-personal-access-token.",
	},
	{
		ID:          "firecrawl-api-key",
		Regex:       `\b(fc-[a-f0-9]{32})` + catalogRightBoundary,
		Keywords:    []string{"fc-"},
		SecretGroup: 1,
		Source:      "https://docs.firecrawl.dev/api-reference/introduction",
		Description: "Firecrawl bearer API-key candidate with the documented fc- marker and Titus v1.2.9 32-lowercase-hex subset. Strict token boundaries prevent prefix matches in longer identifiers; no issuance, billing or live validity verification.",
	},
	{
		ID:          "fireworks-api-key",
		Regex:       `\b(fw_[A-Za-z0-9]{24})` + catalogRightBoundary,
		Keywords:    []string{"fw_"},
		SecretGroup: 1,
		Source:      "https://docs.fireworks.ai/api-reference/create-api-key",
		Description: "Fireworks AI confidential bearer API-key candidate. The fw_ marker and 24-character alphanumeric subset follow Titus v1.2.9; the provider documents bearer usage and one-time key disclosure. No added entropy or digit requirements.",
	},
	{
		ID:          "fleetbase-api-key",
		Regex:       `\b(flb_(?:live|test)_[A-Za-z0-9]{20,64})` + catalogRightBoundary,
		Keywords:    []string{"flb_live_", "flb_test_"},
		SecretGroup: 1,
		Source:      "https://docs.fleetbase.io/developers/api/",
		Description: "Fleetbase live and test secret API keys. The provider explicitly documents both prefixes and forbids exposure in public repositories or client code. The bounded 20-64 alphanumeric body follows Titus v1.2.9 and includes TruffleHog v3.97.4 live keys; it is not issuer validation.",
	},
	{
		ID:          "flexport-api-key",
		Regex:       `\b(shltm_[A-Za-z0-9_-]{40})` + catalogRightBoundary,
		Keywords:    []string{"shltm_"},
		SecretGroup: 1,
		Source:      "https://developers.flexport.com/tutorials/using-api-credentials/",
		Description: "Flexport legacy API-key candidate in the pinned shltm_ 40-character URL-safe form. Flexport documents legacy API keys as bearer credentials granting API access; marker and width are TruffleHog v3.97.4 scanner evidence, not provider grammar. OAuth client IDs and JWT formats are not inferred.",
	},
	{
		ID:          "frameio-user-token",
		Regex:       `\b(fio-u-[A-Za-z0-9_-]{64})` + catalogRightBoundary,
		Keywords:    []string{"fio-u-"},
		SecretGroup: 1,
		Source:      "https://docs.frame.io/docs/authentication",
		Description: "Frame.io user developer-token candidate in the fio-u- 64-character URL-safe subset shared by Titus v1.2.9 and TruffleHog v3.97.4. Developer tokens are persistent bearer credentials with user scopes. No Adobe OAuth migration, padding alternatives or issuance verification is inferred.",
	},
	{
		ID:          "friendli-personal-access-token",
		Regex:       `\b(flp_[A-Za-z0-9]{46})` + catalogRightBoundary,
		Keywords:    []string{"flp_"},
		SecretGroup: 1,
		Source:      "https://friendli.ai/docs/guides/suite/personal_access_tokens",
		Description: "Friendli personal access token in the flp_ 46-alphanumeric Titus v1.2.9 subset. The provider documents tokens as an alternative to account sign-in and uses flp_ bearer examples. No online or internal-structure verification.",
	},
	{
		ID:              "google-oauth-client-secret",
		Regex:           `\b(?:(GOCSPX-[A-Za-z0-9_-]{28})|[0-9]+-[a-z0-9_]{32}\.apps\.googleusercontent\.com["'\s,;][\s\S]{0,39}?\b(?:client_secret|CLIENT_SECRET)["']?[ \t]*[:=][ \t]*["']?([A-Za-z0-9_-]{24}))` + catalogRightBoundary,
		Keywords:        []string{"GOCSPX-", "apps.googleusercontent.com"},
		SecretGroup:     0,
		ValidateContext: validateAuditedAssignmentContext,
		Source:          "https://developers.google.com/identity/protocols/oauth2/web-server",
		Description:     "Google GOCSPX- OAuth client-secret candidates and legacy 24-character client secrets paired with an actual Google client ID and mandatory client_secret assignment in the same value. The Titus v1.2.9 shape/pairing bound is a scanner subset; client IDs alone and arbitrary nearby 24-character strings are excluded.",
	},
	{
		ID:          "hubspot-private-app-token",
		Regex:       `\b(pat-(?:na1|eu1)-[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})` + catalogRightBoundary,
		Keywords:    []string{"pat-na1-", "pat-eu1-"},
		SecretGroup: 1,
		Source:      "https://developers.hubspot.com/docs/apps/legacy-apps/private-apps/overview",
		Description: "HubSpot private-app bearer token for the pinned na1/eu1 region prefixes and lowercase UUID-shaped body. Provider docs establish scoped account access; the region/body contract follows TruffleHog v3.97.4. Arbitrary pat regions and public client IDs are not inferred.",
	},
	{
		ID:              "hubspot-legacy-api-key",
		Regex:           `\b(?:[Hh][Aa][Pp][Ii][Kk][Ee][Yy]|HUBSPOT_API_KEY)["']?[ \t]*[:=][ \t]*["']?([A-Fa-f0-9]{8}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{12})` + catalogRightBoundary,
		Keywords:        []string{"hapikey", "HUBSPOT_API_KEY"},
		SecretGroup:     1,
		ValidateContext: validateHubspotLegacyAssignmentContext,
		Source:          "https://developers.hubspot.com/changelog/upcoming-api-key-sunset",
		Description:     "Legacy HubSpot API key only in a hapikey query/config assignment or explicit HUBSPOT_API_KEY assignment. HubSpot deprecated API-key auth, but historical telemetry remains secret material. A bare contextual UUID is not attributed to HubSpot; no generic heuristic is relied on.",
	},
	{
		ID:          "instagram-access-token",
		Regex:       `\b(IGQVJ[A-Za-z0-9_-]{50,})` + catalogRightBoundary,
		Keywords:    []string{"IGQVJ"},
		SecretGroup: 1,
		Source:      "https://developers.facebook.com/docs/instagram-platform/reference/access_token/",
		Description: "Historical Instagram IGQVJ access-token candidate using the Titus v1.2.9 URL-safe body and 50-character minimum. Tokens are confidential bearer material even though Basic Display was retired. The scanner shape does not establish current availability, expiry or scope; no fabricated maximum is added.",
	},
	{
		ID:          "intra42-client-secret",
		Regex:       `\b(s-s4t2(?:ud|af)-[a-f0-9]{64})` + catalogRightBoundary,
		Keywords:    []string{"s-s4t2ud-", "s-s4t2af-"},
		SecretGroup: 1,
		Source:      "https://api.intra.42.fr/apidoc/guides/getting_started",
		Description: "42 Intra OAuth client secret, distinguished from public u- client IDs by the s-s4t2ud-/s-s4t2af- marker. The exact prefixes and lowercase 64-hex body follow Titus v1.2.9 and TruffleHog v3.97.4; no environment semantics or verification is inferred.",
	},
	{
		ID:          "ionic-personal-access-token",
		Regex:       `\b(ion_[A-Za-z0-9]{42})` + catalogRightBoundary,
		Keywords:    []string{"ion_"},
		SecretGroup: 1,
		Source:      "https://ionic.io/docs/appflow/personal-access-tokens",
		Description: "Ionic Appflow personal token using the documented ion_ prefix and Titus v1.2.9 42-alphanumeric subset. Personal tokens authorize CLI/third-party access and are shown only at creation. No added entropy, expiry or scope validation.",
	},
	{
		ID:          "jina-api-key",
		Regex:       `\b(jina_[A-Za-z0-9]{60})` + catalogRightBoundary,
		Keywords:    []string{"jina_"},
		SecretGroup: 1,
		Source:      "https://docs.jina.ai/",
		Description: "Jina AI bearer API-key candidate with the jina_ prefix and Titus v1.2.9 60-alphanumeric body. Provider documentation requires bearer API authentication; exact body shape remains a scanner subset, not a generator or validity proof.",
	},
	{
		ID:              "klaviyo-private-api-key",
		Regex:           `\b(?:[Aa][Uu][Tt][Hh][Oo][Rr][Ii][Zz][Aa][Tt][Ii][Oo][Nn][ \t]*:[ \t]*[Kk][Ll][Aa][Vv][Ii][Yy][Oo]-[Aa][Pp][Ii]-[Kk][Ee][Yy][ \t]+|KLAVIYO_(?:PRIVATE_API_KEY|API_KEY)["']?[ \t]*[:=][ \t]*["']?)(pk_(?:[A-Za-z0-9]{6}_)?[A-Za-z0-9]{34})` + catalogRightBoundary,
		Keywords:        []string{"klaviyo"},
		SecretGroup:     1,
		ValidateContext: validateAuditedAssignmentContext,
		Source:          "https://developers.klaviyo.com/en/docs/authenticate_",
		Description:     "Klaviyo private API key in the complete Klaviyo-API-Key Authorization header or explicit KLAVIYO_API_KEY/KLAVIYO_PRIVATE_API_KEY assignment. The shared pk_ prefix is not accepted bare because other products use it for public keys. Scanner body alternatives are candidate constraints; six-character public site IDs are excluded.",
	},
	{
		ID:          "langfuse-secret-key",
		Regex:       `\b(sk-lf-[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})` + catalogRightBoundary,
		Keywords:    []string{"sk-lf-"},
		SecretGroup: 1,
		Source:      "https://langfuse.com/docs/api-and-data-platform/features/public-api",
		Description: "Langfuse secret half of public-key/secret-key Basic authentication in the pinned sk-lf-UUID subset. pk-lf- public keys and bare project UUIDs are excluded. UUID shape is a candidate constraint, not proof of authorization or a linked public key.",
	},
	{
		ID:              "launchdarkly-secret-key",
		Regex:           `\b(?:(?:((?:api|sdk)-[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[a-f0-9]{4}-[a-f0-9]{12}))|LAUNCHDARKLY_(?:ACCESS_TOKEN|API_KEY)["']?[ \t]*[:=][ \t]*["']?([A-Za-z0-9]{40}))` + catalogRightBoundary,
		Keywords:        []string{"api-", "sdk-", "LAUNCHDARKLY_"},
		SecretGroup:     0,
		ValidateContext: validateAuditedAssignmentContext,
		Source:          "https://launchdarkly.com/docs/home/account/environment/keys",
		Description:     "Confidential LaunchDarkly api-/sdk- UUIDv4-shaped keys and historical 40-character API tokens in an explicit LAUNCHDARKLY_ACCESS_TOKEN/API_KEY assignment. Server SDK keys are secret; mob- keys and client-side IDs are public and excluded. No live, UUID-variant or permission validation.",
	},
	{
		ID:              "mongodb-atlas-private-api-key",
		Regex:           `\bMONGODB_ATLAS_PRIVATE_API_KEY["']?[ \t]*[:=][ \t]*["']?([A-Fa-f0-9]{8}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{12})` + catalogRightBoundary,
		Keywords:        []string{"MONGODB_ATLAS_PRIVATE_API_KEY"},
		SecretGroup:     1,
		ValidateContext: validateAuditedAssignmentContext,
		Source:          "https://raw.githubusercontent.com/mongodb/terraform-provider-mongodbatlas/master/docs/guides/provider-configuration.md",
		Description:     "MongoDB Atlas legacy API private key only in the provider-documented MONGODB_ATLAS_PRIVATE_API_KEY assignment. The UUID-shaped subset comes from Titus v1.2.9. Public API keys, random UUIDs and loose MongoDB/Atlas proximity do not establish a secret.",
	},
	{
		ID:          "mongodb-atlas-service-account-secret",
		Regex:       `\b(mdb_sa_sk_[A-Za-z0-9_-]{6}[A-Za-z0-9]{34})` + catalogRightBoundary,
		Keywords:    []string{"mdb_sa_sk_"},
		SecretGroup: 1,
		Source:      "https://www.mongodb.com/docs/atlas/government/api/",
		Description: "MongoDB Atlas service-account client secret with the documented mdb_sa_sk_ role marker. The six URL-safe plus 34 alphanumeric body follows Titus v1.2.9 rather than a public issuer generator; public mdb_sa_id_ identifiers and arbitrary UUIDs are excluded.",
	},
	{
		ID:              "netlify-access-token",
		Regex:           `\b(?:(nfp_[A-Za-z0-9_]{36})|NETLIFY_AUTH_TOKEN["']?[ \t]*[:=][ \t]*["']?([a-fA-F0-9]{60,64}|[A-Za-z0-9_-]{43,45}))` + catalogRightBoundary,
		Keywords:        []string{"nfp_", "NETLIFY_AUTH_TOKEN"},
		SecretGroup:     0,
		ValidateContext: validateAuditedAssignmentContext,
		Source:          "https://answers.netlify.com/t/change-to-the-netlify-authentication-token-format/106146",
		Description:     "Netlify personal access tokens with nfp_ and legacy unprefixed tokens only in the explicit NETLIFY_AUTH_TOKEN assignment. Netlify states older tokens remain usable after the prefix transition. Scanner subsets constrain body alphabets/lengths; bare legacy hashes and provider proximity do not establish secrecy.",
	},
	{
		ID:          "pixie-api-key",
		Regex:       `\b(px-api-[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})` + catalogRightBoundary,
		Keywords:    []string{"px-api-"},
		SecretGroup: 1,
		Source:      "https://docs.px.dev/reference/admin/api-keys/",
		Description: "Pixie API credential with the px-api- role marker and Titus v1.2.9 lowercase UUID subset. A complete key authorizes applications to use Pixie; bare key IDs, UUIDs and deployment keys are distinct.",
	},
	{
		ID:          "pixie-deploy-key",
		Regex:       `\b(px-dep-[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})` + catalogRightBoundary,
		Keywords:    []string{"px-dep-"},
		SecretGroup: 1,
		Source:      "https://docs.px.dev/reference/admin/deploy-keys/",
		Description: "Pixie deployment credential with the px-dep- role marker and Titus v1.2.9 lowercase UUID subset. This distinct deployment secret is not inferred from a public cluster UUID or the separate API-key family.",
	},
	{
		ID:              "new-relic-license-key",
		Regex:           `\b(?:((?:[a-f0-9]{36}|eu01xx[a-f0-9]{30})NRAL|(?:[a-f0-9]{32}|eu01xx[a-f0-9]{26})FFFFNRAL)|(?:NEW_RELIC_LICENSE_KEY["']?[ \t]*[:=][ \t]*["']?|associated with your New Relic account\.[ \t\r\n]+license_key:[ \t]*)([a-fA-F0-9]{40}))` + catalogRightBoundary,
		Keywords:        []string{"NRAL", "NEW_RELIC_LICENSE_KEY", "New Relic"},
		SecretGroup:     0,
		ValidateContext: validateAuditedAssignmentContext,
		Source:          newRelicAPIKeysSource,
		Description:     "New Relic confidential telemetry-ingest license key: US/EU NRAL and FFFFNRAL layouts, or historical 40-hex keys in an explicit NEW_RELIC_LICENSE_KEY assignment or documented New Relic configuration banner. Browser/mobile ingest tokens and bare hashes are excluded. Layouts adapt Titus/TruffleHog rather than proving issuance.",
	},
	{
		ID:          "new-relic-admin-api-key",
		Regex:       `\b(NRAA-[a-f0-9]{27})` + catalogRightBoundary,
		Keywords:    []string{"NRAA-"},
		SecretGroup: 1,
		Source:      newRelicAPIKeysSource,
		Description: "Legacy New Relic admin API-key candidate in the NRAA- 27-lowercase-hex Titus v1.2.9 subset. An administrative API credential is confidential regardless of historical deprecation. No permission, availability or live validity claim.",
	},
	{
		ID:          "new-relic-insights-insert-key",
		Regex:       `\b(NRII-(?:[A-Za-z0-9_-]{25}|[A-Za-z0-9_-]{32}))` + catalogRightBoundary,
		Keywords:    []string{"NRII-"},
		SecretGroup: 1,
		Source:      newRelicAPIKeysSource,
		Description: "New Relic Insights insert credential in the NRII- 25- or 32-character URL-safe scanner subsets. New Relic documents legacy Insights keys as still supported, privileged ingest credentials. Intermediate lengths, browser/mobile keys and any live verifier are not inferred.",
	},
	{
		ID:          "new-relic-insights-query-key",
		Regex:       `\b(NRIQ-(?:[A-Za-z0-9_-]{25}|[A-Za-z0-9_-]{32}))` + catalogRightBoundary,
		Keywords:    []string{"NRIQ-"},
		SecretGroup: 1,
		Source:      newRelicAPIKeysSource,
		Description: "New Relic Insights read credential in the NRIQ- 25- or 32-character URL-safe scanner subsets. Read access to telemetry is confidential; a separate public account ID is unnecessary to recognize the secret. No length interpolation or online account verification.",
	},
	{
		ID:              "new-relic-legacy-api-key",
		Regex:           `\b(?:(NRRA-[a-f0-9]{42})|NEW_RELIC_(?:API_KEY|PERSONAL_API_KEY)["']?[ \t]*[:=][ \t]*["']?([A-Za-z0-9]{4}-[A-Za-z0-9]{42}))` + catalogRightBoundary,
		Keywords:        []string{"NRRA-", "NEW_RELIC_"},
		SecretGroup:     0,
		ValidateContext: validateAuditedAssignmentContext,
		Source:          newRelicAPIKeysSource,
		Description:     "Legacy New Relic REST/personal API credential: NRRA- with 42 hex characters, or the older four-character-prefix plus 42-alphanumeric form only in an explicit NEW_RELIC_API_KEY/PERSONAL_API_KEY assignment. Modern NRAK-27 keys remain in new-relic-user-api-key. Loose New Relic proximity is not sufficient.",
	},
	{
		ID:          "nightfall-api-key",
		Regex:       `\b(NF-[A-Za-z0-9]{32})` + catalogRightBoundary,
		Keywords:    []string{"NF-"},
		SecretGroup: 1,
		Source:      "https://raw.githubusercontent.com/nightfallai/nightfall-python-sdk/master/README.md",
		Description: "Nightfall confidential API-key candidate in the NF- 32-alphanumeric TruffleHog v3.97.4 subset. The provider SDK obtains API keys from the account dashboard and uses them for security-data scanning. Prefix/body constraints are scanner evidence, not authentication or issuer verification.",
	},
	{
		ID:          "notion-refresh-token",
		Regex:       `\b(nrt_[A-Za-z0-9_]{40,55})` + catalogRightBoundary,
		Keywords:    []string{"nrt_"},
		SecretGroup: 1,
		Source:      "https://developers.notion.com/guides/get-started/authorization",
		Description: "Notion OAuth refresh-token candidate with the provider-example nrt_ marker and Titus v1.2.9 40-55 alphanumeric/underscore subset. Refresh tokens obtain replacement access tokens; workspace/bot IDs and current/legacy access tokens are separate. Opaque tokens are not decoded or issuer-validated.",
	},
	{
		ID:              "nuget-api-key",
		Regex:           `\b(?:([Oo][Yy]2[A-Pa-p][A-Za-z2-7]{15}[AaQq][A-Za-z2-7]{25}[AaEeIiMmQqUuYy4])|(?:[Xx]-[Nn][Uu][Gg][Ee][Tt]-[Aa][Pp][Ii][Kk][Ee][Yy]|NUGET_API_KEY)["']?[ \t]*[:=][ \t]*["']?([a-z0-9]{46}))` + catalogRightBoundary,
		Keywords:        []string{"oy2", "nuget"},
		SecretGroup:     0,
		ValidateContext: validateAuditedAssignmentContext,
		Source:          "https://github.com/NuGet/NuGetGallery/blob/8b92773a792c86948e2f4c06595a2e8ebd1835a8/src/NuGetGallery/Infrastructure/Authentication/ApiKeyV4.cs",
		Description:     "NuGet v4 plaintext API key: base32 of ASCII v4 plus ten bytes, followed by independently unpadded base32 of a sixteen-byte GUID. Recognizes generator-derived version and padding bits with provider-supported case-insensitive representation. Also recognizes opaque 46-character legacy scanner candidates in the complete X-NuGet-ApiKey/header or NUGET_API_KEY assignment. No database lookup, hash or issuance verification.",
	},
	{
		ID:          "nvidia-api-key",
		Regex:       `\b(nvapi-[A-Za-z0-9_-]{60,70})` + catalogRightBoundary,
		Keywords:    []string{"nvapi-"},
		SecretGroup: 1,
		Source:      "https://docs.nvidia.com/nemo/retriever/26.5.0/extraction/api-keys/",
		Description: "NVIDIA NGC/NIM API-key candidate with the documented nvapi- prefix. The 60-70 URL-safe body follows Titus v1.2.9 and contains TruffleHog v3.97.4 64-character keys; no exact issuer-width claim is made. Public registry paths and legacy opaque keys are distinct.",
	},
	{
		ID:              "nvidia-legacy-api-key",
		Regex:           `\bNGC_API_KEY["']?[ \t]*[:=][ \t]*["']?([A-Za-z0-9]{84})` + catalogRightBoundary,
		Keywords:        []string{"NGC_API_KEY"},
		SecretGroup:     1,
		ValidateContext: validateAuditedAssignmentContext,
		Source:          "https://docs.nvidia.com/ngc/latest/ngc-user-guide.html",
		Description:     "Historical opaque NVIDIA NGC API-key candidate only in an explicit NGC_API_KEY assignment. The 84-alphanumeric encoded representation follows TruffleHog v3.97.4; bare encodings and decoded identifier:UUID strings are not recognized or recursively decoded. The credential role is established by the provider-specific carrier.",
	},
	{
		ID:              "nylas-api-key",
		Regex:           `\b(?:(nyk_[A-Za-z0-9]{67})|NYLAS_(?:API_KEY|ACCESS_TOKEN)["']?[ \t]*[:=][ \t]*["']?([A-Za-z0-9]{30}))` + catalogRightBoundary,
		Keywords:        []string{"nyk_", "NYLAS_"},
		SecretGroup:     0,
		ValidateContext: validateAuditedAssignmentContext,
		Source:          "https://developer.nylas.com/docs/v3/auth/hosted-oauth-apikey/",
		Description:     "Nylas nyk_ API key in the Titus v1.2.9 67-alphanumeric subset and legacy 30-alphanumeric credentials only in an explicit NYLAS_API_KEY/ACCESS_TOKEN assignment. Application API keys authorize mailbox/API access; regional URLs and bare unprefixed bodies are not secrets by themselves.",
	},
	{
		ID:          "pagarme-api-key",
		Regex:       `\b(ak_live_[A-Za-z0-9]{30})` + catalogRightBoundary,
		Keywords:    []string{"ak_live_"},
		SecretGroup: 1,
		Source:      "https://docs.pagar.me/v3/docs/api-key-e-encryption-key",
		Description: "Pagar.me live API-key candidate. The provider documents ak_ followed by live/test as the sensitive account authentication key; this rule retains the TruffleHog v3.97.4 live-only 30-alphanumeric subset. Public/encryption keys and inferred test-key widths are not imported.",
	},
	{
		ID:          "pganalyze-read-api-key",
		Regex:       `\b(pgar_[A-Za-z0-9]{27})` + catalogRightBoundary,
		Keywords:    []string{"pgar_"},
		SecretGroup: 1,
		Source:      "https://pganalyze.com/docs/api/create-api-key",
		Description: "pganalyze read API-key candidate in the pgar_ 27-alphanumeric TruffleHog v3.97.4 subset. Read-only access to GraphQL monitoring/query data remains confidential. Database IDs, query text and other unprefixed strings are excluded; no live request or permission check.",
	},
	{
		ID:          "photoroom-api-key",
		Regex:       `\b(?:sandbox_)?(sk_pr_[A-Za-z0-9]{1,64}_[A-Fa-f0-9]{40})` + catalogRightBoundary,
		Keywords:    []string{"sk_pr_"},
		SecretGroup: 1,
		Source:      "https://docs.photoroom.com/",
		Description: "PhotoRoom API secret in the sk_pr_<label>_<40hex> TruffleHog v3.97.4 subset, including an optional preceding sandbox_ transport marker. Captures the sk_pr_ secret, not the sandbox marker. Provider docs require password-like protection and x-api-key authentication; label bounds remain scanner constraints.",
	},
	{
		ID:          "portainer-api-key",
		Regex:       `\b(ptr_[A-Za-z0-9+/]{42}[AEIMQUYcgkosw048]=)` + catalogRightBoundary,
		Keywords:    []string{"ptr_"},
		SecretGroup: 1,
		Source:      "https://github.com/portainer/portainer/blob/develop/api/apikey/service.go",
		Description: "Portainer access token generated as ptr_ plus padded standard Base64 of 32 random bytes. Checks the generator length, alphabet, final zero padding bits and required equals sign without allocating or decoding. Rejects stored digests, seven-character display prefixes and scanner-only arbitrary URL-safe 20-60-character bodies; no hash/authorization verification.",
	},
}

func validateHubspotLegacyAssignmentContext(value string, start, end int, secret string) contextValidation {
	result := validateAuditedAssignmentContext(value, start, end, secret)
	if result.accepted || start == 0 || (value[start-1] != '?' && value[start-1] != '&') {
		return result
	}
	// In a query, '&' ends the complete hapikey value rather than continuing
	// a source expression. Keep ordinary assignment/header checks elsewhere.
	secretEnd := start + len("hapikey=") + len(secret)
	if secretEnd < end && strings.EqualFold(value[start:start+len("hapikey=")], "hapikey=") && value[secretEnd] == '&' {
		return contextValidation{accepted: true}
	}
	return result
}
