name: Dependabot Auto-Approve & Merge

on: pull_request

jobs:
  auto-approve-and-merge:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      pull-requests: write
      contents: write # Needed to merge PRs via gh CLI
    if: github.event.pull_request.user.login == 'dependabot[bot]' && github.repository == 'grafana/tempo'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false
      - name: Fetch Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@08eff52bf64351f401fb50d4972fa95b9f2c2d1b # v2.4.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Get GitHub App token
        id: app-token
        uses: grafana/shared-workflows/actions/create-github-app-token@259ba21cb3ff07724f331e26d926d655d24b317b # create-github-app-token/v0.2.3
        with:
          github_app: tempo-ci-app
      - name: Approve Dependabot PR
        # Only patch updates
        if: steps.metadata.outputs.update-type == 'version-update:semver-patch'
        run: gh pr review --approve -b "Automatically approved dependency update"
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          PR_URL: ${{ github.event.pull_request.html_url }}

      - name: Enable auto-merge
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          PR_URL: ${{ github.event.pull_request.html_url }}
