name: docker
on:
  push:
    branches:
      - 'main'
      - 'r[0-9]+'
    tags:
      - 'v*'

# Needed to authenticate to GAR with OIDC.
permissions:
  contents: read

env:
  DOCKERHUB_MIRROR_REPOSITORY: us-docker.pkg.dev/grafanalabs-global/dockerhub-tempo-prod-mirror

jobs:

  get-tag:
    if: github.repository == 'grafana/tempo'  # skip in forks
    runs-on: ubuntu-24.04
    outputs:
      tag: ${{ steps.get-tag.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: fetch tags
        run: git fetch --tags --force

      - id: get-tag
        run: |
          TAG="$(./tools/image-tag)"
          if [[ "$GITHUB_REF_TYPE" != "tag" ]]; then
            TAG="$TAG-${GITHUB_RUN_NUMBER}-${GITHUB_RUN_ATTEMPT}"
          fi
          echo "tag=$TAG" >> "$GITHUB_OUTPUT"

  docker:
    if: github.repository == 'grafana/tempo'
    needs: get-tag
    strategy:
      matrix:
        component: [ tempo, tempo-vulture, tempo-query, tempo-cli ]
        runner_arch: [ { runner: ubuntu-24.04, arch: amd64 }, { runner: github-hosted-ubuntu-arm64, arch: arm64 } ]
    runs-on: ${{ matrix.runner_arch.runner }}
    permissions:
      contents: read
      id-token: write
    env:
      TAG: ${{ needs.get-tag.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: fetch tags
        run: git fetch --tags --force

      - name: build-tempo-binaries
        run: |
          COMPONENT=${{ matrix.component }} GOARCH=${{ matrix.runner_arch.arch }} make exe

      - name: docker-build
        run: |
          TAG_ARCH="$TAG-${{ matrix.runner_arch.arch }}"
          docker build --provenance false --platform "linux/${{ matrix.runner_arch.arch }}" -f "cmd/${{ matrix.component }}/Dockerfile" -t "$DOCKERHUB_MIRROR_REPOSITORY/${{ matrix.component }}:$TAG_ARCH" .

      - name: Login to GAR
        uses: grafana/shared-workflows/actions/login-to-gar@12c87e5aa323694c820c1ff3d8e47e8237e05136 # login-to-gar/v1.0.2
        with:
          registry: us-docker.pkg.dev

      - name: docker-push
        run: |
          TAG_ARCH="$TAG-${{ matrix.runner_arch.arch }}"
          docker push "$DOCKERHUB_MIRROR_REPOSITORY/${{ matrix.component }}:$TAG_ARCH"

  manifest:
    if: github.repository == 'grafana/tempo'
    needs: ['get-tag', 'docker']
    permissions:
      contents: read
      id-token: write
    strategy:
      matrix:
        component: [ tempo, tempo-vulture, tempo-query, tempo-cli ]
    runs-on: ubuntu-24.04
    env:
      TAG: ${{ needs.get-tag.outputs.tag }}
      IMAGE_NAME: us-docker.pkg.dev/grafanalabs-global/dockerhub-tempo-prod-mirror/${{ matrix.component }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: Login to GAR
        uses: grafana/shared-workflows/actions/login-to-gar@12c87e5aa323694c820c1ff3d8e47e8237e05136 # login-to-gar/v1.0.2
        with:
          registry: us-docker.pkg.dev

      - name: docker-manifest-create-and-push
        run: |
          docker manifest create \
          	"$IMAGE_NAME:$TAG"               \
          	--amend "$IMAGE_NAME:$TAG-amd64"  \
          	--amend "$IMAGE_NAME:$TAG-arm64"
          docker manifest push "$IMAGE_NAME:$TAG"

  cd-to-dev-env:
    # This job deploys the latest main commit to the dev environment
    if: github.repository == 'grafana/tempo' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-24.04
    needs: ['manifest', 'get-tag']
    permissions:
      id-token: write
    steps:
      - name: Trigger Argo Workflow
        uses: grafana/shared-workflows/actions/trigger-argo-workflow@b513eb1dfd9becfa671a41e55063cdd5c0a08031 # trigger-argo-workflow/v1.2.2
        with:
          namespace: tempo-cd
          workflow_template: tempo-continuous-deployment
          parameters: |
            imageTag=${{ needs.get-tag.outputs.tag }}
