name: Github repo and issue stats collection
on:
  schedule:
    - cron: "*/30 * * * *"

permissions: {}

jobs:
  main:
    # this action keeps failing in all forks, only run in grafana/tempo.
    # stats collection action is only useful in main repo.
    if: github.repository == 'grafana/tempo'
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Get GitHub App token
        id: get-github-app-token
        uses: grafana/shared-workflows/actions/create-github-app-token@259ba21cb3ff07724f331e26d926d655d24b317b # create-github-app-token/v0.2.3
        with:
          github_app: tempo-ci-app
      - name: Checkout Actions
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          repository: "grafana/grafana-github-actions"
          path: ./actions
          ref: main
          persist-credentials: false
      - name: Install Actions
        run: npm install --production --prefix ./actions
      - name: Run metrics collector
        uses: ./actions/metrics-collector
        with:
          metricsWriteAPIKey: ${{secrets.GRAFANA_MISC_STATS_API_KEY}}
          token: ${{ steps.get-github-app-token.outputs.token }}
