name: syft-sbom-ci

permissions: {}

on:
  release:
    types: [created]

jobs:
  syft-sbom:

    runs-on: ubuntu-24.04

    steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      with:
        persist-credentials: false
        
    - name: Anchore SBOM Action
      uses: anchore/sbom-action@e22c389904149dbc22b58101806040fa8d37a610 # v0.24.0
      with:
         artifact-name: ${{ github.event.repository.name }}-spdx.json

