name: syft-sbom-ci

permissions: {}

on:
  release:
    types: [created]

jobs:
  syft-sbom:

    runs-on: ubuntu-24.04

    steps:
    - name: Checkout
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      with:
        persist-credentials: false
        
    - name: Anchore SBOM Action
      uses: anchore/sbom-action@66cbf4bc1f1c0d2edc94016e65bc221b6bb0ad6c # v0.24.3
      with:
         artifact-name: ${{ github.event.repository.name }}-spdx.json

